### ISSUE TITLE
prov/verbs: manual progress, call fi_cq_read with zero count does not drive progress

### ISSUE THREAD

**Issue by AOA-Mohammed** [ofiwg/libfabric#10068]
**Describe the bug**
In a libfabric application and doing `fi_read`, it gets `-FI_EAGAIN`. When calling `fi_cq_read` with zero count, nothing changes and `fi_read` keeps getting `FI_EAGAIN`. However, with `fi_cq_read` and count=1, fi_read eventually succeeds. 

**Expected behavior**
According to documentation "A count value of 0 may be used to drive progress on associated endpoints when manual progress is enabled."

**Environment:**
libfabric/1.21.0
verbs provider
NDR200 NICs

**Comment by aingerson** [comment]
After a quick glance at the code, I don't see an obvious reason for this. Verbs uses the util code which always drives progress, regardless of the count:
```
ssize_t ofi_cq_readfrom(struct fid_cq *cq_fid, void *buf, size_t count,
			fi_addr_t *src_addr)
{
	struct util_cq *cq;

	cq = container_of(cq_fid, struct util_cq, cq_fid);

	cq->progress(cq);

	return ofi_cq_read_entries(cq, buf, count, src_addr);
}
```
Can you provide your code or application to take a closer look or reproduce?

**Comment by AOA-Mohammed** [comment]
Thanks .... yes below are steps to reproduce
1. clone maestro: `git clone https://gitlab.com/maestro-data/maestro-core.git`
2. checkout the commit that shows the problem:
    git checkout 0226605583fbc44ea96107ad09947e5d2464793a
3. then configure and build:
`autoreconf -ivf; ./configure; make`
4. make sure to use verbs: `export FI_PROVIDER=verbs`
5. run tests: `make check`
you will notice that tests that start with check_pm_* (e.g. check_pm_declare.sh) occasionally fails as some components fail to complete `fi_read` with multiple `-FI_EAGAIN`. 
however, `make check` passes with commit 131e968ab68e620110d750bb53eb844b307fd7cb that do `fi_cq_read` with `1` for progress

**Comment by aingerson** [comment]
@AOA-Mohammed Thanks for the info. I was unable to build, it's failing configure for mamba but I'm unfamiliar with mamba. Can you help with the build error or provide context?
```
./configure: line 21071: syntax error near unexpected token `cuda_module,'
./configure: line 21071: `  PKG_CHECK_MODULES(cuda_module, $cuda_module_file,'
configure: error: ./configure failed for deps/mamba
```

**Comment by AOA-Mohammed** [comment]
This looks line configure can not find a macro "PKG_CHECK_MODULES", can you try to export aclocal path
`export ACLOCAL_PATH=/usr/share/aclocal` and try again? `autoreconf -ivf;` then `configure`

**Comment by aingerson** [comment]
@AOA-Mohammed Thanks for the tip. That didn't work for me but I managed to work around it by copying my aclocal pkg.m4 into the mamba m4 directory and running` aclocal -I m4` in the mamba directory to pick it up. Not sure what happened there but I got it to build.

As for the error, I'm not really sure what's going on here. I was able to see the error and reproduce what you're seeing. However, I also got a few runs of the working code that also failed (though much less frequent).
I wrote a test to try to recreate the failure you're describing and the test works fine.
I tried taking a look at your code to understand the flow but couldn't really follow it well without more information. From some logging I was able to see the read getting issued and a lot of returns from the call because the connection hadn't been established yet (maybe the remote side wasn't up yet?). It's hard to speculate further without understanding the flow of the application, but I would guess that maybe the target side is not driving progress to pick up the connection request. If you could provide more details on the flow or see if maybe that could be the case in your application, that would be helpful.

I'm attaching my reproducer in case you want to take a look (attaching as a .txt because github won't let me upload a .c file). Is this close to your flow? Is your target side initiating fully and driving progress while the peer tries to read? With the manual progress model, both sides need to be driving progress, even if they are not initiating a transfer. You could probably get around this by issuing a regular send/recv up front before the RMA request to ensure that the connection has been established inside the provider. Even then, however, the read is not guaranteed to succeed unless the target is also driving progress. 
From the man page:

FI_PROGRESS_MANUAL
This progress model indicates that the provider requires the use of an application thread to complete an asynchronous request. When manual progress is set, the provider will attempt to advance an asynchronous operation forward when the application attempts to wait on or read an event queue, completion queue, or counter where the completed operation will be reported. Progress also occurs when the application processes a poll or wait set that has been associated with the event or completion queue.
Only wait operations defined by the fabric interface will result in an operation progressing. Operating system or external wait functions, such as select, poll, or pthread routines, cannot.

**Manual progress requirements not only apply to endpoints that initiate transmit operations, but also to endpoints that may be the target of such operations. This holds true even if the target endpoint will not generate completion events for the operations. For example, an endpoint that acts purely as the target of RMA or atomic operations that uses manual progress may still need application assistance to process received operations.**


[rma_progress_test.txt](https://github.com/user-attachments/files/15842082/rma_progress_test.txt)

**Comment by chien-intel** [comment]
This is not a bug.  Verbs provider supports automatic progress (it is hardware offload after all) and polling CQ with count of zero is wasting a call.  You want to actually pull something off the CQ, use count > 0.

**Comment by aingerson** [comment]
@chien-intel Yes, verbs should handle this but they are using RDM so it's going through rxm which handles the connections and progress. rxm doesn't create the verbs EP until the other side tries to connect/send. So though the connection request is going through to verbs, rxm is never reading it off the EQ and able to actually create the connection.
@AOA-Mohammed Alternatively, you could try enabling auto progress in rxm (even when requesting manual progress) and see if that solves your issue (environment variable FI_OFI_RXM_DATA_AUTO_PROGRESS=1)

**Comment by chien-intel** [comment]
did I miss something in the bug report that mentioned RDM or RXM provider?

**Comment by aingerson** [comment]
No, he didn't explicitly say it was rxm but I'm looking at the code and they're using FI_EP_RDM

**Comment by AOA-Mohammed** [comment]
> As for the error, I'm not really sure what's going on here. I was able to see the error and reproduce what you're seeing. However, I also got a few runs of the working code that also failed (though much less frequent). I wrote a test to try to recreate the failure you're describing and the test works fine. I tried taking a look at your code to understand the flow but couldn't really follow it well without more information. From some logging I was able to see the read getting issued and a lot of returns from the call because the connection hadn't been established yet (maybe the remote side wasn't up yet?). It's hard to speculate further without understanding the flow of the application, but I would guess that maybe the target side is not driving progress to pick up the connection request. If you could provide more details on the flow or see if maybe that could be the case in your application, that would be helpful.

The code (for example check_pm_interlock.sh) starts three components, two clients and a pool manager (coordinator). The two clients wait until the pool manager is up and has built its endpoints before they start. At the start of the clients, they try to read (fi_read) some info from the pool manager, using connection information the pool manager has already put in the environment. Clients call fi_cq_read to make progress when fi_read fails with FI_EAGAIN and the pool manager is always reading the cq for comletions and posting receives. 

> I'm attaching my reproducer in case you want to take a look (attaching as a .txt because github won't let me upload a .c file). Is this close to your flow? Is your target side initiating fully and driving progress while the peer tries to read? With the manual progress model, both sides need to be driving progress, even if they are not initiating a transfer. You could probably get around this by issuing a regular send/recv up front before the RMA request to ensure that the connection has been established inside the provider. Even then, however, the read is not guaranteed to succeed unless the target is also driving progress. From the man page:
> 
Thanks for the reproducer. Yes, it is close to my flow. Yes, the target (pool manager) is fully initiated and driving progress while others try to read.

**Comment by AOA-Mohammed** [comment]
Thanks @aingerson for your reply and the reproducer code. 

I played a bit with the reproducer to understand the problem. The main difference between my code and the reproducer is that the latter retries` fi_read/write` in a while loop as long as it returns `FI_EAGAIN`. In my code, we give up on retrying after 3 or 5 (configurable) times. 

So I counted the number of retrials the reproducer needed for fi_read to succeed and it was around 3000. I added a 1 ms sleep between the retrials (similar to my code) and found it almost needed 15 times (on average). 

By setting `export MSTRO_OFI_NUM_RETRY=10` (number of fi_read retrials) for my code, some tests were able to pass and some still failed. Increasing it to 20 makes the tests always pass. (with the progress function reading zero cq entries). 

For the other case when the progress function reads at least 1 entry, 5 retrials was almost always enough. So it seems that calling fi_cq_read with 1 requires less retrials. I am not sure this is because calling fi_cq_read with count 1 (or more) is more costly or it makes more progress.

In any case, I see now this is not a bug, as `fi_cq_read` with zero eventually makes progress, therefore, I will close the issue. 

Thank you for your help.
