### ISSUE TITLE
Need clarification about fi_shutdown() and FI_SHUTDOWN events

### ISSUE THREAD

**Issue by sydidelot** [ofiwg/libfabric#10405]
(same question was asked on Slack)

Hi, I need some clarification about fi_shutdown() calls and related FI_SHUTDOWN events (my questions mainly concern on TCP and Verbs providers):

1. What is the regular flow to shutdown a connection that is establishing (FI_CONNECTED event not received yet)? Is the application expected to call fi_shutdown() or directly close the endpoint with fi_close() if the connection is establishing?
2. Is it safe to tear down the connection (fi_shutdown()) and immediately close the endpoint with fi_close() without waiting for the FI_SHUTDOWN event? Is there any risk of side effects, especially with the verbs provider (Inifniband/RoCE) where the same QP number is reused before timewait timeout expires? (@shefty, I would like to have your opinion on this point: https://general.openfabrics.narkive.com/N3q1lIZS/ofa-two-questions-about-rdma-cm-event-timewait-exit-and-the-timewait-state)
3. AFAIK, Verbs would emit a FI_SHUTDOWN (a.k.a RDMA_CM_EVENT_DISCONNECTED) event only when the connection was previously connected. Assuming that the application is required to the wait for the FI_SHUTDOWN event after fi_shutdown() (see point 2.), how would the application know the real EP state as seen by rdma_cm to determine if a FI_SHUTDOWN event will eventually be emitted? My concern is that the FI_CONNECTED event could be buffered in the EQ, causing the application and the verbs provider to have a different vision of the EP state.

**Comment by shefty** [comment]
FI_SHUTDOWN and fi_shutdown() are mostly there for applications to coordinate disconnecting.  Using fi_shutdown() is preferred for tearing down an *active* connection, as it may at least try to push out any queued data.  But fi_close() will also try to cleanup the connection as best it can based on the state.  The difference is that fi_shutdown() could result in retrying disconnect messages until the FI_SHUTDOWN event is generated, whereas, close is likely a one-shot try.

TCP flow:

fi_shutdown() calls shutdown().

1. If a connection isn't established, it doesn't really matter if the app calls fi_shutdown() or just fi_close().  fi_shutdown() is likely to fail internally (with ENOTCONN) with the error discarded.  An FI_SHUTDOWN event will be written to the EQ and the endpoint is disabled.  fi_shutdown() never fails with the TCP provider.
2. Calling fi_shutdown() immediately followed by fi_close() is equivalent to calling shutdown() + close().  I doubt that differs significantly from just calling close() on the socket.

Verbs flow:

fi_shutdown calls rdma_disconnect().

1. fi_shutdown() calls rdma_disconect(), which will fail (EINVAL) because of an invalid state.  The endpoint state remains unchanged.  An FI_SHUTDOWN event will *not* be generated.  It's possible for the endpoint to still connect.

2. Calling fi_shutdown() immediately followed by fi_close() should be similar to calling fi_close().  The app won't wait for a disconnect response, which reduces the number of times the message is sent.  If the disconnect message is lost, that could result in the peer holding onto the other half of the connection that is no longer valid.

The verbs timewait state is managed separately in the kernel from the lifetime of the user's rdma_cm_id.  The QPN won't be usable again until the timewait state exits.

3. Correct, with verbs, FI_SHUTDOWN will only occur if the endpoint was previously connected.  Note that there's always a delay in updating the user space state relative to the kernel.  Events will be written to the EQ in order.  So, if FI_CONNECTED is still on the EQ, then the app called fi_shutdown() on what it thought was an unconnected endpoint.  In this case, the fi_shutdown() will disconnect the QP, and the kernel will send a DREQ.  Eventually an FI_SHUTDOWN event will be queued to the EQ after the FI_CONNECTED event.  The fi_shutdown() call itself does not change the state of the user space endpoint.  The state is updated based on the EQ events that are read.

**Comment by sydidelot** [comment]
Thank you very much @shefty for the detailed answer!

> The verbs timewait state is managed separately in the kernel from the lifetime of the user's rdma_cm_id. The QPN won't be usable again until the timewait state exits.

If I understand your statement correctly, it is safe to shutdown (or close) the endpoint without waiting for the corresponding FI_SHUTDOWN event. This was my primarily concern with Verbs because according to the rdma_cm(7) man page, the application is supposed to wait for `RDMA_CM_EVENT_ESTABLISHED` after a call to rdma_disconnect(). I was worried that ignoring `RDMA_CM_EVENT_ESTABLISHED` would break rdma_cm.

**Comment by shefty** [comment]
It is safe to close the endpoint immediately.  The kernel has to be prepared to handle this case in case the application terminates.  When the rdma_cm_id is closed, the kernel will send either a DREQ (if connected) or REJ (still trying to connect) to the peer to notify them of the closed connection.  Timewait is managed separately.

rdma_disconnect() will return a failure if the rdma_cm_id is not in the connection state. This goes back to verbs item 1 above.  If the app calls fi_shutdown() -> rdma_disconnect() prior to the connection completing (getting an FI_CONNECTED event <- RDMA_CM_EVENT_ESTABLISHED), the fi_shutdown() behaves as a no-op.  The call fails.

If you meant waiting for the RDMA_CM_EVENT_DISCONNECTED event after calling rdma_disconnect(), that's not necessary relative to handling timewait.  It's only needed if the application needs to coordinate the disconnect with the peer.  For example, the peer is still trying to process received messages and will respond to the disconnect once it completes all its transfers.

**Comment by sydidelot** [comment]
It makes sense to me now. Thanks for your answers @shefty!
