### ISSUE TITLE
OFED 3.18-rc3: verbs provider fails to connect when ibacm is running at client

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#1109]
When running the `fi_msg` test program, if the `ibacm` daemon is running on the client with default configuration, the client will fail to connect.  It does not matter whether or not the ibacm daemon is running on the server.

I should note that OFED sets up ibacm to run automatically at startup.

This issue occurs with both the libfabric-1.0.0 and fabtests-1.0.0 included in OFED 3.18 and git master (currently 4cb4ac39fabd18ecbb2db849a1524ecf051cdb1c for me).

Using the librdmacm demo programs `rdma_client` and `rdma_server` works fine, as does `rstream`, so the libfabric verbs provider either has a bug or is exercising a bug or misconfiguration in ibacm.

@a-ilango Can you reproduce this issue in your test environment?

**Comment by a-ilango** [comment]
I have seen this before. Previously, even the rdmacm programs didn't work. May be that was in OFED 3.12? I have to check. Our test systems have OFED 3.18-rc3 installed now and I see that only OFI programs don't work.

@shefty do you remember this issue which we discussed sometime back? Was it due to ibacm cache having incorrect entries?

@patrickmacarthur for now, the workaround is to disable ibacm.

**Comment by shefty** [comment]
The past issues that we saw were related to ibacm having stale data.  That's not the case that Patrick is describing.  You can probably test this without installing OFED, if you manually install ibacm.

**Comment by a-ilango** [comment]
PR #1130 fixes this issue.

**Comment by patrickmacarthur** [comment]
Thanks, I will test later today and close the issue once I have verified the fix.

**Comment by patrickmacarthur** [comment]
I have verified that the issue has been fixed.
