### ISSUE TITLE
Allow specifying both source and destination address strings into fi_getinfo

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1117]
fi_getinfo() is really optimized around specifying either a source address <node, service> or destination address <node, service>.  For many real apps this should be sufficient.  However, it is difficult for an app to specify both the source and destination pairs without using a specific address format (such as sockaddr_in), which requires translating the address string.

Fabtest PR 271 (https://github.com/ofiwg/fabtests/pull/271) proposes calling fi_getinfo twice in this case.  This allows the providers to translate the <node, service> into their own address format using whatever mechanism is appropriate.

As an alternative to that option, we can allow fi_getinfo to accept both the source and destination <node, service> pairs.  There are a couple of options for this.  One would be to introduce a new fi_getinfo like API.  Alternatively, we could define something such as:

struct fi_node_service {
   const char *node;
   const char *service;
};

fi_info::src_addr may be set to this structure.  This structure is assumed when fi_info::addr_format = FI_FORMAT_UNSPEC and fi_info::src_addr is non-NULL.  fi_info::src_addrlen = sizeof(struct fi_node_service).

This would eliminate extra calls to fi_getinfo, while still allowing the providers to select the actual address format that is used.

**Comment by rfaucett** [comment]
I still say the best way to fix this issue is to overhaul addresses from a "void *" to a self-describing struct that looks like:
{code}
struct fi_address {
   enum fi_addr_type;   // FI_SOCKADD, FI_NODESERVICE, FI_UNSPEC, FI_WHATEVER
   void *data;       // type-specific
};
{code}
Then get rid of node and service arguments from fi_getinfo() and always use src_addr and dest_addr in the fi_info struct, much cleaner IMO.  The current "use node,service as dest or src depending on flags, and if not specified, then use what's in fi_info.{src,dest}_addr" is cumbersome to describe or implement.  FI_ADDR_NODESERVICE type means "data" is either 2 pointers to strings or a pointer to 2 back-to-back strings holding node and service.   Getting rid of the typeless void * address means addresses can be specified in different ways to a provider without ambiguity, as appropriate for the given context in which it is used.

**Comment by sayantansur** [comment]
With @rfaucett's approach, the struct fi_address might have 4 extra bytes of padding.

**Comment by shefty** [comment]
We should try to avoid breaking the ABI, and optimize around what we believe will be the common use case, not around testing.  I do not expect many apps to specify both the source and destination address.

**Comment by sayantansur** [comment]
If you're not expecting this to be a common usage, then is it worth it to modify libfabric? I mean, every provider will have to implement this special path, which is still somewhat cumbersome to use by the app.

**Comment by shefty** [comment]
I still think it's useful.  Specifying just the source or destination is easy.  Specifying both is cumbersome no matter what we do.  But just because that's cumbersome doesn't mean that i think we should make specifying just the source or destination cumbersome as well.  I'm not bothered that using two fi_getinfo calls is cumbersome, more that it invites errors when the returned attributes differ.

**Comment by sayantansur** [comment]
Yea, agreed.

**Comment by goodell** [comment]
1. I think Reese's suggestion of using self-describing addresses would be a big improvement to the API, but I understand that is a nontrivial change.  I don't think it's a great fix for this particular issue, but it would be a good general improvement.
2. Instead of requiring applications to call `fi_getinfo` a second time, I'd much prefer a new `fi_getinfo2` call with this signature:
```c
int fi_getinfo2(uint32_t version, 
               const char *src_node, const char *src_service,
               const char *dst_node, const char *dst_service,
               uint64_t flags, struct fi_info *hints, struct fi_info **info);
```
(incidentally, this is exactly what I was expecting all along when I first used `fi_getinfo`; I personally found `FI_SOURCE` to be confusing at first)

The implementation of `fi_getinfo` becomes pretty simple:
```c
int fi_getinfo(uint32_t version, 
               const char *node, const char *service,
               uint64_t flags, struct fi_info *hints, struct fi_info **info)
{
        if (flags & FI_SOURCE) {
                return fi_getinfo2(version, node, service, NULL, NULL, flags, hints, info);
        } else {
                return fi_getinfo2(version, NULL, NULL, node, service, flags, hints, info);
        }
}
```

**Comment by sayantansur** [comment]
Actually, on a node with multiple network interfaces, MPI might end up needing this functionality.

For example, rank 0 might want to specifically want to adapter 1, and rank 0 might want to use adapter 2.

**Comment by shefty** [comment]
What would MPI specify for the destination address?  I always viewed MPI as specifying only the source.

**Comment by sayantansur** [comment]
Ah yea. Never mind, I wasn't thinking right.

**Comment by shefty** [comment]
Re-visiting this, if there is an application requirement for specifying both the source and destination addresses using character strings, then I agree with Dave's proposal to add fi_getinfo2().  This addition would need to filter through to struct fi_provider.

**Comment by shefty** [comment]
The FI_ADDR_STR format allows specifying the source and destination addresses as strings through the fi_info src_addr and dest_addr fields.
