### ISSUE TITLE
ud_pingpong - server connect timeout message is terrible and too fast

### ISSUE THREAD

**Issue by rfaucett** [ofiwg/libfabric#1186]
When the fi_ud_pingpong server is started and you don't start the client within 5s, it prints:
server connect timeout(): /users/rfaucett/proj/ft/none/src/pingpong/ud_pingpong.c:467, ret=-11 (Resource temporarily unavailable)

This is a terrible message, looks totally like some libfabric internal error.
Better:
"%d second timeout expired waiting for message from fi_ud_pingpong client, exiting"

And the default should be more like 30 seconds, not 5.

**Comment by shantonu** [comment]
(1) ud_pingpong actually sets the default timeout to 5s. It can be fixed by setting it to 30s in the example.
(2) ud_pinpong uses non-blocking cq_read. According to the man page, it returns -FI_EAGAIN (which is printed as "Resource temporarily unavailable" err msg) if no completions can be found. This is also true for cq_sread. If cq_sread timeouts i.e. no completions are available, it returns -FI_EAGAIN. So, the behavior seems to be consistent with cq manpage. @shefty, @jithinjosepkl , please correct me if I'm wrong.

**Comment by shefty** [comment]
I think the test may need to handle the timeout differently based on whether it's the server side waiting on the first message.  I don't think Reese is saying that the behavior is wrong, just that the error message could be improved, particularly if the server times out waiting for the client to start.

**Comment by rfaucett** [comment]
(1) yes, timeout can be changed via command line, i am just saying the default is way too small.
(2) Sean is correct.  The primary reason we are timing out here is because the user did not get to another window fast enough and run the client.  The user should not have to read a man page or the ud_pingpong source code to figure this out.  If we time out in the middle of the run, that's another matter, which could also use its own, more explanatory message.

**Comment by shantonu** [comment]
Ok, sure! The test just prints the ret value it gets from cq_read. Since it was posted in as libfabric issue, I thought it's referring to the library :) I will create a PR in Fabtests then.

**Comment by rfaucett** [comment]
oops....  how did this get under libfabric???   I thought I opened it in fabtests...  sorry!!!

**Comment by shefty** [comment]
Fixed in fabtest
