### ISSUE TITLE
/tmp race in cron-run-all-md2nroff.pl

### ISSUE THREAD

**Issue by fweimer** [ofiwg/libfabric#1210]
This is rather harmless because it's not something users are exposed to:

    my $logfile_dir_arg = "/tmp";
    …
    $logfile_dir =
        sprintf("%s/cron-run-all-md2nroff-logs-%04d-%02d-%02d-%02d%02d",
                    $logfile_dir_arg, $year + 1900, $mon + 1, $mday,
                    $hour, $min);
    system("mkdir -p $logfile_dir");

The `system` call ignores the error, so the script will proceed if another user has created the directory with appropriate permissions.  You should use `File::Temp` instead.

**Comment by jsquyres** [comment]
I thought about using `File::Temp`, but decided against it because I wanted a specifically-named directory to make it easy to find the logfiles for a given failure (note: the logfile dir is not deleted if something fails, so that a human can go look at the logs later).

But you're right that any potential error with `mkdir` is ignored; I can add a `-d` check to ensure it was created properly.
