### ISSUE TITLE
FI_ORDER_DATA, max_order_size

### ISSUE THREAD

**Issue by Pgrun** [ofiwg/libfabric#1264]
Looking at clarifying the use of various ordering controls in the man pages.  First issue: the relationship between max_order_size and FI_ORDER_DATA is not clear - both claim to impact the way that data is written into target memory, (even though max_order_size is specific to RMA/Atomics only).

I think it may be clearer if we think of FI_ORDER_DATA and msg_order as controlling whether or not operations are ordered, and think of max_order_size as strictly controlling the upper limit on the size of RMA data for which ordering is enforced.

Consider this thought experiment:  What happens if FI_ORDER_RAW is set in the transmit and recv context, FI_ORDER_DATA is NOT set in the receive context, and max_order_RAW_size is set to some reasonable number?  Is the data for the two operations written to memory on the responder side in the proper sequence?

Supposedly, FI_ORDER_DATA also controls the writing of data into target memory...

If others agree, I will propose new language for the man pages to reflect this.

**Comment by shefty** [comment]
There are multiple issues being addressed by these attributes/flags.

In the simple case, we want to know if the data sent as part of a single transfer is written in order.  Whether we like it or not, apps rely on this in order to poll on memory to know when a transfer is complete.  FI_ORDER_DATA indicates if this is the case.  It indicates that byte x+1 of a transfer is written to memory (as viewed by a process) after byte x.  Or, more formally, if byte x+1 has been updated, then reading byte x will get the updated data.

When dealing with multiple transfers, apps need to know how their buffers will be matched with incoming requests.  FI_ORDER XAX helps with this.  Consider an app that has exposed a buffer to receive a single transfer (MSG or RMA), after which it is no longer accessible for fabric access.  This would provide security against other transfers modifying the data once it's been written.  This feature is used by the tag matching APIs, but there's no reason why the same concept couldn't apply to other types of transfers.

max_order_xax_size differs from FI_ORDER_DATA in that it deals with how data is written between two transfers.  It indicates that byte x of transfer n is written before byte y of transfer n+1, where x and y go to the same memory location.  It does not say anything about byte x versus byte x+1 of transfer n.

There is some overlap in meaning between FI_ORDER_XAX and max_order_xax_size when you restrict the context to only RMA operations to memory that is exposed for a long duration.  In that case, as an example, max_order_waw_size > 0 implies FI_ORDER_WAW.  However, FI_ORDER_WAW can be set even if max_order_waw_size = 0.  This makes sense if you consider that an RMA write may update a counter at the target.  If a counter value increases from n to n+1, the app needs to know if the increase came from write w or write w+1.  FI_ORDER_WAW can be used to indicate this.

In your thought experiment, assuming that the operations access the same memory, the read will see the data modified by the write.  However, the operations are allowed to read and write the data in any order.  I.e. the write may send all packets along different paths to the target, and they may update the target memory in any order.  Likewise, the read may return data along different paths, in any order.  The only restriction is that the read must end up with the updated write data *when it completes*.

Note what this actually allows is that the read can optimistically fetch data from the target, under the assumption that it will not change.  Then before the read completes, it can check to see if any data actually changed, and update the read data accordingly.  (Databases sometimes use a similar technique for transaction processing.)

So.... we at least need to know:

1. Are requests submitted by the application injected into the fabric in the same order as they are submitted?  (How are sequence numbers assigned?)
2. How are packets from a multi-packet transfer routed to the target?
3. How does the Rx context process packets as they arrive?

**Comment by shefty** [comment]
Is there an issue that still needs to be resolved, or can this be closed?  If there's still an issue, can the specific problem be clarified?

**Comment by Pgrun** [comment]
I will try to suggest some language to clarify all this.  It's subtle and complicated.
