### ISSUE TITLE
lib/libfabric directory created by make install from nightly tarball

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#1474]
We're noticing something weird about doing make install from the nightly tarball on
https://www.openfabrics.org/downloads/ofiwg/nightly_tarballs/v1.2.x/libfabric-latest.tar.bz2.

A make install creates a 

${INSTALL_DIR}/lib/libfabric 

subdirectory.  Do we really want this?  One doesn't get this behavior with a install using the tarball generated by make dist from a local repo.

**Comment by goodell** [comment]
Looks like this is just automake v1.11.1 creating `$(pkglibdir)` even if it's not actually directly used on your platform with your chosen set of `configure` arguments.  This directory is necessary if you were to pass `--enable-PROVIDER=dl` to `configure`, since this is where the provider shared objects end up being installed.

`flatbed` (or wherever the tarball creation cron jobs actually run) apparently does builds with automake v1.11.1, while my builds are usually done with v1.13.3.  The latter omits this recipe from the `install-pkglibLTLIBRARIES` rule:
```
        test -z "$(pkglibdir)" || $(MKDIR_P) "$(DESTDIR)$(pkglibdir)"
```

I'm sure we could track down when this change was introduced to automake and start doing our tarball bootstrapping with that version, but I don't think this extra directory is really causing anyone any harm.

**Comment by hppritcha** [comment]
okay, thanks for the explanation.  This doesn't sound like an issue.  closing.
