### ISSUE TITLE
usnic: FI_SHUTDOWN not triggered on FI_EP_MSG

### ISSUE THREAD

**Issue by wavesoft** [ofiwg/libfabric#1567]
I face this problem using the `libfabric-1.1.1` release. 
I am using the `usnic` provider with `FI_EP_MSG` endpoints, trying to create a socket-compatible interface.

In my code I am:
1. [Opening the core fabric resources](https://github.com/wavesoft/nanomsg-transport-ofi/blob/master/src/transports/ofi/hlapi.c#L780)
2. [Creating a passive socket](https://github.com/wavesoft/nanomsg-transport-ofi/blob/master/src/transports/ofi/hlapi.c#L713)
3. [Listening for incoming connections](https://github.com/wavesoft/nanomsg-transport-ofi/blob/master/src/transports/ofi/hlapi.c#L811)
4. Accepting connection, creating an active endpoint and [waiting for data to arrive](https://github.com/wavesoft/nanomsg-transport-ofi/blob/master/src/transports/ofi/hlapi.c#L399)

I can receive data without any problem, but the endpoint's EQ does not fire a `FI_SHUTDOWN` event when the other endpoint is [shut down](https://github.com/wavesoft/nanomsg-transport-ofi/blob/master/src/transports/ofi/hlapi.c#L951) or the connection times out.

I am not sure if this is implementation bug or if there is something wrong with my set-up (or this is something usNIC does not support). However when I use the `socket` provider everything works fine.

**Comment by bturrubiates** [comment]
From looking at the code it doesn't look like the `usNIC` provider supports `fi_shutdown`. Could you see if it is returning a negative error code? The call to shutdown should be returning `-FI_ENOSYS`.  I'll update the erroneous `fi_usnic` man page soon.

**Comment by wavesoft** [comment]
Indeed, it's returning `-FI_ENOSYS`, however my problem is mostly focused on the other end... even if I don't call `fi_shutdown` on the client endpoint, at some point the connection will be terminated (ex. after a network interrupt). 

So, rephrasing my question. Shall I assume that `usNIC` does not provide full session control and therefore will never trigger a `FI_SHUTDOWN` event on the server endpoint? Is there any other way to get notified when a connection is interrupted?

My next step will be to switch on a connectionless protocol and implement the session control on my application..

**Comment by bturrubiates** [comment]
I've submitted a pull request to fix the documentation issues and will open an issue to track the implementation of `fi_shutdown` and other connection management operations. Right now the `usNIC` provider does not fully support `EP_MSG`, but we're working on it. So for the moment we do not provide full session control and I don't think there is currently a way to get notified when a connection is interrupted.

**Comment by shefty** [comment]
@wavesoft - have you looked at rsockets by any chance?  That implements the sockets interface over RDMA devices (currently libibverbs and librdmacm), but there is a partial port of it over libfabric as well.  Is your work open source and available?  You can email me directly (sean.hefty@intel.com) rather than discussing this as part of this issue.

**Comment by wavesoft** [comment]
@bturrubiates - Thanks for the info. I read this on the `usnic` documentation, so I was kind of expecting this. I will run some benchmarks with my current set-up and it's highly probable that I will switch to `EP_DGRAM` in the near future. However I was looking for an 'off-the shelf' solution for my problem. 

@shefty - No, I haven't looked for rsockets, thanks for pointing this out. However in my case I already have a project that uses `libfabric` and I will need to create an adapter for it. My project will most probably be released under an open-source licence, however I will have to confirm with my superiors, since this is part of CERN Openlab research.

**Comment by jsquyres** [comment]
@wavesoft As you noted in the docs, EP_RDM is only "lightly tested" at this point because our focus has been on EP_DGRAM for use in Open MPI.  However, we're now starting to use libfabric+usNIC in other projects, so we're starting to improve libfabric usNIC support for requirements other than Open MPI's (e.g., EP_RDM and EP_MSG support).

I wanted to let you know that right before the libfabric v1.2.0 release, we found what appears to be a correctness bug in EP_RDM: #1621 -- doh!  Previously, we thought EP_RDM just performed poorly (because the implementation that is there is very much a first attempt and hadn't received much attention); we didn't find this correctness issue until it was too late to fix for v1.2.0.

We're working on this right now, but fi_waitset support may come first (per your #1629 issue).

**Comment by wavesoft** [comment]
@jsquyres Thanks for the update! For my current project I solved this problem by introducing a simplistic keepalive mechanism, but it would be great to have a proper implementation in the future. 

But also for my case, #1629 is more urgent.

**Comment by shefty** [comment]
usnic is still supported, but has not been updated in several releases.  Closing very old issues.
