### ISSUE TITLE
prov/usnic: libnl dependency issue

### ISSUE THREAD

**Issue by plebioda** [ofiwg/libfabric#1756]
I have libnl dependency issue on CentOS Linux release 7.1.1503.
After configuring the libfabric without any extra arguments and launching the fabtests/simple/fi_msg example the following assertion fault occurs:
```
fi_msg: route/tc.c:973: rtnl_tc_register: Assertion `0' failed.
```

I've found the same issue on libvma repo:
https://github.com/Mellanox/libvma/issues/24

with the following fix:
https://github.com/Mellanox/libvma/commit/319834aae95404dacd1185f1b1dbce09651bbcae

I didn't try to port this fix on the autotools scripts in libfabric, but the workaround is to disable usnic provider if one doesn't use it - like me.

libfabric: v1.2.0-238-ga241c88

**Comment by jsquyres** [comment]
This is a classic symptom for mixing libnl v1 and libnl v3 in the same application (thanks, libnl developers! :frowning:).

Can you run ldd on your libfabric.so and see if it links against both libnl and libnl-3?

Centos 7.1 -- if it's just like RHEL 7.1 -- has all of its libraries use libnl-3 (e.g., libibverbs).  Can you ensure that libnl-3-devel is installed?  That will allow libfabric to build with libnl-3 support instead of libnl support.

**Comment by plebioda** [comment]
Yes it links against both:
```
libnl.so.1 => /lib64/libnl.so.1 (0x00007f9b38686000)
libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x00007f9b37952000)
libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00007f9b37736000)
```
I didn't have libnl3-devel installed, but after installing it the problem dissappears.

**Comment by jsquyres** [comment]
Ok, good.  When configure finds both libnl3 and libnl, it prefers libnl3.

Over in the Open MPI project, [we have some (tentative) configury that might help detect this mixed-libnl-v1-and-v3 scenario](https://github.com/open-mpi/ompi/pull/1014), but it's not ready yet.

I'll close this issue now that you have it working.
