### ISSUE TITLE
OFIWG bot going crazy 

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1798]
Does anyone know why the man pages are being updated every 15 minutes? 

@shefty @jsquyres

**Comment by jsquyres** [comment]
@bturrubiates texted to alert me.  I've disabled the crontab on the new flatbed server.

After looking into this, I think the problem is that ofiwg-bot's crontab is still enabled on the old flatbed server, and there's a different version of pandoc between the two of them that generates slightly different nroff output (such that they're effectively fighting over the nroff-rendered man pages).

I've emailed Ken asking him to turn off the old server's crontab.  Once he does, I'll re-enable the crontab on the new server.

**Comment by shefty** [comment]
Has this been resolved?  I'm assuming so, but checking anyway.

**Comment by jsquyres** [comment]
Yes, this has been resolved.
