### ISSUE TITLE
usnic: Transition to using the util buf pool for EP_RDM and EP_MSG.

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1810]
The usnic provider currently manages free pools separately and has some error handling issues (`get_[tr]x_[wr]qe` don't report errors).

**Comment by bturrubiates** [comment]
After looking at this for a while it looks to me like we want to be using `ringbuf` from `include/fi_rbuf.h` instead. The `util_buf_pool` doesn't support keeping track of counts which is necessary for the `tx_size_left` and `rx_size_left` implementations.

**Comment by shefty** [comment]
The peanut gallery chiming in here.  The size_left calls are proving problematic in supporting.  I can't support them at all from the UDP provider, or not without introducing a lot of overhead only needed to support those calls.  I also do not plan on supporting them in the utility providers (RDM over DGRAM, shared memory, RDM over MSG, etc.) for the same reason.  They are simply too closely tied to a specific way of implementing the underlying queues to be of general use.

**Comment by bturrubiates** [comment]
> The peanut gallery chiming in here. The size_left calls are proving problematic in supporting. I can't support them at all from the UDP provider, or not without introducing a lot of overhead only needed to support those calls. I also do not plan on supporting them in the utility providers (RDM over DGRAM, shared memory, RDM over MSG, etc.) for the same reason. They are simply too closely tied to a specific way of implementing the underlying queues to be of general use.

For the endpoints that are software implemented in the usNIC provider we simply use the number of free entries in the request list.

Are there any API changes being considered surrounding this difficulty?

**Comment by shefty** [comment]
> For the endpoints that are software implemented in the usNIC provider we
> simply use the number of free entries in the request list.

But even a software based implementation is limited by supporting this.

Example 1: The TX queue is implemented as a circular queue, where each entry either contains command information or a IOV.  This model supports exactly 1 request for the maximum IOV size, or N requests of 1 IOV.  A get_size call can only return 1 if the queue is completely empty, otherwise it returns 0.  This model is arguably an optimized software based TX queue.

Example 2: The TX queue is really the RX queue of a peer.  This is a shared memory use case.

> Are there any API changes being considered surrounding this difficulty?

I just return -ENOSYS for the get_size calls.  But this makes it a call that apps cannot reliably invoke.  Maybe this means deprecating the calls?

In any case, trying to support these calls are forcing providers to implement queuing in a specific way, which may be suboptimal for performance or memory usage. I just happened to notice the comment in this thread that the implementation was being driven by the get_size calls.  And from this side of the peanut gallery, I chose to return -ENOSYS for them rather than add overhead just to return a sane value.

**Comment by bturrubiates** [comment]
> A get_size call can only return 1 if the queue is completely empty, otherwise it returns 0.  This model is arguably an optimized software based TX queue.

I'm not sure I understand this last part. Wouldn't the call return 0 if it was completely empty and `M/N` for the regular case (to get minimum count bounded by max IOV size)?

> I just return -ENOSYS for the get_size calls.  But this makes it a call that apps cannot reliably invoke.  Maybe this means deprecating the calls?

Yeah, if that's the case then it sounds like they should be deprecated in the next API update.



> Example 2: The TX queue is really the RX queue of a peer.  This is a shared memory use case.

This is a good example.

**Comment by shefty** [comment]
> 	A get_size call can only return 1 if the queue is completely empty,
> otherwise it returns 0. This model is arguably an optimized software based
> TX queue.
> 
> I'm not sure I understand this last part. Wouldn't the call return 0 if it
> was completely empty and M/N for the regular case (to get minimum count
> bounded by max IOV size)?

A queued operation consumes 1 entry for the command + 1 entry per IOV.  If the TX queue is size N, then max_iov = N - 1.  Get_size returns 1 when the queue is empty (1 request of maximum size).  So a simple send consumes 2 entries, leaving N - 2 free.  This means it can accept a request for up to N - 3 IOVs, which is smaller than the maximum.  In this case, get_size would need to return 0.

The way around this would be to artificially restrict max_iov to a smaller value, but the only reason to do so would be to support get_size.

**Comment by bturrubiates** [comment]
The `util_buf_pool` is not a good solution for this issue. The size left functions may be disappearing in a future release, we'll re-evaluate this at a later time.
