### ISSUE TITLE
When is it valid to use FI_GETWAIT on a CQ?

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1918]
The usNIC provider defers creation of the CQ until bind time. This means that we don't have a useful FD to give back before bind time. Depending on which endpoint the CQ is bound to the FD may be an eventfd or a FD supported and allocated by the hardware (in the case of DGRAM).  This isn't a problem with wait sets because they internally use an epoll fd allocated at open time.

Are there use cases for retrieving the wait object before the bind? Does the API say anything about the lifetime of the FD? If I retrieve an FD before a bind call and then call unbind and bind again, is the FD still usable?

The `fi_msg_epoll` test retrieves the FD before the CQ has been bound to an endpoint. Is this just a situation where the usNIC provider has to be explicit about a limitation and return `-FI_EAGAIN` if `FI_GETWAIT` is used before bind time? The provider passes the  `fi_msg_epoll` test if the bind is called before getting the wait object, is the fix just re-ordering these calls?

@shefty @goodell @jsquyres

**Comment by goodell** [comment]
I think we should update the general man pages to say that it may not be possible to `FI_GETWAIT` on an unbound CQ.  For the return value, `FI_EAGAIN` as you suggest might be OK, otherwise we could use something like `FI_ENOCQ` or `FI_EOPBADSTATE` for a little more clarity on the issue.

>  If I retrieve an FD before a bind call and then call unbind and bind again, is the FD still usable?

Ick, this is problematic for usNIC right now, with no easy fix in the stack on the visible horizon.  The good news is that I don't think apps actually want to do this, but the bad news is that not supporting it does violate the principle of least astonishment.

**Comment by shefty** [comment]
> The usNIC provider defers creation of the CQ until bind time. This means
> that we don't have a useful FD to give back before bind time. Depending on
> which endpoint the CQ is bound to the FD may be an eventfd or a FD
> supported and allocated by the hardware (in the case of DGRAM). This isn't
> a problem with wait sets because they internally use an epoll fd allocated
> at open time.

The API doesn't say anything about when the wait object must be valid.  Given that it seems that a user can expect to retrieve it immediately after calling fi_cq_create.

Also, note that there's nothing that restricts which type of EPs a CQ may be bound to.  So I don't think you can currently assume anything regarding which EPs will eventually be bound to a CQ based on the first binding.

The latter is an open issue that I plan to address in the ABI 1.1 release at the end of the year.  Providers need to know or enforce restrictions on a CQ when it is created.  Today there are no restrictions.

> Are there use cases for retrieving the wait object before the bind? Does
> the API say anything about the lifetime of the FD? If I retrieve an FD
> before a bind call and then call unbind and bind again, is the FD still
> usable?

I think you can argue that the fd of an unbound CQ isn't usable. :)

> The fi_msg_epoll test retrieves the FD before the CQ has been bound to an
> endpoint. Is this just a situation where the usNIC provider has to be
> explicit about a limitation and return -FI_EAGAIN if FI_GETWAIT is used
> before bind time? The provider passes the fi_msg_epoll test if the bind is
> called before getting the wait object, is the fix just re-ordering these
> calls?

I don't think there's any issue with reversing the order of the calls.  But the ultimate problem is deeper and requires an update to the fi_cq_attr structure, so that the CQ knows what type of EPs (include caps and mode bits) that it is dealing with.

**Comment by bturrubiates** [comment]
> The latter is an open issue that I plan to address in the ABI 1.1 release at the end of the year.  Providers need to know or enforce restrictions on a CQ when it is created.  Today there are no restrictions.

Some sort of restriction mechanism would help a lot in this kind of situation where one implementation is hardware driven and another is not. 

> I think you can argue that the fd of an unbound CQ isn't usable. :)

Agreed :ok_hand: 

> I don't think there's any issue with reversing the order of the calls.  But the ultimate problem is deeper and requires an update to the fi_cq_attr structure, so that the CQ knows what type of EPs (include caps and mode bits) that it is dealing with.

I'll submit a PR for fabtests. :+1: on the update, that'd be really helpful.

**Comment by bturrubiates** [comment]
Fixed by ofiwg/fabtests#499. A new issue will be opened to track the issues of CQ/EP pairings.
