### ISSUE TITLE
reporting loopback only/limited devices

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1975]
The question is how to handle devices that only support loopback (SHM) or cannot (usNIC).  Sockets provider can also report loopback as a device.

Feedback from the OFIWG is a request to always report loopback devices, like other providers, but add some layer of generic filtering that can be applied.

A new domain attribute is a possible solution.

**Comment by bturrubiates** [comment]
I've opened two new PRs (#2195 and #2196) for comments that demonstrate a couple of ways this problem could be solved. At the moment these both assume that the only two communication scopes are host local and global. Are these two scopes sufficient, or is it likely that a provider may want finer granularity?

**Comment by j-xiong** [comment]
Both RFC look good. The communication scope approach has more space to expand.  For near term goal (to characterize usNIC and SHM providers) either of them should serve the purpose. 

That being said, to explore a little bit on the aspect of finer granularity, let's take a look at these possible scopes:
(1) process local. a.k.a. "self".  
(2) node local. within the same OS image. that's where shared memory can be used.
(3) host local. within the same box. multiple OS images. can take advantage of local inter-OS fast communication mechanism. 
(4) remote. 

(1) and (2) would fall into the original definition of "local" scope. (3) and (4) would be considered as part of the original "remote" scope. The question remains whether we want to have process-local singled out since there is no reason a provider chooses not to allow process loopback communication if it support loopback at all. A more difficult task is to define the mechanism to distinguish (3) and (4).

**Comment by shefty** [comment]
Based on discussions of the fabric name reported by the sockets provider, I think we agree that none of the attributes indicate reach-ability.  An argument can be made that the loopback fabric is simply limited to the local node.  So, I don't think we _need_ to do anything special for handling a loopback provider.

As a recommendation, we may want to define and document a well-known fabric name for loopback fabrics, such as "localhost".

For limited devices that cannot support local communication, either we 'disallow' those (and use provider documentation to detail when they occur), or add a mode bit.  We're not in a great position here, since we have an in tree provider with this limit, but no way to expose it.  So adding a mode bit would actually break apps.
