### ISSUE TITLE
Version information for each call of the provider API

### ISSUE THREAD

**Issue by piroux** [ofiwg/libfabric#2182]
While working to update the fabric and domain names in the usnic provider per community conventions (see https://github.com/ofiwg/libfabric/issues/1974 and https://github.com/ofiwg/libfabric/issues/2052), we tried to use application-requested version information to retain the old fabric/domain name behavior for backward compatibility.  

In the end, we were not able to find a suitable solution because some API calls do not have a way to propagate the application-requested version information to the provider implementation.

Specifically, the `fi_getinfo()` API function has the `uint32_t version` param, which allows propagation of the app-requested version number down into the provider.  But the `fi_fabric()` API function does not have any access to versioning information (i.e., no version parameter, and no access to an info object returned via `fi_getinfo()`).  See [fi_prov.h](https://github.com/ofiwg/libfabric/blob/cca75dfe3ef59b6a70eabcdd32e077db1df2268b/include/rdma/providers/fi_prov.h#L67-71) :

``` c
int (*getinfo)(uint32_t version, const char *node, const char *service,
         uint64_t flags, struct fi_info *hints, struct fi_info **info);
int (*fabric)(struct fi_fabric_attr *attr, struct fid_fabric **fabric, void *context);
void (*cleanup)(void);
```

When libfabric is ready to change its API/ABI (e.g., in v2.0), we propose:
1. Add `const` to the `attr` parameter to `fi_fabric()` and the `fabric` op function pointer
2. Add a version parameter (similar to `fi_getinfo()`) to `fi_fabric()` and the `fabric` op function pointer
3. Add a version parameter (similar to `fi_getinfo()`) to the `cleanup` op function pointer

**Comment by shefty** [comment]
This problem has occurred to me.  I can think of a few options, but of these I prefer:

* Limit apps to using a single version
* Store a global version variable that's set by fi_getinfo
* Set the default version to the library version
* Require apps call fi_getinfo to change the version

Another option is adding version fields to either fi_info or fi_fabric_attr.  My concern is that the version passed into fi_getinfo be the same as what's set in fi_info or fi_fabric_attr.

The first proposal above doesn't require an API/ABI change - just a documentation update, which is likely backward compatible with all apps.

A simplification of that proposal, but which bumps the ABI, is to add a new call, fi_set_version(), which allows overriding the default version.  This way an app can set the version before calling fi_allocinfo.

**Comment by jsquyres** [comment]
We thought about these kinds of approaches, too, but did not like them because they involve hidden global state.  This somewhat defeats the point of the nice self-contained handle-based design of libfabric.

I.e., it's possible that an application could internally use two different libraries:

* Library A calls `fi_getinfo(FI_VERSION(x, y), ...)`
* Library B calls `fi_getinfo(FI_VERSION(a, b), ...)`

Where (x,y) != (a,b) -- and the two different libraries may therefore reasonably expect different behavior from libfabric.  More generally: an app can't always control what versions are passed to `fi_getinfo()` in its process.  If we want libfabric to take over the world, we should allow apps to request different versions from `fi_getinfo()`.

I think that if you pass a different version number to `fi_getinfo()` and `fi_fabric()`, and then pass the resulting info and fabric to `fi_domain()`, then libfabric should legally be allowed to rickroll you.  Or maybe just fail / return an error.

Our proposal of passing a version to `fi_fabric()` was mainly motivated by

1. simplicity (it's 7% easier than setting a member on the `fi_fabric_attr` struct), and (more importantly)
1. consistency with `fi_getinfo()`'s interface

**Comment by shefty** [comment]
If we're going to change the ABI around the version parameter, I think we need to determine if the version applies better at the fabric level or at a domain level.  Domains could come from different hardware vendors, which share the same fabric.

If we need to support users wanting different versions, then I think we should embed the version into fi_info or fi_fabric_attr.  This would be set by libfabric to match the version passed into fi_getinfo.  The user doesn't need to do anything other than pass the structure back.

On this approach, since fi_info references fi_fabric_attr, placing the version in the latter seems like the better option, subject to our thoughts on the above.

And that approach makes me note that fi_fabric_attr includes a prov_version and name fields.  Either of those could encode the fi_getinfo version data.  (I'm assuming that fi_fabric_attr come from fi_info, and is not hard-coded by the application.

**Comment by jsquyres** [comment]
There's several different conceptual versions here:

1. The version of the libfabric package
1. The version of the libfabric API
1. The API version that the application is asking for (in a few different possible locations, e.g., via `fi_getinfo()`, `fi_fabric()`, etc.)
1. The provider version that is reported back from `fi_getinfo()` in `info.fabric_attr.prov_version`

I personally think that if you getinfo to get an info back with version X, you should probably use that same version X back with all subsequent libfabric calls that derive from that info.  I don't think that we should guarantee consistent behavior if you modify the version (e.g., make a fabric with version X and a domain with version Y).

Meaning: reporting the version back in the info struct somewhere seems reasonable to me, and then we pass that info in to creating a fabric (we already pass in an info to creating a domain and endpoint).  In this way, the version can be at the top-level info struct -- it doesn't have to be in the fabric/domain/endpoint/etc. attribute sub-structs.

**Comment by shefty** [comment]
I want to avoid application source changes, so one of these options seem best:

    struct fi_fabric_attr {
        uint32_t version;

or

    struct fi_fabtic_attr {
        struct fi_info *info;

    struct fi_info {
        uint32_t version;

I'm thrilled about neither
