### ISSUE TITLE
Un-predictable performance in fi_msg_stream with file descriptor based waiting

### ISSUE THREAD

**Issue by supunkamburugamuve** [ofiwg/libfabric#2280]
The performance of the fi_msg_stream example is un-predictable for verbs provider with fd waiting. I was developing a system with this approach and encountered really strange issues where the program works fine sometimes and sometimes it slows down without any reason. So I looked at the example provided and found the same.

Here are some example runs. It seems this program doesn't complete sometimes. Look at the times and you can see that they vary from 17 sec to 74 sec. The client and server both were in the same machine for this particular case. 

[skamburu@j-login1 bin]$ ./fi_msg_stream -f verbs -S 1000000 -I 100000 -c fd 
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
976k    100k    93g        19.50s   5128.83     194.98       0.01
[skamburu@j-login1 bin]$ ./fi_msg_stream -f verbs -S 1000000 -I 100000 -c fd 
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
976k    100k    93g        24.65s   4057.11     246.48       0.00
[skamburu@j-login1 bin]$ ./fi_msg_stream -f verbs -S 1000000 -I 100000 -c fd 
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
976k    100k    93g        17.68s   5657.17     176.77       0.01
[skamburu@j-login1 bin]$ ./fi_msg_stream -f verbs -S 1000000 -I 100000 -c fd 
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
976k    100k    93g        79.15s   1263.40     791.51       0.00
[skamburu@j-login1 bin]$ ./fi_msg_stream -f verbs -S 1000000 -I 100000 -c fd 
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
976k    100k    93g        24.42s   4094.80     244.21       0.00

**Comment by a-ilango** [comment]
This seems to happen for smaller sizes (-S 10000), iterations (-I 100) and -c sread as well. I'll take a look. Thank you for reporting this.

**Comment by supunkamburugamuve** [comment]
Great let us know what you find. For now I've changed my program to use norma non-blocking completion queue reads.

**Comment by a-ilango** [comment]
In the test, the sender is overrunning the receiver sometimes. When and how often it happens might depend on how long sread or polling might take. In fact, I see this happening sometimes even in the case of polling on the CQ.

The reason the test takes random times to complete depends on the values, the verbs QP attributes, min_rnr_timer and timeout might take. Please look up the definitions of these attributes here:
http://www.rdmamojo.com/2013/01/12/ibv_modify_qp/

If we don't set them explicitly, I believe their values are chosen by the hardware/verbs implementation. When I ran the test multiple times, I noticed that the min_rnr_timer gets a different value each time. Since the sender waits until it gets an RNR NACK from the receiver to re-transmit the send, we see that the test takes a while to complete. We would see longer times when min_rnr_timer is set to values as high as ~245 ms

We don't have any control over these attributes in OFI (since it's using RDMACM). So the workaround is to post some receives in advance so that the sender doesn't overrun the receiver.

**Comment by supunkamburugamuve** [comment]
Thanks @a-ilango. The server I developed does post receives in advance. But unfortunately I saw the same behavior.

**Comment by a-ilango** [comment]
@supunkamburugamuve are you sure you're not overrunning the receiver? If the sender posts send at a faster rate then we would exhaust the preposted recvs soon and hit the issue again.
