### ISSUE TITLE
fi_pingpong compatibility

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2307]
I've just finished cleaning up the `fi_pingpong` test. 

Please test and let me know if there are issues or check off the appropriate box if it works as expected.
- [ ] gni
- [ ] mxm - deprecating
- [x] psm
- [x] psm2
- [x] rxd
- [x] sockets
- [x] udp
- [x] usnic
- [ ] verbs

@hppritcha @j-xiong @shantonu

**Comment by j-xiong** [comment]
It works fine with the latest psm and psm2 providers.

**Comment by bturrubiates** [comment]
> It works fine with the latest psm and psm2 providers.

Thanks!

**Comment by goodell** [comment]
@bturrubiates I wonder if it's clear to all provider maintainers what "works as expected" specifically means?  Do you have a concrete list of arguments/modes with which it should be run?  I haven't been following `fi_pingpong` closely, but I wouldn't know off the top of my head how to verify all the cases for the usnic provider.

**Comment by bturrubiates** [comment]
> @bturrubiates I wonder if it's clear to all provider maintainers what "works as expected" specifically means? Do you have a concrete list of arguments/modes with which it should be run? I haven't been following fi_pingpong closely, but I wouldn't know off the top of my head how to verify all the cases for the usnic provider.

By works as expected I just meant that a pingpong test can be launched using any of the following options:
- `p`, provider
- `-d`, domain
- `-e`, endpoint type
- `-S`, transfer size
- `-c`, data integrity checking

So, 

1. Can you launch a test with a specific provider (`-p`) and domain (`-d`) with all of the supported endpoint types and does the test have any issues? It should successfully ping and pong.
2. Can a test be launched for the provider with the `-S` option and it successfully runs that transfer size? Does it obey provider limits (it shouldn't allow anything higher than `ep_attr->max_msg_size`.
3. Does data integrity checking pass? If this fails, then it is more likely to be a bug in the provider code as this _should_ be provider independent, but it's good to test.

**Comment by a-ilango** [comment]
I see verbs check box ticked already. Did someone verify the test for verbs?

**Comment by bturrubiates** [comment]
> I see verbs check box ticked already. Did someone verify the test for verbs?

I think that was me copying from the old,PR. I'll uncheck that.

**Comment by shantonu** [comment]
Found an issue with sockets provider while testing ```fi_pingpong``` with domain name filtering. Submitted #2314 to fix the issue. All other tests works fine with sockets provider.

**Comment by bturrubiates** [comment]
> Found an issue with sockets provider while testing fi_pingpong with domain name filtering. Submitted #2314 to fix the issue. All other test works fine with sockets provider.

Thanks!

**Comment by a-ilango** [comment]
The test doesn't work with verbs provider as it doesn't pass one of node, service or hints->src_addr/dest_addr (on the server side). Verbs provider uses rdmacm which requires one of those args to be present. I think this restriction doesn't apply to fi_getinfo. So let me fix verbs to handle this.

**Comment by bturrubiates** [comment]
> The test doesn't work with verbs provider as it doesn't pass one of node, service or hints->src_addr/dest_addr (on the server side). Verbs provider uses rdmacm which requires one of those args to be present. I think this restriction doesn't apply to fi_getinfo. So let me fix verbs to handle this.

Right so this test will first call `fi_getinfo` on the server side and the only hint it may provide is the domain name. Once `fi_getinfo` has returned the usable fabric interfaces, the test just uses the first available interface. The server side then calls `fi_getname` and passes this across to the client via control messaging. The client uses this as a hint in `hints->dest_addr`.

**Comment by shefty** [comment]
We need to clarify when fi_getinfo can return a wildcard address.  Passive endpoints may not return a usable fi_getname that can be targeted by the client side of a connection.

Proposal: when FI_SOURCE is specified as a flag into fi_getinfo and the node parameter is NULL, the returned source address may contain a wildcard address.  fi_getname documentation should be updated to clarify that a passive endpoint may return a wildcard address if it was never bound to a specific source node address.

This test should also be added to the test scripts.

One other note, this file is large and copies existing code.  We have fabtests for full functionality testing.  I would much rather see this test be extremely simple -- a simple pingpong with few options.

**Comment by jsquyres** [comment]
@shefty You seem to be saying 3 things:

1. What to do if the name of a PEP contains a wildcard?
    * Do you have a suggestion here?  E.g., how do we even know if the name we got from `fi_getname()` contains a wildcard?
1. We need to add this to testing.
    * Which testing are you referring to?  `make test`?
1. This pingpong is too complicated.
    * We actually trimmed out a whole lot from the original pingpong.  What additional things do you want to trim out here?

**Comment by bturrubiates** [comment]
@hppritcha @sungeunchoi: Could you check if this works with the GNI provider? 

@a-ilango: How is the verbs support going? Are there still issues? 

@shefty: Could someone at Intel test this with MXM?

**Comment by shefty** [comment]
> 1.	What to do if the name of a PEP contains a wildcard?
> 
> 	*	Do you have a suggestion here? E.g., how do we even know if
> the name we got from fi_getname() contains a wildcard?

I think the test needs to be restructured to handle this.  fi_getname should be allowed to return a wildcard address, otherwise, all listens will be limited to a single network/IP address.

> 2.	We need to add this to testing.
> 
> 	*	Which testing are you referring to? make test?

Yes - make test

> 3.	This pingpong is too complicated.
> 
> 	*	We actually trimmed out a whole lot from the original
> pingpong. What additional things do you want to trim out here?

I would drop inject handling, for example.  I would need to look deeper into the code to see if anything else can be dropped.

**Comment by shefty** [comment]
> @shefty <https://github.com/shefty> : Could someone at Intel test this
> with MXM?

We plan on deprecating the mxm provider, as Mellanox is moving away from it.  So I don't think we care about mxm working with the pingpong test.  (I'm not sure MXM supports anything other than tag matching.)

**Comment by jsquyres** [comment]
@shefty Outside of the context of this issue, do you need to add some verbiage to README / whatever about the deprecation of MXM?  Do you plan to remove it in whatever the next libfabric release is after v1.4.0?

**Comment by shefty** [comment]
> @shefty <https://github.com/shefty>  Outside of the context of this
> issue, do you need to add some verbiage to README / whatever about the
> deprecation of MXM? Do you plan to remove it in whatever the next
> libfabric release is after v1.4.0?

Yes, we need to add some sort of documentation about deprecating mxm.  This topic only came up to me late last week.  The intent is to remove it from v1.5.

**Comment by a-ilango** [comment]
> How is the verbs support going? Are there still issues?

@bturrubiates I'm working on it. It should be ready soon.

**Comment by bturrubiates** [comment]
> @bturrubiates I'm working on it. It should be ready soon.

Cool, thanks.

**Comment by shefty** [comment]
These are the simplifications that I would make to the pingpong test:

- remove data verification
- remove data alignment code
- only support a single transfer size, with a (small) default
- have a fixed number of transfers, with a small default
- use fi_tostr to print fi_info data
- drop using the socket interface, use libfabric communication only
- use fi send/recv calls only

Really, this should be a very simple pingpong test, not a 2200 line program that duplicates hundreds of lines of code from a peer repository.

**Comment by jsquyres** [comment]
@shefty I guess we had different goals.  We weren't looking to create a dirt-simple pingpong; we had reasons for most of the items you listed:

* Data verification: an important use case of fi_pingpong is to verify that the fancy-schmancy high speed network you just bought is actually working.  Data verification is quite important for that.
* Data alignment: another important use case is to verify that you're not only getting correct data, but you're also getting the expected performance out of that fancy-schmancy high speed network that you just bought.  Alignment is important for that.
* Multiple transfer sizes: Two reasons here:
  1. Every customer has different religions about what data transfer sizes are important to them.
  1. Testing different transfer sizes is quite important for verification of network path MTU settings.
* Multiple number of transfers: does this really matter?
* Use fi_tostr: if we converted something manually that `fi_tostr()` should do, that can/should be fixed.  What are you referring to, specifically?
* Sockets: I think that we initially used the sockets API to avoid the PSM server startup delay issue.  I'm not 100% sure it's still an issue...?
* Fi send/recv: are you referring to the use of `fi_sendmsg()`?

**Comment by j-xiong** [comment]
It's not a startup delay issue, it's that in order to resolve peer "node" passed to fi_getinfo, the peer has to start the name server first (that happens when the domain is created). The use of socket to create a synchronization point before calling fi_getinfo was exactly the reason caused the issue. It was later resovled by exchange the address info via socket instead of resolving via fi_getinfo. However, that's just one way to get it work. Fabtests doesn't use socket and doesn't have the issue either.

**Comment by shefty** [comment]
I agree we have different goals.  I don't want to duplicate functionality that already exists in fabtests in another repository.  This isn't stressing all aspects of the API -- RMA and tag matching in particular don't show up -- probably because the usnic hardware doesn't do it.  So, the test is severely lacking in many respects, yet does far more than it needs to in order to answer the question if data can be transferred.

**Comment by jsquyres** [comment]
This program is basically a libfabric analog of `ibv_rc_pingpong` and `ibv_ud_pingpong`.  We decided to do DGRAM, RDM, and MSG in a single program, but they could be split up if people want to.  If we want an RMA-based pingpong, great -- that can be added, too.

> Sidenote: we didn't skip RMA support simply because usNIC doesn't support it -- we skipped it because we were just making an analog to `ibv_rc|ud_pingpong`.

The point: this pingpong is a *sysadmin tool*, not an *API testing tool*.  That is, sysadmins use `ibv_devinfo` and `ibv_*_pingpong` to verify the basic functionality of their verbs stacks and network hardware.  It's typically among the first things that they run when both verifying and troubleshooting.  Sysadmins can now do that in libfabric with `fi_info` and `fi_pingpong`.  Specifically: this pingpong is not intended to be a comprehensive API test -- it's a sysadmin test.

I forgot one other goal of this pingpong: to be a more-or-less straightforward example of the fi API for people to read without all the indirection of the fabtests tests.  Specifically: we've heard from multiple users and customers that the fabtests are really hard to read/grok because of all the `ft_` API indirection and conglomeration to be able to be used by multiple tests.  They're right.  This pingpong is a single, self-contained, standalone program.

Is there some code duplication between `fi_pingpong` and fabtests?  Essentially, yes -- there's only so many ways to write a pingpong program.  Additionally, the FI API implies a fairly common bootstrapping structure between all the tests (which is what a bunch of the indirection in fabtests aims to share).  But yes, this pingpong -- by definition of being a standalone too -- sorta duplicates the bootstrapping in fabtests (minus the indirection).  I don't know how to avoid that when having a standalone pingpong program in libfabric (not fabtests).

**Comment by shefty** [comment]
Yeah, I pretty much hate this test at this point.

**Comment by jsquyres** [comment]
I was just reminded of this issue.  I particularly love [@shefty's last comment](https://github.com/ofiwg/libfabric/issues/2307#issuecomment-250322720).  😄 

Given that we've been shipping `fi_pingpong` for a while, I'd say this issue can be closed.
