### ISSUE TITLE
fi_getinfo on Ubuntu/Debian

### ISSUE THREAD

**Issue by tschuett** [ofiwg/libfabric#2336]
I ran in an issue with fi_getinfo with the master branch. 1.3.0 does not show this issue.
I am looking for the sockets provider, but it returns "No data available".
```
struct fi_info* hints = fi_allocinfo();
struct fi_info* info = nullptr;
 
hints->ep_attr->type = FI_EP_MSG;

int res = fi_getinfo(FI_VERSION(1, 1), "myhostname", nullptr,
                                FI_SOURCE, hints, &info);
cout << fi_strerror(-res) << endl;
```
The issue is an entry in /etc/hosts:
```
127.0.1.1 myhostname.mycompany.com myhostname
```
The getaddrinfo call in sock_node_matches_interface returns 127.0.1.1 which matches neither eth0 nor lo. The reason for the 127.0.1.1 line is explained here:
https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution

**Comment by jsquyres** [comment]
@jithinjosepkl @shantonu Can you have a look?

**Comment by shantonu** [comment]
I looked at the issue. In sockets provider to get the list of local interfaces by calling ```getifaddrs```. But in Debian ```127.0.1.1```  is not returned by ```getifaddr```. We have to add ```127.0.1.1``` manually where ever we call ```getifaddrs```.

I discussed this with @shefty and we decided to add a wrapper call ```ofi_getifaddrs``` which will add ```127.0.1.1``` in the list of local interfaces when hostfile has this extra entry. I'll submit a PR.

**Comment by jsquyres** [comment]
This doesn't sound like a good solution -- you're putting a one-off comparison in for a system that chose to do something really weird.

It does highlight the difference between hostnames and resolvable names, however.  I.e., it clearly delineates that the hostname does *not* correspond to a specific interface (i.e., it's only convention on many other systems where the hostname just happens to correspond to one of the interfaces).

Meaning: should libfabric not be relying on a hostname to find an interface, but instead relying on names that resolve to local interfaces?

**Comment by shefty** [comment]
Well the system is doing a hack, so a hack in libfabric to work with it isn't too inappropriate.

I didn't follow your meaning.  Are you suggesting that the failure be the correct behavior?

**Comment by jsquyres** [comment]
I'm suggesting that perhaps we shouldn't be relying on a hostname, because technically, the hostname has nothing to do with a resolvable interface name.

**Comment by shantonu** [comment]
> I'm suggesting that perhaps we shouldn't be relying on a hostname, because technically, the hostname has nothing to do with a resolvable interface name.

I think we added the logic in sockets provider if a hostname matches a particular network interface to resolve the issue #2146 (where a resolvable address is given as source address, which doesn't match any local interface e.g. google.com). The problem with Debian is ```getifaddrs``` doesn't return ```127.0.1.1``` as local interface and when user specifies ```127.0.1.1``` as ```node``` parameter in ```fi_getinfo```, it fails.

Do you have any suggestions how to handle the issue?

**Comment by jsquyres** [comment]
If we're requiring a local *interface* and someone gives us a *hostname* that does not resolve to a local interface, I'd call that an error.

That being said, I agree that while hostnames are not *technically* the same thing as interface names, most users think that they are.  And what Debian/Ubuntu is doing here is downright weird / contrary to most conventions.

When failing to resolve a name to a local interface:

1. Plan to return a failure from the API call
1. See if you can resolve it to a 127.0.0.0/8 address via getifaddrs().  If you can, then we're in this situation (i.e., that it's likely a hostname, but not an interface name).  If libfabric verbosity is enabled, you can emit a helpful message describing the situation, and advising them to use a local interface name and/or network address (i.e., it's ok to emit a paragraph-long verbose message -- we call these "show help" messages in Open MPI).

**Comment by shefty** [comment]
> 2.	See if you can resolve it to a 127.0.0.0/8 address via
> getifaddrs(). If you can, then we're in this situation (i.e., that it's

So I think the sockets provider could change its special handling of addr == 127.0.0.1 to something like addr & 0x7f000000 == 0x7f000000 (using proper constants, endianess, etc.)

**Comment by jsquyres** [comment]
@shefty Are you proposing the following compromise: if the name resolves to a 127.0.0.0/8 address, then assume that the user is asking for the loopback interface?

If so, I could probably agree to that.  It probably is the least astonishing to the user.  It would be good, however, to emit a verbose log message when the name specified did not correspond to an interface, and libfabric defaulted to/assumed that the user meant the loopback interface.

Specifically: in this case, loopback is making a "You specified X, but I *assume* you meant Y" kind of choice.  So we should have some kind of verbose logging / debug way of letting the user know we have made that choice.

**Comment by shefty** [comment]
Yes - that sounds good.

**Comment by shantonu** [comment]
Sounds good to me!

**Comment by tschuett** [comment]
The solution is surprising to users, because the code above is not portable (Debian vs non Debian).

Will there be any advice to users on how to work around this issue? I was looking for `info->src_addr` for off-node communication and now I am going to end up with the loopback device. Should I call `getifaddrs` to get an IP address from an ethX device and call `fi_getinfo` with this IP address? Should I perform a DNS lookup to get the real IP address?

**Comment by jsquyres** [comment]
@tschuett Are you saying that users expect to specify `myhostname` and have it map to some non-loopback interface on their machine?  If so, how do we know which one it should be?

**Comment by tschuett** [comment]
Would you expect `myhostname-ib0` to point to a loopback device?

I am saying that you should query the DNS server for the IP of `myhostname` instead of looking at `/etc/hosts`. The IP will map to the correct device.

With the current solution, I have to pass an IP address to `fi_getinfo`when I use `FI_SOURCE`. Using a hostname is not portable.

**Comment by jsquyres** [comment]
@tschuett I think you misunderstand the proposal.  Here's what we're proposing for when a local address is required:

1. Resolve the provided name.
    * I haven't looked at the specifics of the sockets provider, but it's most likely calling `gethostbyname()`, or something similar.
    * Such functions will directly convert a string containing a numeric IP address to binary form.  E.g., if the string is "10.11.12.13", that will simply be converted to 10.11.12.13.
    * Or, if a string name is provided that is not simply a numeric IP address in string form, resolve it using the system resolver.  The system resolver typically first looks in `/etc/hosts`, and if not found, then use DNS (the configuration of the system resolver is outside the scope of libfabric).
1. If the provided name fails to resolve, error.  This is what already happens today.
1. Now that we have an IP address for the provided name, call `getifaddrs()` to get a list of interface addresses on the machine.
1. If the resolved IP address we got corresponds to an interface address on the machine, good -- we're done.
1. If not:
   1. ***This is the new part:*** If the resolved IP address is in the 127.0.0.0/8 block, then assume that the user meant to use the local loopback device.  So go find a local interface in the 127.0.0.0/8 address, and use that one.  In verbose mode, emit a warning message indicating that we assumed that the user meant the local loopback device, even though the name they supplied did not resolve to an actual interface.
   1. Otherwise, error.

My comments above are about making the distinction between the *hostname* of a machine, and the *names that resolve to interfaces on a machine*.  Technically, they are different things, and the hostname of a machine is not required to resolve to any interface.

## Case 1

For example, I can have a machine configured thusly:

1. Hostname: `foo`
1. Interface: 127.0.0.1/8
    * `/etc/hosts` contains a line: `127.0.0.1 localhost`
1. Interface: 10.10.10.10/24
    * The name `bar.mydomain.com` resolves to `10.10.10.10`, either via `/etc/hosts` or DNS

I.e., most people would expect that since the hostname of the machine is `foo`, that `foo` (or `foo.mydomain.com`) would also resolve to an interface on that machine.  But that's not so in this case -- the network interface on this machine corresponds to the name `bar.mydomain.com`.

So if a user specifies `foo` as the name to a libfabric API, what interface should we use?

In this case, presuming that `foo` does not resolve to an IP address at all, libfabric should error.

(this is not a change from existing behavior; I'm just giving an example of where the hostname is not, in fact, resolvable to a local interface)

## Case 2

Consider a machine that is configured like case 1, but *also* has a local entry in `/etc/hosts`:

```
127.0.1.1 foo
```

(i.e., this is a Debian / Ubuntu machine like your issue describes)

So if a user specifies `foo` as the name to a libfabric API, what interface should we use?

In this case, libfabric will be able to resolve `foo` to 127.0.1.1, but that does *not* correspond to any interface on the local machine.  Hence, the new behavior that we're proposing is that libfabric will conclude, "Oh, you specified a name that does *not* correspond to a local interface, but you *probably* meant a loopback-like device, since the name that `foo` resolved to is in the 127.0.0.0/8 block."

------

So your question of "Would you expect `myhostname-ib0` to point to a loopback device?" is an entirely different case.  Presumably, the name `myhostname-ib0` has an `/etc/hosts` and/or DNS entry that resolves that name to an IP address that corresponds to an IPoIB interface on the local machine.  If that is the case, then we're done and the new / proposed behavior doesn't come into play at all.

Does this all make sense?

**Comment by tschuett** [comment]
Thanks for the explanation. That makes sense now.

**Comment by jsquyres** [comment]
@bturrubiates and I were reading through the back-story of this issue (i.e., going back and reading the Debian docs, which point back to older posts on the Debian devel mailing lists, etc.).  Here seems to be the original suggestion where the 127.0.1.1 idea came from:

https://lists.debian.org/debian-boot/2005/06/msg00938.html

From this mail, it sounds like they really wanted the hostname to *not* resolve to any IP address at all (assuming there is no local interface that corresponds to that hostname, e.g., in DNS).  ...but that would break too many things.  So the 127.0.1.1 workaround was made for the short term (and the long term solution is to not resolve the hostname to an IP address at all).

Meaning: perhaps my proposed workaround of having the hostname default over to a valid localhost interface actually goes against the intent of what the Debian people were trying to do.

Instead, perhaps we should make *no* special case for the hostname at all.  If a name fails to resolve, then return a failure from `fi_getinfo()`.  Period.

**Comment by shantonu** [comment]
So the current behavior seems to be correct for Debian. Right?

**Comment by jsquyres** [comment]
@shantonu Do we do any special handling for 127.0.0.0/8 addresses at all in the current sockets provider?

But with the rationale from what I posted a few hours ago, I think the behavior should be: if a name is given that does not match a local IP interface, then we should return an error.  If this is the behavior we already have, then I think that is correct behavior.

**Comment by shantonu** [comment]
@jsquyres, nothing special is done for ```127.0.0.0/8``` except we report it at the end of the list-of-available-network-interfaces when fi_getinfo is called without any src_addr (required for SHMEM).

Currently, if ```/cat/hosts``` has the following line -
```
127.0.1.1 myhostname
```
and ```fi_getinfo(..., "myhostname", ...,FI_SOURCE, hints, &info)``` is called, sockets provider returns 
```-FI_ENODATA``` which was reported in this issue.

**Comment by shefty** [comment]
It appears that the current behavior is correct and intended.
