### ISSUE TITLE
what is the ep_per_node field of fi_av_attr for?

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2389]
While reading the `fi_av.3` man page, I noticed the `ep_per_node` field of the `fi_av_attr` structure. It is defined as: 

> This field indicates the number of endpoints that will be associated with a specific fabric, or network, address. If the number of endpoints per node is unknown, this value should be set to 0. The provider uses this value to optimize resource allocations. For example, distributed, parallel applications may set this to the number of processes allocated per node, times the number of endpoints each process will open.

It doesn't look like any providers support this. The description doesn't make much sense to me. What is this for? 

@shefty

**Comment by shefty** [comment]
This allows a provider to optimize its address storage.  For example, suppose an address consists of a 4-byte network address, followed by a 2-byte transport address.  The typical case would result in consuming 6-bytes (or possibly 8 due to alignment) per endpoint.  However, if the provider knows that there will be 128 EPs per node, it can store the network and transport addresses separately.  Using the same example, this reduces the addressing memory footprint from 768 bytes per node(6 x 128) to 260 bytes (4 + 128 x 2).  If the EP addresses are consecutive, the footprint can be further reduced to only a few byte per node.

**Comment by shefty** [comment]
@bturrubiates - please close if this sufficiently answers your question

**Comment by bturrubiates** [comment]
> @bturrubiates - please close if this sufficiently answers your question

Yeah that sufficiently answered my question, thanks.
