### ISSUE TITLE
Document flow control for remote CQ (i.e., immediate) data

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#240]
There needs to be a way to detect overflow of the CQ due to remote CQ data on RDMA_WRITE-type operations (where there would not normally be an event generated on the remote CQ).  It would also be nice to allow the receiver to reserve a certain number of CQE's for remote CQ data.

**Comment by shefty** [comment]
A domain level 'resource management' option was defined.  If FI_RM_ENABLED is set, the provider is expected to do 'something' to prevent receive CQ overflow from occurring.  This could be by forcing the app to retry or blocking receives from being posted in order to prevent the CQ from being overrun.  From an interface perspective, I think we're okay here.  From an implementation/protocol perspective, I think there's work to do.  But we can only control the API.  :)
