### ISSUE TITLE
Extend memory region modes to enable hardware acceleration

### ISSUE THREAD

**Issue by mblockso** [ofiwg/libfabric#2548]
Continuing discussion from #2444 

The current memory region modes bundle two distinct attributes in their definition. The first is whether the key may be specified by the user or whether the key is generated by the provider and the user is required to exchange these keys with remote processes. The second is whether the remote memory is addressed using an offset or a virtual address.

The `FI_MR_SCALABLE` mode is defined as having a key that may be specified by the user and the remote memory is addressed using an offset into the remote memory region.

The `FI_MR_BASIC` mode is defined as having a key that is generated by the provider which must be exchanged and the remote memory is addressed using the virtual address of the remote memory.

What needs to be added are the other two combinations of key type and addressing type. This will enable hardware acceleration on certain providers, such as bgq.

There are a few ways to enable these memory region modes. We could add a new `mr_addr` enum to the `fi_domain_attr` structure to specify offset- vs virtual- addressing. If the mr addr is unspecified, the value would default to the v1.4 libfabric definition of the mr_mode. In other words, if `FI_MR_SCALABLE` is specified for the `mr_mode` and the `mr_addr` is unspecified, then mr addr would default to "offset". Similarly, if `FI_MR_BASIC` is specified then the mr addr would default to "virtual".

Another option is to extend the `mr_mode` enum to include all combinations. For example:

    enum fi_mr_mode {
      FI_MR_UNSPEC = 0,
      FI_MR_BASIC = 1,
      FI_MR_SCALABLE = 2,
      FI_MR_BASIC_VIRTUAL = 1,
      FI_MR_SCALABLE_OFFSET = 2,
      FI_MR_BASIC_OFFSET,
      FI_MR_SCALABLE_VIRTUAL
    };

Duplicating the enum values for FI_MR_BASIC and FI_MR_SCALABLE maintains backward compatibility (assuming that the compiler assigns the values as expected!). Alternatively, providers can check for the v1.4-style mr enum and internally convert the value. In either case, the `FI_MR_SCALABLE` and `FI_MR_BASIC` enum values would remain valid.

@shefty @sayantansur @hppritcha @pkcoff

**Comment by shefty** [comment]
With the proposed raw memory region support, a provider should be able to support FI_MR_BASIC and convert.  This would introduce additional overhead in RMA operations -- the key would be used to convert an address into an offset, but it is also an option.

Which feature does bgq support?  Offset based addressing or user provided key? What is the key size used by bgq?

The MR mode implies one more property than those mentioned: whether the memory backing the region must be backed by physical memory.  So, in total there are 8 different combinations that are possible, plus a local registration mode.  The local mode behavior depends on whether basic or scalable is selected.

Of the proposed changes, the one that seems the most natural is to add new enum values to fi_mr_mode. (Btw, the C standard defines how enum values are defined.)  But an enum is also a poor choice to represent what would essentially be bit flags...

**Comment by mblockso** [comment]
> Which feature does bgq support? Offset based addressing or user provided key? What is the key size used by bgq?

The bgq hardware would use a provider-supplied key that must be exchanged between all peers (as in `FI_MR_BASIC`) and would use offset-based addressing (as in `FI_MR_SCALABLE`). 

> The MR mode implies one more property than those mentioned: whether the memory backing the region must be backed by physical memory.

All memory is pinned and backed by physical memory.

If you must know the nitty gritty details, the key will contain the base physical address of the memory being registered and actually only needs 42 bits to store this information. The bgq hardware uses absolute physical addresses for rdma operations, so the `fi_write()` implementation takes the key (base physical address) and adds the addr (interpreted as an offset) to it to get the absolute physical address on the remote node.

If I understand the raw memory region proposal correctly it would add some amount of overhead for this specific platform. To use `FI_MR_BASIC` the raw key needs to contain 2 types of information: the 42 bit base physical address, **and** the 64 bit base virtual address. The `fi_write()` call will provide the remote virtual address of the memory to be updated. The base virtual address is needed to subtract from this remote virtual address in order to obtain the offset (which the caller of `fi_write` probably already knows). The offset is added to the base physical address as before.

These raw keys need to be exchanged with all peers which may initiate rma and atomic operation and then mapped to a "normal" 64 bit key. This mapping could be accomplished in many ways, but for the moment let's assume that it is a pointer to a copy of the raw key. This means that the critical path will include a pointer dereference, and likely a cache miss, followed by some extra math to obtain he absolute physical address of the remote memory.

Question: what is the lifespan of the raw key that is exchanged? After the remote maps it to a "normal" 64 bit key, can the memory for the raw key structure be freed?

> But an enum is also a poor choice to represent what would essentially be bit flags...

I much prefer replacing the memory region mode enum with bit flags, but I assumed this would cause too much headache for maintaining ABI compatibility since the `fi_domain_attr` structure does not already contain a "flags" field.

**Comment by shefty** [comment]
I agree that the raw proposal would add more overhead, and I would not list it as my top option for this.

I *think* you could make use of Mr. Basic if you used:

key = base virtual address - base physical address
offset = virtual address passed into read/write call - key

The key is set when registering, and the offset is calculated at the peer.  The overhead is trivial.

It's possible to convert the enum into an int and use it as flags. So that is an option if we want to expose apps to more possible memory registration options.

**Comment by shefty** [comment]
I missed answering one of your questions -- once a key has been mapped, the raw data can be deleted.  The provider isn't even required to store anything unless it needs to.  Note that there is an open issue that came out of the ofiwg discussions related to how an app indicates that it no longer needs a raw key, so that the provider knows it can free any internal allocations.

**Comment by sdvormwa** [comment]
> The current memory region modes bundle two distinct attributes in their definition.

Actually more than two--in addition to the addressing and key, there is also a distinction of "registration occurs on allocated data buffers" vs "registration occurs on memory address ranges".  A provider can't currently support user-defined keys and offset-based addressing if they don't also support memory regions with "holes" (eg. unmapped pages in the region) and on-demand paging (eg, the client isn't responsible for notifying ofi if the the page-table gets updated after a region was created) as well.  It'd be nice to address those attributes as well.

**Comment by mblockso** [comment]
With the addition of domain capability and mode bits (#2534) could we change this 'mr_mode' enum into equivalent domain mode bits?

For example:
- FI_MR_MODE_ADDR_OFFSET | FI_MR_MODE_ADDR_VIRTUAL
- FI_MR_MODE_KEY_EXCHANGE | FI_MR_MODE_KEY_DIRECT
- FI_MR_MODE_PAGING

(change these names as you wish - they are just placeholders)

**Comment by shefty** [comment]
Before discussing _how_ to expose this, I think we need to determine if we _want_ to expose this additional complexity to the application.  I'd really like to come up with ways to simplify life for the application developers, while still providing mechanisms to support a broad set of implementations.  For example, raw memory region support expands implementation support by providers, without complicating apps that already use FI_MR_BASIC, since the new raw mechanism can always be used.

An application that has to insert a bunch of different code paths based on various flags isn't necessarily going to gain any performance by removing them from the provider.  (This applies to all of the capabilities exposed by the API and not just the MR calls, which are already too complex IMO.)

**Comment by sdvormwa** [comment]
>  I'd really like to come up with ways to simplify life for the application developers, while still providing mechanisms to support a broad set of implementations.

What is simplifying for some users can make things a lot more complicated for others, particularly where memory management (registration, addressing, etc) is concerned.  As a potential user, my preference would be for more options rather than fewer, as historically the chosen fewer options aren't the ones that are going to benefit my use case...

> For example, raw memory region support expands implementation support by providers, without complicating apps that already use FI_MR_BASIC, since the new raw mechanism can always be used.

I'm not following this.  As far as I understand the raw memory region support (I'm assuming you are referring to [PR 2392](https://github.com/ofiwg/libfabric/pull/2392)), it doesn't talk about capabilities of the region at all, merely the format of the MR key.  Or are you suggesting building on top of that?

> An application that has to insert a bunch of different code paths based on various flags isn't necessarily going to gain any performance by removing them from the provider.

My particular use case benefits greatly from user-defined keys (or at least computable without having to communicate with the remote peer, which user-defined keys can satisfy) and support for memory regions that aren't backed by physical pages at the time of registration.  Currently, this functionality is tied to a bunch of other stuff that I don't really care about, notably on-demand paging, that make it likely that providers will either opt to (1) not implement it at all, or (2) implement it in such a way that the performance is terrible (eg, falling back to two-sided communication or some kind of active messages rather than truly one-sided RMA).  Neither of these options are particularly appealing to me.

**Comment by mblockso** [comment]
> What is simplifying for some users can make things a lot more complicated for others, particularly where memory management (registration, addressing, etc) is concerned. As a potential user, my preference would be for more options rather than fewer, as historically the chosen fewer options aren't the ones that are going to benefit my use case...

+1

In my experience with MPICH, the code that creates the memory regions is already separated from the code that uses the memory regions (I believe a similar code structure is also used in Sandia OpenSHMEM). Right now the setup pseudo code is like this:
```C
struct mpi_mr {
    struct fid_mr * mr;
    uint64_t key;
    uintptr_t base_vaddr;
    uint64_t peer_key[0];
};

setup_mpi_memory_region (...) {
    struct mpi_mr * my_mpi_mr;

#if defined (USE_MR_SCALABLE)
    /* all peer memory regions will use the same key */
    my_mpi_mr = (struct mpi_mr *) malloc(sizeof(struct mpi_mr));
    my_mpi_mr->key = CALCULATE_DESIRED_KEY(....);
    fi_mr_reg(..., my_mpi_mr->key, ..., &my_mpi_mr->mr, ...);

#elif defined (USE_MR_BASIC)
    /* peer memory regions may use a different key - must exchange keys before use */
    my_mpi_mr = (struct mpi_mr *) malloc(sizeof(struct mpi_mr) + sizeof(uint64_t) * num_peers);
    fi_mr_reg(...,, &my_mpi_mr->mr, ...);
    my_mpi_mr->key = fi_mr_key(my_mpi_mr->mr);
    EXCHANGE_KEYS(my_mpi_mr->key, &my_mpi_mr->peer_key[0], num_peers, ...);
#endif

    my_mpi_mr->base_vaddr = (uintptr_t) virtual_address_of_my_buffer;
}
````
... and it is used at runtime as in the following pseudo code:
```C
MPI_Put(..., target_rank, target_disp, ...) {
    fi_addr_t dest_addr = convert_mpi_rank_to_fi_addr(target_rank, ...);

# if defined (USE_MR_SCALABLE)
    /* use offset-based addressing mode */
    fi_write(..., dest_addr, target_disp, my_mpi_mr->key, ...);

#elif defined (USE_MR_BASIC)
    /* use virtual address mode */
    fi_write(..., dest_addr, my_mpi_mr->base_vaddr + target_disp,
        my_mpi_mr->peer_key[target_rank], ...);
#endif
}   
```

*My point is* that one only needs to replace those ifdefs appropriately to handle this new "verbose" memory region attribute idea.

The setup code would replace "USE_MR_SCALABLE" with "FI_MR_MODE_KEY_DIRECT", and then replace "USE_MR_BASIC" with "FI_MR_MODE_KEY_EXCHANGE ".

The MPI_Put code would replace "USE_MR_SCALABLE" with "FI_MR_MODE_ADDR_OFFSET", and then replace "USE_MR_BASIC" with "FI_MR_MODE_ADDR_VIRTUAL".

IMHO, this new style is easier to understand and maintain while the complexity is no greater than before.

**Comment by hppritcha** [comment]
I like this approach.  I don't think it adds undue complexity to libfabric consumer applications, as @mblockso illustrated in the previous comment.

**Comment by shefty** [comment]
This still feels like it is being completely driven by the provider up, rather than application down -- and for a system that is no longer produced.  Not every app re-compiles every time it changes provider.  So far, apps have only asked for FI_MR_SCALABLE support.  Everything else is just exposing provider implementation restrictions that the app needs to code around.  For the specific problem that raised this issue, what is wrong with using something like what I described above:

I think you could make use of Mr. Basic if you used:

key = base virtual address - base physical address
offset = virtual address passed into read/write call - key

The key is set when registering, and the offset is calculated at the peer. The overhead is trivial.

**Comment by sdvormwa** [comment]
> So far, apps have only asked for FI_MR_SCALABLE support.

As an "app" developer, at least in the sense of being a libfabric user, I would love FI_MR_SCALABLE if I had any confidence whatsoever that providers would actually implement it efficiently enough to warrant using it.  Unfortunately, the more functionality that is tied to it, the more likely it is that at least one piece will make it difficult for a provider to implement efficiently.  If the functionality that I want is natively supported by the network I'm using, but libfabric's design prevents me from using it efficiently because that functionality is tied to other functionality, I'm really struggling to see why I would want to use libfabric...

**Comment by sayantansur** [comment]
The intention is supposed to be that as the app developer, you express the semantic we need, and the provider implements it in the most efficient manner possible on the platform. Therefore no net wasted work, and simpler apps.

The discussion we should really be having is WHY it is faster for the app to do all the legwork vs. the provider just implementing the semantic.

So far, I haven't really heard what provider authors would want to make their lives simpler when implementing MR_SCALABLE.

**Comment by shefty** [comment]
I separate remotely accessed MRs into two categories based on whether the app must exchange data or not.  It was arguably a mistake to change how the remote buffer was addressed based on whether data was exchanged or not (i.e. virtual address versus offset).

The biggest issue we've hit is that in the data exchange case, the data is too limiting.  You only get a 64-bit key.  The raw MR support patch attempts to address that issue.

I agree with Mike that if we only add the ability to select VA versus offset based addressing when data exchanged is required, then there's basically no impact to the peer.  But a more generic approach would be to allow the provider to select the base address.

**Comment by sdvormwa** [comment]
> The intention is supposed to be that as the app developer, you express the semantic we need, and the provider implements it in the **most efficient manner possible on the platform**. Therefore no net wasted work, and simpler apps.

That's nice in theory.  In practice, *if the provider implements it at all* (supporting FI_MR_SCALABLE isn't mandatory after all...), it is likely to be done quickly as a check-off item unless an important client pushes for it.  Otherwise there is no business case justifying spending the development time to make it work well as opposed to simply working at all.

> The discussion we should really be having is WHY it is faster for the app to do all the legwork vs. the provider just implementing the semantic.

On many networks, there isn't a single "most efficient" way to implement FI_MR_SCALABLE.  There are trade-offs that must be weighed, many of which are dependent on the behavior of the particular application.  I doubt you'll find many providers that provide multiple implementations of FI_MR_SCALABLE individually tuned for various use cases...

> So far, I haven't really heard what provider authors would want to make their lives simpler when implementing MR_SCALABLE.

On-demand paging in response to network traffic is a pretty major one.

**Comment by sdvormwa** [comment]
> ...
> The key is set when registering, and the offset is calculated at the peer. The overhead is trivial.

How do you expect this to work in the case of a region created with fi_mr_regv() and more than one segment?  If the underlying network treats the sections as a single contiguous buffer, then the "key" it transmits to the remote side is going to have to include a complete map of VA->offset to properly interpret the VA the user passes in.

**Comment by shefty** [comment]
These are the attributes that I'm aware of that are related to RMA-able MRs based on all hardware that I'm aware of:

- The MR may be aligned/sized on byte or page boundaries.  Other alignment may be possible, but I'm not aware of any.
- The MR may result in pages being pinned or not, depending on whether the provider has access to the OS page tables.
- For pinned pages, pages may be pinned only for the duration of the transfer, or for a potentially unlimited amount of time.  This can affect fork support and is often related by the MR alignment restrictions.
- Key lengths may be different sizes.
- Key values may be given by either the provider or application.
- The remote address used to access the MR may be a virtual address, offset based, or provider selected.
- MRs may be associated with domains, endpoints, or both.
- A MR may remain valid until closed by the registering program, or may be closed as part of a data transfer operation.
- MRs may be modified after creation.
- MRs may require that virtual addresses be back by physical pages at time of registration or not.
- MRs may refer to a SGL of arbitrary size.
- MR creation may be a synchronous operation, asynchronous operation, and may or may not generate entries on a completion queue.
- A peer may need to perform some sort of preparation function prior to targeting a MR.

There are probably more attributes, but these are what I can think of at the moment.  Job key support still needs to be added to this.  I'm *VERY* hesitant of going down the path of trying to expose every single attribute that every provider may need.  That would lead to a completely insane and unusable API.

There's a general agreement to expand support for larger keys.  That solution was made more generic to handle a couple other use cases.  Modifying the 'raw key' patch to include support for a generic base address seems like a simple modification and really only leaves apps with 2 types of MR support - BASIC_EX (which replaces BASIC and needs a better name) and SCALABLE.  These modes map back to whether the app needs to exchange data or not.

**Comment by sdvormwa** [comment]
> MRs may require that virtual addresses be back by physical pages at time of registration or not.

An important follow-up on this one is whether the MR is automatically updated when a VA it covers becomes backed by physical pages or if the user needs to initiate the update...

>  I'm VERY hesitant of going down the path of trying to expose every single attribute that every provider may need. That would lead to a completely insane and unusable API.

Okay, what about this.  Have a single additional mode in addition to basic and scalable: FI_MR_PROVIDER.  If a provider supports this mode, its behavior is completely defined by the provider--addressing can be VA or offset based, keys may or may not be exchangeable, etc.  No extra flags or mode bits to describe or request specific behavior.  Yes, this means that it couldn't be used by "generic" apps, but it also means that providers can expose functionality to users who really want to use it and are okay with provider-specific tuning without significant API creep.

**Comment by shefty** [comment]
I removed my 'raw mr' patch from the abi 1.1 series to update/replace it, and was also thinking of a adding a third mode (FI_MR_RAW) that would essentially replace BASIC.  But even that needs some level of definition, but the intent is to cover the case where the app must exchange data.

We already have the provider name exposed, which apps can use to key on for provider specific behavior.  So if we simply leave areas undefined, then those attributes become provider specific.

**Comment by sdvormwa** [comment]
Let me dive into a more concrete example.  The GNI API has two features that together allow the client to create something usefully between FI_MR_BASIC and FI_MR_SCALABLE for my use case.  By using the VMDH functionality (see section 3.7.1.1 of [this document](http://docs.cray.com/books/S-2446-5202/S-2446-5202.pdf) for details), the need to exchange data can be obviated as it is with FI_MR_SCALABLE.  Similarly, the use of the GNI_MEM_RESERVE_REGION flag (see section 3.7.1.3) allows for for memory ranges that aren't backed by physical pages at registration time, again as with FI_MR_SCALABLE.  However, the GNI_MEM_RESERVE_REGION functionality requires that the user manually update parts of the region with the GNI_MEM_UPDATE_REGION flag before those parts can be the target of network operations, and thus this can't be directly used to implement FI_MR_SCALABLE.  For my particular use case, I can pretty easily guarantee that I will call an update function sometime between the creation of the MR and any remote accesses targeting pages that didn't exist at the creation of the MR.

What I would like to see is some way for the GNI provider to directly expose this hardware functionality to me, enabling a useful subset of the FI_MR_SCALABLE functionality without all the baggage that would come with the provider attempting to fully implement FI_MR_SCALABLE in software.  It doesn't sound like your proposal would do that, given

> But even that needs some level of definition, but *the intent is to cover the case where the app must exchange data*.

My intent is just the opposite--to enable the app to not exchange data in situations where the provider can't efficiently provide the full functionality of FI_MR_SCALABLE.

**Comment by sayantansur** [comment]
> However, the GNI_MEM_RESERVE_REGION functionality requires that the user manually update parts of the region with the GNI_MEM_UPDATE_REGION flag before those parts can be the target of network operations, and thus this can't be directly used to implement FI_MR_SCALABLE. For my particular use case, I can pretty easily guarantee that I will call an update function sometime between the creation of the MR and any remote accesses targeting pages that didn't exist at the creation of the MR.

This reminds me of the way MPI Dynamic windows work. Need to understand GNI better, but if it is indeed a direct 1:1 map with MPI, then an additional call to "make real pages available" for FI_MR_SCALABLE sounds reasonable. We should also inspect SHMEM and see if it can provide this additional call.

**Comment by shefty** [comment]
This issue is mixing separate requests.  For the original issue, a data exchange between peers is required.  What's needed is the most generic (but usable!) way for that to be defined such that it covers as many of the different attributes listed above as possible.

**Comment by sdvormwa** [comment]
> This issue is mixing separate requests.  For the original issue, *a data exchange between peers is required*.

First, why are you so focused on an *MR exchange* between peers?  Is there any app-driven requirement for this (outside legacy applications that only do it because the api they were using required it...)?  You can't argue that the address/offset is the app-driven reason because that is potentially needed with FI_MR_SCALABLE (eg, to communicate which offsets are valid), and potentially not needed with FI_MR_BASIC (eg, if you know the peer always creates the MR at a fixed base address, so you just need the key).  What possible reason could the app have that *requires* a key exchange other than the provider requires it?

Second, the "original issue" was breaking the association of addressing mode and key type to enable hardware acceleration:

> What needs to be added are the other two combinations of key type and addressing type. This will enable hardware acceleration on certain providers, such as bgq.

I argued that there were more implicit attributes built into the existing modes that could prevent hardware acceleration on certain providers, giving an explicit example with the gni-provider, making the case for a more generic approach that doesn't just cover addressing.

> What's needed is the most generic (but usable!) way for that to be defined such that it covers as many of the different attributes listed above as possible.

Data exchange is one of the attributes you listed above:

> Key values may be given by either the provider or application.

**Comment by sdvormwa** [comment]
> This reminds me of the way MPI Dynamic windows work. Need to understand GNI better, but if it is indeed a direct 1:1 map with MPI, then an additional call to "make real pages available" for FI_MR_SCALABLE sounds reasonable. We should also inspect SHMEM and see if it can provide this additional call.

I'm not very familiar with MPI Dynamic windows, but given how practical the MPI committee is, my expectation is they noticed that it is really hard for discrete network hardware to automatically update memory regions in response to page table updates since they can't use the processor's page table directly (unless the network vendor controls the processor as well...).  Network vendors could in theory handle this by intercepting page table updates in the OS and updating the region at that point with their OS drivers, but that potentially adds a lot of work to a very hot path in the OS for what is likely to be a rare scenario.  An additional call to "make real pages available" as you put it nicely solves the problem without interfering with too many other things by relying on the user to decide when the expense of the update is justified.

**Comment by shefty** [comment]
> First, why are you so focused on an MR exchange between peers?

Because there are literally millions of adapters in the marketplace that require this, and all of them are OFA members.  That's why BASIC exists at all.

**Comment by mblockso** [comment]
I agree with @sdvormwa in that requirements for this aspect of OFI should be more provider-driven than application-driven. 

Why would any application choose FI_MR_SCALABLE when both are "supported" by a provider? FI_MR_BASIC is, um, *not* scalable at all on large systems. A single memory region exchange for a full size BGQ job (Mira) would consume 200MB on each node (assuming shared memory) - and consider that each process in this full configuration gets < 256MB already!

The *only reason* to choose a memory region mode other than FI_MR_SCALABLE is to enable hardware acceleration at the provider level. We need to start thinking about solving this problem via "provider-up" requirements, not "application-down" requirements.

**Comment by shefty** [comment]
I believe we can come up with more abstract solutions that can cover a broader range of implementations.  The linux kernel went down the path of exposing provider specific registration primitives to the apps.  The result was that apps implemented 5 different ways of handling registration.  Keep in mind that the linux kernel _only_ has verbs devices!  The fix for this was to completely re-work the memory registration interfaces, which was possible only because the kernel doesn't need to maintain backward compatibility.

**Comment by shefty** [comment]
Cray - allocates page table entries, then app re-freshes which pages are in the table.

**Comment by shefty** [comment]
Possible solution - just return UNSPEC back for provider specific, or return PROVIDER_SPECIFIC

**Comment by shefty** [comment]
I'm still working on defining this, but I think we may need to go with something close to what Mike proposed early in the thread and convert mr_mode into equivalent 'mode' bits.
