### ISSUE TITLE
offload collectives: need a send atomic function

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2557]
As discussed in previous OFIWG meetings:

It is very convenient to implement offload MPI collectives using the tag-matching API. In the MPI reduction collective, there is a need to perform an accumulate operation on the remote side. Some algorithms may want to support multiple senders that are atomically accumulating at the target.

A send_atomic function w/ tag matching would be very useful. I didn't explore if this would be useful for the non-tag matching case, but it would be nice to have symmetry though.

**Comment by shefty** [comment]
A straightforward solution for this is to define an FI_TAGGED flag to all atomic operations.  When set, the 'key' parameter is treated as a 'tag' parameter, with the atomic operation targeting a tagged receive buffer, rather than an RMA buffer.  This potentially allows all atomic operations to target tagged messages without API changes.

In order to use this approach, I would add a new atomic valid call that includes a flags argument.

**Comment by sayantansur** [comment]
Seems reasonable to me.
