### ISSUE TITLE
Providers need to handle new domain caps/mode fields

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2626]
From 0404fdb3f40a85caef2242a074d6d79a3c0e9dcd, 49ff5ec5999c6e09c3dd8e201a8e239215d3bc11, 27302412ef2a2c9f8eb85b20ce34269f553f2c4f, c40bc47928b464ebd2f1cd00f72ad90a0df47da5.  Values need to be set/checked as needed.

- [ ] bgq
- [x] gni
- [ ] mlx
- [x] psm
- [x] psm2
- [ ] rxd
- [ ] rxm
- [ ] sockets
- [ ] udp
- [ ] usnic
- [x] verbs

**Comment by mblockso** [comment]
@pkcoff

**Comment by bturrubiates** [comment]
@shefty 

I was looking through the docs today and it looks like some of the new caps (`FI_SHARED_AV`, `FI_LOCAL_COMM`, and `FI_REMOTE_COMM`) seem to apply at both the top level caps and also domain level caps. 

Am I interpreting the man pages correctly? If so, why allow these at the top level caps? This seems to make it more complicated because the provider would need to check for the capability in two places, and what happens when the caps conflict (`FI_LOCAL_COMM` given to top level, `FI_REMOTE_COMM` given to domain level)? I'm assuming the  domain caps would have priority in that case.

**Comment by shefty** [comment]
I went back and forth on this.  But the current definition for domain caps is consistent with the way rx/tx caps are defined.  It's not too late to change this definition, however.
