### ISSUE TITLE
Need at least one provider to support new multicast interfaces

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2627]
The more the merrier! 979537dacb8fd7ba489551896745eef360026d20.  At least the UDP provider should be updated to verify the interfaces.

- [ ] bgq
- [ ] gni
- [x] mlx
- [x] psm
- [x] psm2
- [x] rxd
- [x] rxm
- [x] sockets
- [ ] udp
- [ ] usnic
- [x] verbs

**Comment by mblockso** [comment]
@pkcoff

**Comment by medawsonjr** [comment]
All,

My apologies for being late to the party here. I'm a tech guy from the HFT space, and am keenly interested in UDP multicast support in libfabric (particularly over OmniPath). Am I to conclude that libfabric now supports UDP multicast since this issue was closed just under a month ago?

Thanks in advance for your timely response.

**Comment by shefty** [comment]
My timely response was delayed because of vacation...  The UDP provider has support coded for multicast, but that support has not been validated.  The OPA and verbs providers do not yet support multicast.  The primary goal of this issue was to verify that the API changes were sufficient to support multicast.

Knowing that there's a customer request for this feature is useful in helping to prioritize this work.  Can I ask you to open a new issue to add multicast support to the OPA and/or verbs providers?
