### ISSUE TITLE
Question about RM behavior

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#2643]
In reading the "Resource Management" section of https://ofiwg.github.io/libfabric/v1.4.0/man/fi_domain.3.html, I have some questions:

* "Receive overrun" is not defined.  Later in the page, it says "Unmatched receives and receive overruns deal with the processing of messages that consume a receive buffers.", and it goes on to define "unmatched receives."  But it does not define "receive overrun."
    * I assume a receive overrun is when you receive a message of length X into a buffer of size Y, and X>Y.  Is that correct?
* In the "Unrel EP-RM Disabled" and "Rel EP-RM Disabled" columns, several entries say "error".  Does this mean that libfabric is supposed to catch this error and return a non-FI_EAGAIN error?  Or does it really mean that libfabric's behavior is undefined in these scenarios?
    * This is a little pedantic, but some of the items in the columns are clearly what libfabric *does* (e.g., it returns EAGAIN).  So does "error" refer to what libfabric *does* (i.e., libfabric returns some non-EAGAIN error)?  Or does it conceptually refer to the fact that this case *is* an error (and the behavior is undefined)?
* There are 10 cases where the result is "X or Y" (e.g., "buffered or drop").  This is basically saying "something is going to happen, but I'm not going to tell you what."  It doesn't allow the app developer to plan, because they basically have to handle both cases.
    * My $0.02: for one example, it says "buffered or drop".  I think that these two options are describing the implementation -- which we don't want to do.  You want to describe what happens from the API's perspective.  For "buffered or drop", I think that really means "the sent message will either never be received or will eventually be received" (which is also why I don't think the "X or Y" cases are useful).  *How* it's never or eventually received isn't important.

**Comment by shefty** [comment]
Receive overrun should be clarified as 'receive buffer overrun'.

The error entries are intentionally vague to give the provider more leeway in the implementation.  It is an error and the behavior is undefined.  The provider _may_ catch such errors, in particular EAGAIN to avoid overrunning the tx/rx queues.  But since the app has disabled RM, it may not want the overhead of these checks, so the provider is okay disabling them.  On the CQ side, the provider may detect an error and tear down the connection, which I think is a likely implementation, but not guaranteed.

We should probably separate 'error' in the case where RM is disabled, meaning that the app is assuming full responsibility, versus the RM enabled case, in which case I would expect the app to see an actual error event.  So the two error cases in the bottom right of the table should be 'error reported' or something similar (that can fit in the table).

In the cases of X or Y, I think we can remove 'buffered' from any of the choices.  I don't think provider buffering changes anything about how the app needs to respond.  Either they get the message, or it is dropped, the latter of which an app must handle when dealing with an unreliable transport.

We can drop EAGAIN where it appears as an option as well (Rx CQ).  I don't think that option affects the app either.

Truncate is harder to deal with, as that affects the implementation, and I'm aware of providers that do both (truncate or throw an error).

We should re-work the table so that it describes what the application will see better, where we can.  We can add descriptive text beneath the table as needed.

**Comment by shefty** [comment]
FYI - I'm working on an update to this.  Hope to have it shortly.

**Comment by jsquyres** [comment]
Thanks @shefty
