### ISSUE TITLE
fi_cntr_wait return code when error

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2798]
The current text in the man pages is ambiguous as to what error code is returned from fi_cntr_wait() when there is an error. A clarification will be useful.

> This call may be used to wait until the counter reaches the specified threshold, or until an error or timeout occurs. Upon successful return from this call, the counter will be greater than or equal to the input threshold value.
> 
> If an operation associated with the counter encounters an error, it will increment the error value associated with the counter. Any change in a counter’s error value will unblock any thread inside fi_cntr_wait.

**Comment by jshimek** [comment]
Based on my interpretation of the man page I recommend using FI_EAVAIL when there is an error available, and FI_ETIMEDOUT if it just timed out. That being said the man page is probably in need of some clarification with regards to the return codes to be used. @shefty

**Comment by shefty** [comment]
I agree that ETIMEDOUT makes sense.  But forcing an EAVAIL error code implies a particular implementation.  If EAVAIL must be returned, then wait cannot simply return because the wait object has been signaled.  It now needs to see if an error occurred, but that check itself may be racy, such that the EAVAIL return code itself cannot be trusted by the app.

**Comment by jshimek** [comment]
@shefty What do you mean by the check may be racy? fi_cntr_wait returns in the case of a timeout or error, but makes no mention of the return codes to be used. EVAIL seems to fit and ETIMEDOUT seems to fit. 
Based on my reading of the man page and of several providers getting an error on fi_cntr_wait means you need to check fi_cntr_readerr, unless you mean fi_cntr_waits' error return is for more than just informing you that the cntr_err has been set. 

Looking at the current providers:
BGQ will never exit fi_cntr_wait because of an error, so if there is one and someone passed -1 for a timeout it will spin forever
PSMX will never exit fi_cntr_wait because of an error, so if there is one and someone passed -1 for a timeout it will spin forever
PSMX2 will never exit fi_cntr_wait because of an error, so if there is one and someone passed -1 for a timeout it will spin forever.
Sockets is slightly better it checks on entry if there is an cntr_error, but doesn't seem to check if there's an error after that, so if a -1 timeout is passed it could spin forever. I only looked at the socket_cntr_wait code so if the cntr_err is handled in a different function it might work correctly.
GNI in 1.5 will exit fi_cntr_wait when a cntr_err exists.

If I am misunderstanding how the cntr functions are supposed to work could you clarify it for me?

**Comment by shefty** [comment]
In order to report EAVAIL, the provider needs to compare an initial value against some current value.  The problem is what initial value is used.

If it's read by the provider before blocking, then there's a race where the error counter can change between the app calling wait and the provider reading it.  This can lead to the provider returning from wait without notifying the app that the error counter has changed relative to their reading of it, which makes the return value misleading.

If the value is from the last time fi_cntr_readerr(), then readerr() has changed from a simple counter read operation to a read/write.  There was a discussion on this at some point.  The conclusion was to leave the interpretation of the counter values up to the app.  This means that fi_cntr_wait() can return 0 even if the counter was not recently updated, but only updated since the last time wait was called.  The criteria is that repeated calls to fi_cntr_wait() should not result in busy spinning.  The thread should eventually block (assuming that the provider is intelligent enough not to spin wait).

**Comment by jshimek** [comment]
@shefty So I think I now understand, so fi_cntr_wait needs to return 0 if either you hit the threshold or an err_cnt is greater than the value when it entered. So the user needs to check fi_read_cntr and fi_read_cntrerr on a successful return from fi_cntr_wait, since a 0 just means either one of the cntr's incremented. 

So this works in the naive case if the threshold is not set, but when there is a threshold set the cnterr needs to be read every time cntr_wait unblocks from a wait_object notification to check if its timed_out or if the threshold has been met and return then. With a threshold value we need to store a cnt_err value such that we can support waiting until the threshold is passed or the error counter is incremented. Or does the wait object that fi_cntr_wait depends on need to be able to differentiate between a signal of the counter incrementing and  a signal of the error counter incrementing?

At minimum could we put a clarification into the man page that a return of 0 is for either the regular counter and the error counter? In reading the man I was confused by this probably because of the different uses of the word error.

Could this be a topic of discussion at the working group?

**Comment by shefty** [comment]
We can bring this up for discussion.  The way I believe current implementations work is something like this:

Inside fi_cntr_wait - save threshold value, block on wait object

In progress areas - When incrementing counter, if there is a waiter and threshold has been met, signal the wait object.  If incrementing the error count, if there is a waiter, signal the wait object.

Wait objects are a little tricky, because we don't want to ignore all signals and NOT return control back to the app.  (That's like three negatives in one sentence.)

**Comment by shefty** [comment]
Return code does not indicate which value changed, if any.
Only new counter errors should unblock a waiting thread -- rather than unblocking if the error count is > 0.
*New* being an error that occurs while waiting.
A wait object may already be signaled when starting a wait call.   E.g. an error may have occurred prior to wait being called.
Wait should be thread safe.  Different thresholds may be specified.
Wait calls should not 'spin' back to the app.
