### ISSUE TITLE
Filtering via FI_PROVIDER environment variable does not filter out utility providers

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2904]
```sh
$ FI_PROVIDER=sockets ./fi_info | grep provider | uniq
provider: sockets
provider: sockets;ofi-rxm
```

I can't seem to find any specific documentation around how this should be handled with regard to the utility providers. Is this the expected behavior? 

I think the layering is still awkward. If the provider were explicitly requesting endpoint support via a utility provider, then I think it makes sense for the utility provider to respond as if it were the base provider. In this model, where the utility providers 'discover' their base layers, I think only the main requested provider should respond. 

@shefty @jsquyres

**Comment by shefty** [comment]
> $ FI_PROVIDER=sockets ./fi_info | grep provider | uniq
> provider: sockets
> provider: sockets;ofi-rxm
> 
> I can't seem to find any specific documentation around how this should
> be handled with regard to the utility providers. Is this the expected
> behavior?

This is the expected behavior.  The utility providers are expected to be transparent to the app, which includes not being filtered.

> I think the layering is still awkward. If the provider were explicitly
> requesting endpoint support via a utility provider, then I think it
> makes sense for the utility provider to respond as if it were the base
> provider. In this model, where the utility providers 'discover' their
> base layers, I think only the main requested provider should respond.

It's actually horribly convenient to be able to test the utility providers over sockets.  The utility providers just report last in the getinfo list, so the core providers will take precedence.

**Comment by jsquyres** [comment]
I have to admit that this still warps my brain.

Let me ask a clarifying question: if a user wants to disable a utility provider, how does he/she do it?

**Comment by shefty** [comment]
There is no known way to disable a utility provider.  They are always there.  Always watching.  Always ready to leap out.

We would need a new variable or flag or some other way to disable them.

**Comment by jsquyres** [comment]
![image](https://cloud.githubusercontent.com/assets/617316/25147149/843ee416-2444-11e7-84d8-ddff6ac81003.png)

I'm sorry, that just had to be done!

**Comment by shefty** [comment]
That is why I do open source

**Comment by jsquyres** [comment]
I'm still trying to wrap my head around this.

I guess my question is: why are the utility providers visible to the user at all?  They seem like an internal implementation detail of the providers.

I.e., if a user selects the `foo` provider, what do they care how the `foo` provider chooses to implement the functionality (i.e., via utility/shared code inside libfabric or with 100% of their own code)?  The user should just see that `foo` is used.  How `foo` works internally is irrelevant (from the user's point of view).

(sidenote: I agree to the prior comment: it might be useful to add a secondary control to selectively enable/disable utility providers -- if for no other reason than developers may want to force the use of a utility provider or not)

**Comment by bturrubiates** [comment]
> I guess my question is: why are the utility providers visible to the user at all? They seem like an internal implementation detail of the providers.
> 
> I.e., if a user selects the foo provider, what do they care how the foo provider chooses to implement the functionality (i.e., via utility/shared code inside libfabric or with 100% of their own code)? The user should just see that foo is used. How foo works internally is irrelevant (from the user's point of view).

I think the only way to make it 100% transparent would be for a provider to explicitly provide support via a layered utility provider. Then it would look like usNIC to the application, the application wouldn't be aware of the design detail of a layered provider, and when someone says "The streaming endpoint doesn't work" we won't say "What streaming endpoint? We don't support that.".

**Comment by shefty** [comment]
From the viewpoint of the application, the only way it knows a utility provider is in use is that the provider name is adjusted to append the utility.  This is necessary for debugging.  It also allows an app to request a specific utility provider or utility + core combo -- which is needed for testing.

The name change is required in order to get to the correct provider when the user later calls fi_fabric() to open a specific fabric.  Having only the core provider name doesn't allow us to select the correct provider.

**Comment by jsquyres** [comment]
I guess I'm struggling with the fact that there has been -- and continues to be -- confusion about the utility providers, and what is their expected vs. actual role.

It would seem to be quite a bit simpler -- especially from an "explaining it to the user" perspective -- to completely hide them as an implementation detail.  If additional controls are needed to force / prevent their use from a testing perspective, no problem.  But that also should be an implementation detail, perhaps as a run-time parameter on a per-provider basis (or perhaps as a run-time parameter on the utility providers themselves, if you don't want to further complicate the individual providers).

**Comment by shefty** [comment]
The complexity and confusion has arisen as a direct result of trying to make them hidden, when they are very much real providers.  They plug into the framework as a provider, and can be an external library just like any other provider.  We can't even prevent a third party from creating a 'utility' provider, and having it act completely like a core provider.

After calling fi_getinfo(), an app calls fi_fabric().  That call only contains the fi_fabric_attr structure.  From that structure, we need to route the call to the correct location.  That is why the provider name carries the utility provider name.  We can break the ABI and create a new fi_fabric() interface that allows us to route the call to the utility provider, or we maintain compatibility.  Breaking the ABI means that an app must update to the new API in order to actually use any utility provider.  That doesn't exactly keep them hidden either.  Plus _something_ in the fi_info+ data must indicate that the call needs to route to the utility provider, which again prevents them from being hidden.

IMO, the confusion has been self inflicted as a result of attempting to implement the impossible.
