### ISSUE TITLE
UDP and UDP;ofi-rxd  provider selection

### ISSUE THREAD

**Issue by bcernohous** [ofiwg/libfabric#2968]
I was experimenting with UDP and UDP;ofi-rxd with a recent master level build and noticed some oddities.

If I specify version 1.4 or 1.5 on fi_getinfo I do not get the UDP provider.  I need 1.3 or lower to get any UDP provider with or without a utility provider.

Unlike sockets (where experiments have shown that the domain name may be ipogif0, rsip, or lo), the UDP domain name is always udp.  And the first UDP provider returned by fi_getinfo is the loopback address, which doesn't seem like the best choice.  I'm having to parse the ipv4/ipv6 sockets address rather than looking at a libfabric domain name or some other attribute to get what I want.

**Comment by shefty** [comment]
The version should not matter, so something is off there.  I'll investigate.

The udp domain is system wide, rather than tied to a specific device.  An EP may be restricted to a source address, but the domain can work across all NICs in the system.  However, we can discuss whether having the udp provider behave more like the sockets provider would be more useful for apps.

I agree that returning the loopback address first isn't ideal.  That can be adjusted.

Btw, the ofi-rxd provider should not be enabled.  It has a serious architectural issue and is undergoing a rewrite of its progress engine.

**Comment by bcernohous** [comment]
I just noticed that even bin/fi_info seems to have an issue, maybe the 1.3 version problem?  fi_info -l shows UDP but just fi_info does not.

$ bin/fi_info  -l
gni:
    version: 1.0
UDP:
    version: 1.0
sockets:
    version: 2.0
ofi-rxm:
    version: 1.0
ofi-rxd:
    version: 1.0

$ bin/fi_info  | grep provider
provider: gni
provider: gni
provider: gni
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets;ofi-rxm
provider: sockets;ofi-rxm
provider: sockets;ofi-rxm
provider: gni;ofi-rxd
provider: sockets;ofi-rxd
provider: sockets;ofi-rxd
provider: sockets;ofi-rxd

**Comment by shefty** [comment]
I ran a quick test on 1.4.2rc1, and udp showed up fine.   1.5+ (tip of master) showed with fi_info -l, but not fi_info -p udp.  Not sure why

**Comment by shefty** [comment]
old issue
