### ISSUE TITLE
Is IBV_EXP_DEVICE_ATTR_ODP necessary in the verbs provider?

### ISSUE THREAD

**Issue by agrippa** [ofiwg/libfabric#3039]
When building on an older cluster at Rice U:

https://docs.rice.edu/confluence/display/CD/DAVinCI+Overview

libfabric correctly finds that verbs is supported, but when building we hit the following error message:

prov/verbs/src/ep_rdm/verbs_ep_rdm.c: In function ‘fi_ibv_rdm_open_ep’:
prov/verbs/src/ep_rdm/verbs_ep_rdm.c:558:23: error: ‘IBV_EXP_DEVICE_ATTR_ODP’ undeclared (first use in this function)
  exp_attr.comp_mask = IBV_EXP_DEVICE_ATTR_ODP | IBV_EXP_DEVICE_ATTR_EXP_CAP_FLAGS;

It seems like this might be a problem with a way too old verbs installation:

$ rpm –qa | grep ibverb
libibverbs-utils-1.1.7mlnx1-OFED.2.2.125.gbfab13c.x86_64
libibverbs-1.1.7mlnx1-OFED.2.2.125.gbfab13c.x86_64
libibverbs-devel-1.1.7mlnx1-OFED.2.2.125.gbfab13c.x86_64

So the question is, does the verbs provider have a hard dependency on these flags or would it be possible to macro them out in the preprocessor if they aren't supported?

**Comment by shefty** [comment]
@gladkovdmitry17.  I'm not sure if the code depends on this feature (probably does), but it should be possible to work-around this.  ODP is a Mellanox specific feature, so there shouldn't be a dependency on a vendor specific capability.  At the very least, the verbs rdm support should just be disabled, so that msg support is still available (and usable via the rxm provider).

**Comment by evgeny-leksikov** [comment]
ODP improves performance on large messages. I would suggest to fix check in https://github.com/ofiwg/libfabric/blob/master/prov/verbs/configure.m4#L54

**Comment by gladkovdmitry17** [comment]
Yes, as @shefty correctly noted, verbs / RDM has a dependency on the ODP Mellanox OFED specific feature. But during the configuration step the possibility to use that feature will be checked. And if there is a possibility to exploit the ODP feature is `HAVE_VERBS_EXP_H` macro is set. In the other words, there are two branches in verbs depend on whether that feature can be used or not.
@agrippa Could you check an output during configure step, please?
Is there 

> checking infiniband/verbs_exp.h usability... no
> checking infiniband/verbs_exp.h presence... no
> checking for infiniband/verbs_exp.h... no

those lines in the output? If there is "_... yes_" instead of "_... no_" on machine w/o MlnxOFED, it seems our configure step for verbs doesn't work correctly.

**Comment by agrippa** [comment]
Sure, here's what I found in config.log. Looks like it reported all "yes".

configure:17965: checking infiniband/verbs_exp.h usability
configure:17965: gcc -std=gnu99 -c -fvisibility=hidden -O2 -DNDEBUG -Wall -Wundef -Wpointer-arith  conftest.c >&5
configure:17965: $? = 0
configure:17965: result: yes
configure:17965: checking infiniband/verbs_exp.h presence
configure:17965: gcc -std=gnu99 -E  conftest.c
configure:17965: $? = 0
configure:17965: result: yes
configure:17965: checking for infiniband/verbs_exp.h
configure:17965: result: yes
configure:18041: result: looking for library without search path

**Comment by gladkovdmitry17** [comment]
@agrippa  Thanks. Seems checking for infniband/verbs_exp.h is not complete solution to determine whether verbs is able to utilize ODP feature. 
Also checking for `ibv_open_device` is seems excessive, it should be replaced by `ibv_exp_query_device`.

I will extend the configure checks by looking for `ibv_exp_query_device` and `IBV_EXP_DEVICE_ATTR_ODP` in configuration step. Seems, IBV_EXP_DEVICE_ATTR_ODP was added a bit earlier than other content of `verbs_exp.h`. 
MLNX OFED 3.0.2 supports ODP at least. But I'm not sure about OFED 2.2.125 that you are using.

**Comment by gladkovdmitry17** [comment]
@agrippa Could you check PR #3044, please? Seems it works on my system

**Comment by agrippa** [comment]
@gladkovdmitry17 LGTM, tested out a build on our system. Thanks for the quick fix!

**Comment by gladkovdmitry17** [comment]
@agrippa you're welcome.
@shefty Is it possible to include the fix within 1.5 release? Thanks!

**Comment by shefty** [comment]
Yes, this will get pulled into 1.5

**Comment by shefty** [comment]
#3044 was merged.
