### ISSUE TITLE
prov/gni: Sandia Open SHMEM multi-thread all-toall test hangs

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#3423]
Not sure if the SOS ```mt_a2a``` test ever passed with the GNI provider, but it doesn't now.  The test passes when only one thread is used, but consistently hangs in the ```get``` stage of the test when multiple threads are used.

**Comment by hppritcha** [comment]
Some digging shows this has to do with addition of the use of a wait object in SOS.  There seems to be an issue with the implementation of GNI wait objects and the way SOS is using the wait object with multiple threads.  A workaround to avoid the hang is to avoid calling ```fi_cntr_wait``` in SOS.  This can be done by setting the following environment variable:

```
export SHMEM_OFI_RX_POLL_LIMIT=-1
```

I'll update the SOS GNI provider wiki.

@jdinan

**Comment by jdinan** [comment]
@hppritcha The wait object should be disabled when threading is enabled, since threads can wake up other threads from calls to ```shmem_wait``` with a store.  This should be fixed in the v1.4 branch (or will be soon, if it isn't yet).

That env var is new, BTW.  It will appear for the first time in SOS v1.3.4, which should be out within the next month or so.

**Comment by hppritcha** [comment]
Okay with this information,  I'll close this bug.

**Comment by jdinan** [comment]
@hppritcha If you --enable-hard-polling and --enable-completion-polling, it should not be necessary to set ```SHMEM_OFI_RX_POLL_LIMIT```.  Are you setting both of those configury flags?
