### ISSUE TITLE
Is it allowed to cancel operations that don't generate completions?

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#3519]
fi_cancel uses the context to identify the operation to cancel. However, according to fi_endpoint man page (quoted below), a provider that requires FI_CONTEXT mode can't assume the context passed in is valid if the operation has completion suppressed. As the result, the provider may not be able to store necessary information in the context for later fi_cancel call.

> Endpoints allocated with the FI_CONTEXT mode set must typically provide struct fi_context as their per operation context  parameter.   (See  fi_getinfo.3 for  details.)  However, when FI_SELECTIVE_COMPLETION is enabled to suppress completion entries, and an operation is initiated without FI_COMPLETION flag set, then the context parameter is ignored.  An application does not need to pass in a valid struct fi_context into such data transfers.

**Comment by shefty** [comment]
Hmmm... I think we'd have to go with 'no'.  The use of FI_CANCEL only works with operations that are associated with a valid fi_context.  Maybe we can add FI_CANCEL as an operation flag to mark a posted operation as cancelable?  When specified, fi_context must be valid.  This might work, but I think ends up with a messy definition.

**Comment by j-xiong** [comment]
An answer "no" will make the provider implementation simpler :) so I won't complain. We may want to add a note to the fi_cancel man page to make sure the users are aware of the restriction.

**Comment by sayantansur** [comment]
The typical usage of FI_SELECTIVE_COMPLETION allows the user to suppress full completions, and get completions via a counter. In such a situation, the application itself might not have a valid context ptr per op (the entire point of suppressing completions is to remove overhead per operation).

Therefore, I agree that we update the documentation to say that FI_CANCEL only works when the context pointer is not ignored.

As an aside, I think this issue is separate from the FI_CONTEXT mode bit.
