### ISSUE TITLE
Does libfabric support on-demand-paging(ODP)?

### ISSUE THREAD

**Issue by songweijia** [ofiwg/libfabric#3634]
I want to port our application from ibverbs API to libfabric. One feature we need for ibverbs API is [ODP](https://community.mellanox.com/docs/DOC-2898), which allows accessing to the whole virtual address space of application from the RDMA device without pinning physical memory pages in advance (ibv_reg_mr). Does libfabric support ODP now? I tried as follows but no luck.

I had a libfabric test program running well with 'verbs' provider and 'msg' endpoint in the following environment:
linux kernel:4.6.0-040600-generic
linux distribution: ubuntu16.04
libfabric: the latest code in github master branch:
commit 3f24e4a37c2a941ab37fe822403ff7f2bf41eb59
Merge: f7f56e0 a5c431f
Author: Sean Hefty <sean.hefty@intel.com>
Date:   Mon Dec 18 09:45:57 2017 -0800

    Merge pull request #3629 from aingerson/master
    
    prov/tcp: fix resource leak reported by coverity
Verbs driver: MLNX_OFED_LINUX-4.2-1.2.0.0-ubuntu16.04-x86_64
Hardware: Mellanox ConnectX-4 VPI
`$ lspci | grep Mellnaox`
`45:00.0 Infiniband controller: Mellanox Technologies MT27700 Family [ConnectX-4]`
`45:00.1 Ethernet controller: Mellanox Technologies MT27700 Family [ConnectX-4]`

To try ODP, I disabled FI_MR_ALLOCATED for fi_mr_reg as follows.
`ct->hints->domain_attr->mr_mode = FI_MR_LOCAL | FI_MR_VIRT_ADDR | FI_MR_PROV_KEY; `
But fi_getname() failed with error 61 "No data available."

Here is the hint we use:
    caps: [ FI_MSG ]                                                                                                                                                                              [140/1741]
    mode: [ FI_CONTEXT ]
    addr_format: FI_FORMAT_UNSPEC
    src_addrlen: 0
    dest_addrlen: 0
    src_addr: (null)
    dest_addr: (null)
    handle: (null)
    fi_tx_attr:
        caps: [  ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [  ]
        comp_order: [  ]
        inject_size: 0
        size: 0
        iov_limit: 0
        rma_iov_limit: 0
    fi_rx_attr:
        caps: [  ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [  ]
        comp_order: [  ]
        total_buffered_recv: 0
        size: 0
        iov_limit: 0
    fi_ep_attr:
        type: FI_EP_MSG
        protocol: FI_PROTO_UNSPEC
        protocol_version: 0
        max_msg_size: 0
        msg_prefix_size: 0
        max_order_raw_size: 0
        max_order_war_size: 0
        max_order_waw_size: 0
        mem_tag_format: 0x0000000000000000
        tx_ctx_cnt: 0
        rx_ctx_cnt: 0
        auth_key_size: 0
    fi_domain_attr:
        domain: 0x0
        name: mlx5_0
        threading: FI_THREAD_UNSPEC
        control_progress: FI_PROGRESS_UNSPEC
        data_progress: FI_PROGRESS_UNSPEC
        resource_mgmt: FI_RM_UNSPEC
        av_type: FI_AV_UNSPEC
        mr_mode: [ FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_PROV_KEY ]
        mr_key_size: 0
        cq_data_size: 0
        cq_cnt: 0
        ep_cnt: 0
        tx_ctx_cnt: 0
        rx_ctx_cnt: 0
        max_ep_tx_ctx: 0
        max_ep_rx_ctx: 0
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 0
        cntr_cnt: 0
        mr_iov_limit: 0
    caps: [  ]
    mode: [ FI_CONTEXT, FI_MSG_PREFIX, FI_ASYNC_IOV, FI_RX_CQ_DATA, FI_LOCAL_MR, FI_NOTIFY_FLAGS_ONLY, FI_RESTRICTED_COMP, FI_CONTEXT2 ]
        auth_key_size: 0
        max_err_data: 0
        mr_cnt: 0
    fi_fabric_attr:
        name: (null)
        prov_name: verbs
        prov_version: 0.0
        api_version: 0.0

The following is the debug information we saw with FI_LOG_LEVEL=info.
libfabric:verbs:core:ofi_check_domain_attr():512<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_mr_mode():496<info> Invalid memory registration mode
libfabric:verbs:core:ofi_check_mr_mode():497<info> Expected: FI_MR_LOCAL, FI_MR_ALLOCATED
libfabric:verbs:core:ofi_check_mr_mode():497<info> Given: FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_PROV_KEY
libfabric:verbs:core:ofi_check_domain_attr():511<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():512<info> Supported: mlx5_0-rdm
libfabric:verbs:core:ofi_check_domain_attr():512<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():511<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():512<info> Supported: mlx5_0-dgram
libfabric:verbs:core:ofi_check_domain_attr():512<info> Requested: mlx5_0
libfabric:core:core:fi_getinfo_():739<warn> fi_getinfo: provider verbs returned -61 (No data available)
libfabric:ofi_rxm:core:ofi_check_ep_attr():618<info> Unsupported endpoint type
libfabric:ofi_rxm:core:ofi_check_ep_attr():619<info> Supported: FI_EP_RDM
libfabric:ofi_rxm:core:ofi_check_ep_attr():619<info> Requested: FI_EP_MSG
libfabric:core:core:fi_getinfo_():739<warn> fi_getinfo: provider ofi_rxm returned -61 (No data available)
Fail to fi_getinfo() with error [-61], No data available.

**Comment by gladkovdmitry17** [comment]
@songweijia  Currently the verbs provider with FI_EP_RDM endpoint type supports Explicit ODP feature for large message transfer (Rendezvous protocol) of messages >= `FI_VERBS_RDM_BUFFER_SIZE=<positive integer value>` run-time parameter value. We are using Explicit ODP + Relaxed access (lazy de-registration of MRs on IB verbs library level), but it corrupts memory in some cases. The feature is disabled by default and can be turned on by setting `FI_VERBS_USE_ODP=1` knob.

As I mentioned above the feature is supported only by the verbs/RDM. But we're implementing the possbility to use Explicit ODP on verbs/MSG level. Currently this is in progress development of PR #3602.

If you would like to use Implicit ODP feature (if I correctly got it from your description), unfortunately, it's impossible for now. We have done some research on whether this feature gives some performance advantages. But we don't see any benefits.

We decided to implement software-based MR caching at the OFI level (it allows us to get a saturated bandwidth for messages > 2 Mbytes) for verbs/MSG, verbs/RDM and our new RxM/verbs/MSG implementation of RDM support (this is our target provider in the near future to support all new features).

**Comment by songweijia** [comment]
@gladkovdmitry17 Thank you very much for the reply. It's good to know that explicit ODP on verbs/MSG is under development! And yes, ideally, I want to use implicit ODP. I agree that the implicit ODP does not improve throughput or latency (It actually introduces some overhead because you have to anyhow have the physical memory pages prepared before data transfer). However, implicit ODP allows RDMA to access memory whose address is unknown at the time of registration. For the performance overhead, the application can actually prefetch the pages as soon as it knows where the RDMA goes in memory space.

It would be nice if implicit ODP could be available through libfabric in the future. On the other side, I will discuss with our team on the possibilities of workaround with explicit ODP.

**Comment by KenBirman** [comment]
Just to add to what @songweijia said, a benefit of implicit ODP is that if you have an application running at a fairly "high level" (like a program doing some sort of machine learning task), it probably will talk to RDMA through a library layer that has to handle marshalling and similar tasks.  With implicit ODP, an RPC or some other form of message send can completely avoid marshalling and copying -- you can just use scatter-gather and let the RDMA layer or the software emulator walk the list of memory regions.  Lacking implicit ODP, it seems to us that you would need to pre-register the full memory region, and because malloc can grow the region, it becomes a game of trying to figure out which pages are already registered and which ones are "new" and hence need to be registered.  I can see how to do this (you would need some form of high-water mark, and then if a memory area was above it, you would register all the pages from the old one to the new one).  But it seems clumsy, and this would be right on the critical path.  

With implicit ODP, you just do the high level operation, and it causes a verb to be constructed using scatter-gather, and we don't have to worry about whether those particular memory areas are registered.

And you do gain performance.  The big win is that you don't have to check each address to see if it is in registered memory.  But as a practical matter, there is a second win: right now, without knowing how memory allocation works, you would be forced to do memcpy to copy from wherever the application has its data into pages that have been properly registered, and that memcpy operation would be slower than the hardware RDMA operation itself.

Even with implicit ODP, this is clearly not going to work for aggressively managed memory -- if pointers can swizel under your feet, copying would be the only choice.  But from C or C++, implicit ODP lets us use scatter gather and completely avoid the copying.  

On the receive side, copying is avoided by passing in pointers or references right into the received memory area where the message landed.  So the issue doesn't arise on the receivers, only on the sender...

**Comment by gladkovdmitry17** [comment]
@songweijia Thanks a lot for providing details of your usage.

> It would be nice if implicit ODP could be available through libfabric in the future.

Yes, I'm going to put some efforts and implement ODP asap for you. It shouldn't take longer, but can help you gain performance.

> On the other side, I will discuss with our team on the possibilities of workaround with explicit ODP.

Your scenarios are OK for us. I'm going to take this activity when my current tasks will be done.

 @KenBirman Many thanks for great explanation of possible case that can be applied with the Implicit ODP. It sounds enough to take it into account and implement a support asap.

**Comment by songweijia** [comment]
@gladkovdmitry17 That's very exciting to hear! Thank you very much for this support! We can now confidently continue to move on to libfabric!

**Comment by KenBirman** [comment]
Our plan is to port [Derecho ](http://www.cs.cornell.edu/ken)to run on libFabrics rather than directly on Mellanox RDMA.  The platform is entirely [open source](https://GitHub.com/Derecho-Project), but to use it, people have needed to have the hardware, and we get complaints about that right now.  Once we are on libFabrics we should have way better portability and this specific feature will also improve our performance.

**Comment by gladkovdmitry17** [comment]
@songweijia @KenBirman Thanks!
Please, keep this issue open. It's necessary to follow up this activity

**Comment by byronyi** [comment]
> Just to add to what @songweijia said, a benefit of implicit ODP is that if you have an application running at a fairly "high level" (like a program doing some sort of machine learning task), it probably will talk to RDMA through a library layer that has to handle marshalling and similar tasks. With implicit ODP, an RPC or some other form of message send can completely avoid marshalling and copying -- you can just use scatter-gather and let the RDMA layer or the software emulator walk the list of memory regions. Lacking implicit ODP, it seems to us that you would need to pre-register the full memory region, and because malloc can grow the region, it becomes a game of trying to figure out which pages are already registered and which ones are "new" and hence need to be registered. I can see how to do this (you would need some form of high-water mark, and then if a memory area was above it, you would register all the pages from the old one to the new one). But it seems clumsy, and this would be right on the critical path.
> 
> With implicit ODP, you just do the high level operation, and it causes a verb to be constructed using scatter-gather, and we don't have to worry about whether those particular memory areas are registered.
> 
> And you do gain performance. The big win is that you don't have to check each address to see if it is in registered memory. But as a practical matter, there is a second win: right now, without knowing how memory allocation works, you would be forced to do memcpy to copy from wherever the application has its data into pages that have been properly registered, and that memcpy operation would be slower than the hardware RDMA operation itself.
> 
> Even with implicit ODP, this is clearly not going to work for aggressively managed memory -- if pointers can swizel under your feet, copying would be the only choice. But from C or C++, implicit ODP lets us use scatter gather and completely avoid the copying.
> 
> On the receive side, copying is avoided by passing in pointers or references right into the received memory area where the message landed. So the issue doesn't arise on the receivers, only on the sender...

@KenBirman This idea looks very similar to my work on TensorFlow GPU Direct RDMA (https://github.com/tensorflow/tensorflow/pull/11392). May I know if there is any advances or work you guys are pushing? I am glad to hear that out.

**Comment by songweijia** [comment]
So far we didn't use the ODP features yet (although we still plan to). According to merged PR #3602 , Explicit ODP should already work with libfabric. I don't think Implicit ODP is supported in libfabric so far.

My two cents on the implicit ODP for libfabric: maybe using the `flag` argument in `fi_mr_reg()` would work. `fi_mr_reg()` should be able to complain if the hardware does not support this feature. I believe @dmitrygladkov had deliberated over this feature much more than I do.

**Comment by KenBirman** [comment]
Matt was telling me about an idea for using a slab allocator to solve this in an easy way with no changes to LibFabrics.  

Basically you allocate and register a slab of bytes and then get malloc to allocate space for the objects in the slab.  Marshaling becomes easy because the bytes are right there, and the data is pinned at a known place so RDMA works.  Then the receiver can recreate the objects easily.  

There is even a form of pointer (a “fancy” pointer) that has a base plus an offset.  If your objects use these, and are allocated in the slab, then relocating the object is easy.  You just maintain a variable giving the base address of the slab...

**Comment by KenBirman** [comment]
By the way. The GPU RDMA work sounds very cool.  I’ll look at that... as a caution, such techniques can be hard to use.  Tight timing, fragile control mechanisms and lack of standards for hardware fencing (sequential memory consistency) combine to make things super hard to deploy.

**Comment by byronyi** [comment]
@KenBirman Indeed, we have been working on that for a while, and we do found several peculiar issues. For example, NIC reading from the GPU memory seems to be less performant than writing to it. Reading from GPU memory sometimes suffers from memory corruption, especially when using in conjunction of the CUDA stream API. 

By the way, we are establishing a SIG in TensorFlow focusing on high performance networking extensions, and we will kick it off in the coming weeks. Currently we have different contributors from the users and networking vendors, but not so many researchers from academia. I could re-ping you when we have a formal mailing list, if you are interested.

**Comment by KenBirman** [comment]
Sure, although honestly we know much more about Azure functions and AWS Lambdas right now than about tensor flow.  Obviously there is a superficial sense in which all are similar. But the ecosystems are very different.  Tensor Flow seems like the winner for managing attached GPU or TPU clusters so we definitely agree with your focus.  But we are stretched a bit thin at Cornell and in some ways that limits what we can actually do.  I’m not fond of doing halfway projects that overlook key details...  now, hypothetically, if people from the Tensor Flow side wanted to participate that could change the situation quickly

**Comment by byronyi** [comment]
It would make me surprised if Azure functions and AWS Lambdas have RDMA support though. But if they do, it would be great, especially for multi-agent reinforcement learning system such as Ray by [RISELab@Berkeley](https://rise.cs.berkeley.edu/projects/ray/). They have just published in OSDI'18 and the project seems to align with the style of AWS Lambda, i.e. distributed real-time stateless computation.

**Comment by KenBirman** [comment]
Agreed,  they would not have direct RDMA function.  I think of these as PaaS event handler technologies that would see an event, like meta data from a recently acquired video, and then might want to trigger some form of secondary processing like downloading to GPU and extracting some form of information because the video looks interesting.  

Then you would want the RDMA to run (out of band) directly to your video analytic engine on the GPU or TPU cluster.

So the event triggers s function that decided to initiate a cascade of actions, but those big data actions actually occur on other data paths and on other compute elements

**Comment by shefty** [comment]
This issue is 3 years old. The verbs provider does support ODP, but must be enabled through an environment variable.
