### ISSUE TITLE
OFIWG Bot not working?

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#3813]
The last time  nroff-generated man pages got updated was on Jan 8. There have been several man page updates since then.

**Comment by j-xiong** [comment]
@shefty @jsquyres

**Comment by jsquyres** [comment]
Yoinks.  I'll have a look.

**Comment by jsquyres** [comment]
Mmm... I see the problem: the required DCO check is failing when the ofiwg bot is pushing to github.com.  Meaning: pushing automated changes like this now requires a PR (i.e., it's not sufficient to just have the bot sign off its commits, it must also go through a PR so that the DCO status check can be completed successfully).

The obvious answer is to disable DCO as a required check on master.  But that seems lame; the required check is actually a useful error check.

I just ran everything manually to let the most recent man page updates through; let me think about this a little to see if there's a way to fix this without disabling the "DCO check is required" functionality.

**Comment by shefty** [comment]
I push directly to github master for the final release commit.   That works okay.

**Comment by jsquyres** [comment]
I'll bet you haven't done that since we made the DCO check required.

**Comment by shefty** [comment]
I _think_ I did it for 1.6.0rc1, which was just over a week ago.

**Comment by jsquyres** [comment]
I think that was #3773.

**Comment by shefty** [comment]
That PR was closed with a direct push.  So, there was a PR open on it; I just didn't merge it.  But the DCO check ran.
