### ISSUE TITLE
prov/usnic: Provider fails one of the MR mode tests.

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#3871]
See debug output here: 

```
FI: [FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY]
HINTS: [FI_MR_LOCAL, FI_MR_ALLOCATED]
Setting EOTHER
RET: -256
FAIL: fi_getinfo failed Unspecified error(256)
```

The problem is that we're returning more hints than the test passed us. I've narrowed it down to this interaction: 

[Here](https://github.com/ofiwg/libfabric/blob/master/prov/usnic/src/usdf_ep_dgram.c#L568-L569) we check the hints that were passed in using a core function. Since the core function returns that they are compatible, we don't change the defaults (we assume that our defaults are a subset of the user input) and end up returning this value. The problem seems to be that our default values require `FI_MR_VIRT_ADDR`, and `FI_MR_PROV_KEY` but the application does not request any RMA capabilities so another [core function](https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_attr.c#L450-L460) clears these bits in the check and our provider determines it can be used successfully.  

@shefty need a bit of help understanding what the appropriate fix is here. Are the `FI_MR_VIRT_ADDR/FI_MR_PROV_KEY` only for RMA operations? If so, should usNIC only be claiming that it needs `FI_MR_LOCAL` and `FI_MR_ALLOCATED`? Or is the check wrong? 

Also @jsquyres

**Comment by shefty** [comment]
VIRT_ADDR and PROV_KEY only apply to RMA/atomic operations.  So, if the app isn't wanting RMA, there's no need for it to support those bits or the provider to require them.  The core function that you reference is clearing these bits in that situation, so the app can work with a provider that it may not otherwise be able to use.

From the provider's perspective, it is supposed to set those bits that it needs.  The core will make the adjustments.  Since, AFAIK, usnic doesn't support RMA, it shouldn't be setting those bits -- only LOCAL and ALLOCATED.

**Comment by bturrubiates** [comment]
> VIRT_ADDR and PROV_KEY only apply to RMA/atomic operations. So, if the app isn't wanting RMA, there's no need for it to support those bits or the provider to require them. The core function that you reference is clearing these bits in that situation, so the app can work with a provider that it may not otherwise be able to use.
> 
> From the provider's perspective, it is supposed to set those bits that it needs. The core will make the adjustments. Since, AFAIK, usnic doesn't support RMA, it shouldn't be setting those bits -- only LOCAL and ALLOCATED.

I see, I think we misunderstood those mode bits originally. I can open a PR that reduces our requirements.
