### ISSUE TITLE
prov/sockets: hang with scalable endpoint

### ISSUE THREAD

**Issue by mshiryaev** [ofiwg/libfabric#3886]
Hello,

I faced with hang on sockets provider trying to utilize SEP feature although PSM2 provider works well. The reproducer is attached ([mep_reproducer.zip](https://github.com/ofiwg/libfabric/files/1773307/mep_reproducer.zip))

Here is the description of reproducer. Test is single-threaded and has simple pingpong pattern where each side send/recv multiple messages per iteration. Test works with 2 modes:

1. when all communication go over the single 0-th endpoint (this case works well)

2. and when (N-1) messages go over the 0-th ep and 1 message go over the 1-st ep

The hang happens on the second case and depends on cq polling ordering.
If we consider the sender side: it sends few messages over 0-th ep and 1 message over 1-st ep and then does polling. If we poll cq_1 till getting of completion and then switch to cq_0 then it works. But if will poll cq_0 before cq_1 (even just to get only 1 completion) then subsequent polling of cq_1 will hang.

To run test:
- launch "./mep_reproducer -f sockets" on the first node
- launch "./mep_reproducer -f sockets <hostname_of_first_node>" on the second node

It should work well. But if you will set env var TOUCH_CQ_0=1 on both nodes then polling ordering will correspond to description above and hang will happen.

**Comment by shefty** [comment]
I'm still debugging this.  I've tracked a problem down into sock_progress.c::sock_pe_read_hdr().  In that call is a check that a message queued on the receive socket is for the receive context being monitored.
```
if (sock_pe_is_data_msg(msg_hdr->op_type) &&
    msg_hdr->rx_id != rx_ctx->rx_id)
        return -1;
```
This check is failing, which leads to the hang.  Because sockets emulates scalable endpoints, traffic for different tx/rx contexts go over the same tcp connection.  It looks like a message for rx 0 is pending on the socket, but the code is only looking for messages for rx 1.  That message is left on the socket and never handled as long as the code only tries to process rx 1 messages.

I need to understand the code more to figure out the right fix.

**Comment by shefty** [comment]
See PR #3897 for a possible fix.  This PR has only been lightly tested at the moment.  It passes fabtests and the reproducer.

**Comment by mshiryaev** [comment]
Hi @shefty, I verified your patch fixed test-case with current message sizes.
size_t msg_sizes[] = { 256, 512, 8388608 };

But when I modified sizes I got hang again. For example, with the following message sizes:
size_t msg_sizes[] = { 16384000, 4000, 67108864, 16384, 150994944, 16384, 1769472, 1024, 2654208, 1536, 3538944, 1536, 1228800, 1024, 139392, 384 };

**Comment by shefty** [comment]
I updated the PR to progress the tx contexts as well.  I was able to run the reproducer with the message sizes that you mentioned.

**Comment by mshiryaev** [comment]
Thanks, this fixed the hang.
