### ISSUE TITLE
op-type in CQ entries?

### ISSUE THREAD

**Issue by rfaucett** [ofiwg/libfabric#393]
This is probably an old discussion I just missed, but shouldn't some forms of cq_entry contain the operation type that has completed?  If not in fi_cq_entry, at least in fi_cq_msg_entry and beyond?
As an app writer, I always found it useful to be able to switch early on SEND / RECV / ... and interpret the context based on that.  Yes, the app can encode that information into a known place in all context structs it uses, but I think I'd find that a little annoying - often structs we'd like to use as contexts have other constraints and requiring app authors to construct container structs for them seems slightly unfriendly, i.e.
```C
struct standard_context {
    uint32_t op_type;
    void *context_i_really_want;
};
```
And, yes, using different CQ for different ops works, but can be inefficient.

**Comment by shefty** [comment]
Since it appears this can be handled as a simple extension (new completion values), I think we try to address it by 1.0.  But even then, we aren't really time bound.

**Comment by shefty** [comment]
Thinking about this more, this could be addressed without any changes to the data structures.  Most of the CQ entry types have a flags field.  That could be used to provide additional details about the completion, with more refined control available than a simple op_type.

In the simplest case, the flags FI_SEND, FI_RECV, FI_TAGGED, FI_RMA | FI_READ, FI_RMA | FI_WRITE, FI_ATOMIC can be used to indicate the type of operation that completed.  The operation details would need to be a positive check, rather than assuming that a negative check means the opposite.  E.g. If FI_SEND is not set, this does not mean that the operation was a receive.

So, I think this can be handled as an update to the documentation and providers.
