### ISSUE TITLE
Layering multiple providers (More than 2) causes unintuitive behavior.

### ISSUE THREAD

**Issue by wckzhang** [ofiwg/libfabric#4203]
Since the addition of commit a170446d, libfabric has allowed the ability to layer more than 2 providers, which causes an unintuitive user issue.

When running Open MPI with OMPI_MCA_mtl_ofi_provider_include="tcp;ofi_rxm;ofi_mrail", the core provider utilized by libfabric is not tcp. It appears that the sockets provider is taking precedence over the tcp provider. I investigated the Open MPI code, and there does not seem to be an issue with the mtl_ofi_provider_include flag. When libfabric's configure is run disabling the other core providers, libfabric chooses the tcp provider without issue.

This may be the intended functionality described in the layering rule "If both the providers are utility providers or if more than two providers are specified, the rightmost provider would be compared."

However, this does cause the unintuitive behavior where the specified providers are not being utilized.

**Comment by shefty** [comment]
I consider this a bug.  I'll see if Arun can look into this.

**Comment by a-ilango** [comment]
I did some digging and the issue seems to be in mrail provider. I don't see a straightforward fix at this time. :/

OpenMPI calls fi_getinfo without specifying any provider name in the hints and later filters fi_info based on the provider name passed by the user. mrail provider limits fi_info list to just one entry if there were multiple fi_info returned from the underlying provider. This is to keep one fi_info per rail. So, mrail strips off the "tcp;ofi_rxm;ofi_mrail" fi_info which appears later in the list and hence OpenMPI is unable to find it. I'll try to see if we can somehow avoid this.

**Comment by wckzhang** [comment]
@a-ilango I have some ideas about what to do. I will look into this bug and send out a PR if I make progress. You can assign this issue to me.

**Comment by a-ilango** [comment]
@wckzhang I didn't get time to come back to this. Please go ahead if you want to work on it.

My preliminary thoughts are the following:

Calling fi_getinfo for each rail would give us:
```
rail0_info0 -> rail0_info1 -> ...
rail1_info0 -> rail1_info1 -> ...
```
We need to create a "header" mrail_info for similar fi_info from each rail. For example, if `info0` corresponds to `sockets;ofi_rxm;ofi_mrail` and `info1` corresponds to `tcp;ofi_rxm;ofi_mrail`, then we create two header `mrail_info` corresponding to them. Also we would need get back to the rail infos from the header infos.

The current code creates the header info only for `rail*_info0`.

**Comment by wckzhang** [comment]
@a-ilango My thoughts so far would be to change what happens inside of mrail_get_core_info so that it creates an array of lists (will probably use a hashmap of lists in v2). Each element in the array will be an info list corresponding to a different provider. Each following element in a list will be a different rail for the provider. The info list returned to the application will be the modified head elements of each list in the array. The num_rails uint32_t can be a global variable that is incremented when iterating over mrail_addr_strv. We can also do something similar to mrail_info_vec to cache the array of lists for each fi_getinfo. When the application calls mrail in the send path, mrail can then access this array of lists, find the appropriate provider, and use round robin on the rails provided. Is this in line with what you were thinking?

Some uncertainties are:
* What are the future plans for the MRAIL_ADDR_STRC environment variable?
    * Since MRAIL_ADDR_STRC has to be unique for every node, it's very finicky to work with
    * It looks like using this could break some of the API requirements. For example, if the application passes in src_addr in its hints, mrail will override this using MRAIL_ADDR_STRC.
    * To fix this, we could create a custom address structure for mrail which can contain multiple addresses and read it from src_addr instead.
    * I think this is a good chance to move away from using the MRAIL_ADDR_STRC environment variable. We can move out of source address rail detection to provider based rail detection. We could create automatic NIC detection programmatically using fi_getinfo as well as set some default behavior. Then MRAIL can be discoverable by default at a low priority. In addition, we can add a num rails environment variable in the case that a user would want to run multiple rails over the same NIC and distribute rails equally among the NIC's available.

**Comment by a-ilango** [comment]
> My thoughts so far would be to change what happens inside of mrail_get_core_info so that it creates an array of lists (will probably use a hashmap of lists in v2). Each element in the array will be an info list corresponding to a different provider. Each following element in a list will be a different rail for the provider. The info list returned to the application will be the modified head elements of each list in the array. 

This sounds like a reasonable approach.
> We can also do something similar to mrail_info_vec to cache the array of lists for each fi_getinfo.

Yes, I think mrail_info_vec can be used here. We could do something like the following:
```
mrail_info_vec:
	[0]: mrail_info_array0     
	[1]: mrail_info_array1
        ...

mrail_info_array*
	[0]: info_rail0 -> info_rail1 -> ... // sockets
	[1]: info_rail0 -> info_rail1 -> ... // tcp
        ...
```
It may also be possible to avoid caching fi_info for every invocation of fi_getinfo. We could have a fabric name based on the provider and the rails used and have it as a key into a hash table of cached fi_info lists. For any domain or endpoint open call, we could retrieve the correct info list using the fabric name. This would also need to modify (after making a copy) the cached fi_info list based on the attributes in `fi_info` passed to `fi_domain` or `fi_endpoint` call.
>When the application calls mrail in the send path, mrail can then access this array of lists, find the appropriate provider, and use round robin on the rails provided. Is this in line with what you were thinking?

I'm not sure why we need access this list on a send call. Once an mrail endpoint is opened, it would have references to underlying rails' endpoints.
> Since MRAIL_ADDR_STRC has to be unique for every node, it's very finicky to work with

I thought about this as well. It might be easier to use say, interface name instead of the IP address. But then the user would have to ensure, the interface names are uniform across a cluster and refer to the correct rail in every node.
> It looks like using this could break some of the API requirements. For example, if the application passes in src_addr in its hints, mrail will override this using MRAIL_ADDR_STRC.

I think if the app passes the rail addresses in `hints->src_addr`, the app should not set MRAIL_ADDR_STRC to avoid any overriding.
> To fix this, we could create a custom address structure for mrail which can contain multiple addresses and read it from src_addr instead.

Yes. The plan is to define a FI_STR_ADDRV address type for this purpose. It would be a vector of rail addresses that can be passed in `hints->src_addr`.

> We can move out of source address rail detection to provider based rail detection. We could create automatic NIC detection programmatically using fi_getinfo as well as set some default behavior. Then MRAIL can be discoverable by default at a low priority.

What do you mean by provider based rail detection? Is it something like use all rails that a provider can use?
>In addition, we can add a num rails environment variable in the case that a user would want to run multiple rails over the same NIC and distribute rails equally among the NIC's available.

In case of multiple rails over the same NIC, I'm assuming it's over multiple ports available on the NIC, right?

We would want to provide the right config options to the user based on what's often used and what can be implemented easily.

**Comment by wckzhang** [comment]
Hmm, I was looking into mrail_info_vec and mrail_get_info_cached, and it doesn't seem like what it should be doing. As far as I can tell, it looks for mrail_info_vec[index]->fabric_attr->name compared to the fabric_attr->name passed into mrail_fabric_open. If they match, it uses the mrail_info_vec[index] struct. However, it looks like the mrail_info_vec[index]->fabric_attr->name will be identical for every entry inside mrail_info_vec. This means that only mrail_info_vec[0] would ever be used.

What were your goals for mrail_info_vec and mrail_get_info_cached?

We could deprecate this and replace it with a hashmap instead maybe something with key like...

"<provider_name>, <rail 1>, <rail 2>, ..." and value being the fi_info struct list for that provider.


> I'm not sure why we need access this list on a send call. Once an mrail endpoint is opened, it would have references to underlying rails' endpoints.

You're right, this should be accessed on endpoint open, not on send.

> I thought about this as well. It might be easier to use say, interface name instead of the IP address. But then the user would have to ensure, the interface names are uniform across a cluster and refer to the correct rail in every node.

I think we should keep user requirements to a minimum. Having them ensure such would be prone to error. I think we should automate NIC detection, remove MRAIL_ADDR_STRC, and have hints->src_addr as the only option allowing for specific rails.

> Yes. The plan is to define a FI_STR_ADDRV address type for this purpose. It would be a vector of rail addresses that can be passed in hints->src_addr.

What is the current progress of the FI_STR_ADDRV address type? Is it in design/implementation? I can work on it if nobody else is.

> What do you mean by provider based rail detection? Is it something like use all rails that a provider can use?

Yes, use all rails that a provider can use in the default case. If the application requests that provider, we should only provide the rails that can support that provider. When rails are specified say through hints->src_addr we can do some additional logic to ignore other rails or if the rail specified doesn't support the provider requested, we can have an error or warning.

> In case of multiple rails over the same NIC, I'm assuming it's over multiple ports available on the NIC, right?

Yes, in some cases, opening multiple ports over the same NIC can be useful. I'd imagine it would work as follows: 
>NUM_RAILS environment variable specifies a number of rails: 4
provider sockets;mrail is requested and supported on two NIC's that have been detected/specified.
Mrail cycles through the sockets;mrail info list called "info" in a round robin fashion.
It assigns rail 1 to info->src_addr, rail 2 to info->next->src_addr, then reaching the end, seeing ->next = NULL, goes back to the beginning so rail 3 is info->src_addr and rail 4 is info->next->src_addr

In fact, with a custom FI_STR_ADDRV address type, we only need one fi_info struct instead of a list I think?

**Comment by shefty** [comment]
My general expectation is that there would be a list of lists of fi_info's.  Each fi_info corresponds to a single rail.  If needed, a fi_info can be duplicated to appear as more than 1 rail.  Each fi_info list has some sort of mrail fi_info 'header'.  That is what gets reported to the app.  (I'm guessing this is the case today.)

The 'header' src_addr can be a vector of the src_addr values in the corresponding list.

As for other fields, I think the value depends on the list values.  For example, what is currently going into the fabric name, domain name, and provider name fields?  IMO, if all rails have the same value, it should match.  If the rails have different values, then using some sort of concatenated value seems reasonable.

Note that the list of the lists shouldn't be that large, and we only walk it maybe once.

**Comment by wckzhang** [comment]
@a-ilango What were your goals for mrail_info_vec and mrail_get_info_cached? The implementation will need to be changed to fall in line with the new design. If you give me a good idea of what you would like/use cases, I can design and implement the changes.

**Comment by a-ilango** [comment]
> What were your goals for mrail_info_vec and mrail_get_info_cached?

The fabric open call accepts only a fi_fabric_attr. So we cache the fi_info list during fi_getinfo time so that we can get back to it later using fabric name. Future work was to append an index to the fabric name so that we fetch the right fi_info.

Alternatively, making the fabric name a concatenation of rail fabric names which can be used as the key to search in a list or a hash map sounds better.

> I think we should automate NIC detection, remove MRAIL_ADDR_STRC, and have hints->src_addr as the only option allowing for specific rails

A goal of MRAIL_ADDR_STRC is to allow easy specification of which rails to use by the user. Even if hints->src_addr is used I would assume the app would take input from the command line to fill hints->src_addr. That's same as using an environment variable. Automatic rails detection would be a separate case though.

FI_STR_ADDRV  first needs to be defined in the man page. @shefty, I think this is not done yet. If we need to support default case of using all rails available to a provider, we may have it as an array of strings with a final NULL to denote the end or we could make it as FI_ADDR_STRC and have strings of type FI_ADDR_STR delimited by comma.

Multiple ports on a NIC could show up as separate domains and hence can have separate fi_info. I think this would be the case at least with IPoIB since they set separate device names for different ports. Whether to report them as same domain is something that needs to be decided.

> In fact, with a custom FI_STR_ADDRV address type, we only need one fi_info struct instead of a list I think?

Yes, this is possible if the rails are uniform (have same attributes). Otherwise we would have to summarize the attributes in the "header" fi_info. We might also want to expose only the header fi_info to apps.

So does the following sound good:
```
if (rail fabric names are same):
	mrail_info->fabric_attr->name = mrail_<rail_fabric_name>
else:
	mrail_info->fabric_attr->name = concat("mrail_", rail0_fabric, rail1_fabric, ...)
```
@shefty is this what you suggested?

The following are the use cases that we have discussed so far:
1. App specifies which rails to use via FI_MRAIL_ADDR_STRC (this also allows specifying primary / failover rails).
2. App specifies just the provider and expects to use all rails available.
3. App specifies specific number of rails to use with a provider.

**Comment by shefty** [comment]
I think creating some sort of concatenated fabric name will be needed in cases where the underlying names differ.  It would be nice to be able to open the underlying fabrics when the mrail fabric is opened, but we could technically defer the work until the domain is opened.  Your pseudo-code looks reasonable, though we can figure out the actual name format.

I have not defined ADDRV yet, but I was leaning toward using one long string with a separator, similar to the provider name (and what may also turn into the fabric and domain names).

If mrail has no other configuration data, picking rails based on input hints, such as fabric, domain, or provider name, would allow for using all rails for a given provider or attached to the same fabric.  All rails would be active in this case.  I think we just need to define the default behavior when individual rails aren't identified.  It may require mrail to check which environment variable have been set.

**Comment by a-ilango** [comment]
> It would be nice to be able to open the underlying fabrics when the mrail fabric is opened, but we could technically defer the work until the domain is opened.

This would make it simpler but caching rail infos still has some other benefits like avoiding additional fi_getinfo calls during domain and endpoint creation. Especially with layered providers, there's a lot of fi_getinfo calls.

One thing we have to make sure is the "header mrail info" is representative of the rails infos. For uniform rails, this is not a problem. Otherwise the header has to summarize the attributes.

So to start with:
1. Assume only uniform rails.
2. Expose only header fi_info for: specified rails (FI_MRAIL_STR_ADDRC) or all rails for a provider that belong to the same fabric (subnet). We may want to avoid interfaces like localhost in the default case.
3. Set fi_info->src_addr to address of type FI_ADDR_STRC (format to be defined)
4. Set fabric_attr->name (format to be defined)
5. Cache rail infos in a list / hashmap keyed by fabric names.

Does the above sound good?

**Comment by shefty** [comment]
I agree with storing the fi_info list.  I'm just suggesting that if we can't pick the right list using only the fabric attributes, then we could wait until we have the full fi_info structure when the domain is opened.  Ideally, I'd like to pick it when the fabric is opened, as I think that will be easier.  Heck, we may only end up with 1 option anyway.

I don't know that it will be that much work to craft a common fi_info that represents all rails.  Many of the attributes will be mrail specific.

IMO, the biggest question is identifying the rails.  I was assuming that using an environment variable to select rails using the src_addr was the easiest option.  But maybe just specifying the provider and using all domains or all src_addr options (minus any fi_info where FI_REMOTE is not set) that are available will work better?

**Comment by rajachan** [comment]
@a-ilango #2 on your list might be more restrictive than you'd want. Multiple rails could be used for either performance or fault-tolerance, and in the latter case, you could very well have rails that don't belong to the same fabric despite belonging to the same provider; primarily to isolate fault domains.

**Comment by a-ilango** [comment]
For # 2 the restricted case is only for default behavior (when config is not specified using say FI_MRAIL_ADDR_STRC). We wouldn't want to surprise users by clubbing rails that are not supposed to be clubbed. If the user wants something like fault tolerance (which requires rails across fabrics), then they need specify it explicitly. Otherwise we won't know which rail/fabric is primary and which one is for fail over.

**Comment by a-ilango** [comment]
We would want to support the common use case of providing higher bandwidth without any config required from user. e.g. On nodes that have only one fabric, we can by default expose all rails as a group.

**Comment by rashikakheria** [comment]
How are we approaching detecting different NICs for a given provider (without FI_MRAIL_ADDR_STRC)? Given that a NIC can have multiple address formats attached to it and/or could be loopback?

**Comment by a-ilango** [comment]
From fi_getinfo perspective, different NICs for a given provider would be similar to multiple ports on the same NIC: an fi_info would be generated for each NIC. If a NIC has multiple addresses configured, I think that would result in multiple fi_infos as well. So without a configured FI_MRAIL_ADDR_STRC, you would not have control as to which fi_infos would form the individual rails.

Loopback addresses would need to be skipped as they may not be useful.
