### ISSUE TITLE
Visual Sutdio 2017 community 15.3 retargeting solution pops "Collection was modified" Error

### ISSUE THREAD

**Issue by germanafro** [ofiwg/libfabric#4392]
- cloned a fresh copy
- opened with VS 2017 CE
- right click a projekt  
- Select Retarget Projects 
- choose any Option
- Error prompt 

coudl this be a reason? : 
>E:\workspace\c++\libfabric\Libfabric.Build.Default.props(3,3): warning MSB4011: "E:\workspace\c++\libfabric\Libfabric.Build.Default.props" cannot be imported again. It was already imported at "E:\workspace\c++\libfabric\pingpong.vcxproj (34,3)". This is most likely a build authoring error. This subsequent import will be ignored.

reason for retargeting is : 
>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for Intel C++ Compiler XE 15.0 (Platform Toolset = 'Intel C++ Compiler XE 15.0') cannot be found. To build using the Intel C++ Compiler XE 15.0 build tools, please install Intel C++ Compiler XE 15.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

edit:
on a closer look, do i actually need to use the C++ Compiler XE 15.0 build tools ? can I use them with VS2017? if not I find that severly limiting. Google is certainly not on my side today trying to resolve this issue.  VS updater does not seem to have this compiler either.

**Comment by dmitrygladkov** [comment]
libfabric has 6 VS solution configuration:
* 1-2: Debug/Release ICC (restricted support for Intel Compiler XE 15.0 only)
* 3-4: Debug/Release v140 (VS 2015 tool set)
* 5-6: Debug/Release v141 (VS 2017 tool set)

You may switch to Debug/Release v140 (VS15) and v141 (VS15 (backward compatibility mode) and VS17) configuration to build libfabric using VS compiler. 

>coudl this be a reason? 
E:\workspace\c++\libfabric\Libfabric.Build.Default.props(3,3): warning MSB4011: "E:\workspace\c++\libfabric\Libfabric.Build.Default.props" cannot be imported again. It was already imported at "E:\workspace\c++\libfabric\pingpong.vcxproj (34,3)". This is most likely a build authoring error. This subsequent import will be ignored.

This is just warning, because we have 4 projects (libfabric, fi_info, fi_pingpong, fi_strerror) in libfabric VS solution and all of them include properties file `Libfabric.Build.Default.props` to determine Windows Target on your system. This helps user/developr to avoid re-targeting VS solution when tey're going to build libfabric from sources on Windows.

**Comment by germanafro** [comment]
ohh ty I didnt see anything about that in the readme.
I managed to compile now, but might I add, that I also had to snoop out a basically hidden readme file inside the prov/netdir which told me where to get the headers that were missing. 

I can imagine other people searching for hours or days to find what i had been stumbling over by accident. maybe I'll draft a more clear and complete readme for windows and commit it later.

**Comment by dmitrygladkov** [comment]
> maybe I'll draft a more clear and complete readme for windows and commit it later

It would be great. But we will do our best to improve support of fabric interfaces on Windows. And user experience to work with libfabric on Windows is our primary task here, because this is not straightforward thing right now.
