### ISSUE TITLE
prov/tcp;ofi_rxm: "Message truncated" errors when running multi-threaded

### ISSUE THREAD

**Issue by AddyLaddy** [ofiwg/libfabric#4644]
I am hitting numerous issues when trying to use the "tcp;ofi_rxm" provider from a multi-threaded linux process that is sending messages (fi_tsend) with sizes from 8 to 1MiB bytes.
I see errors such as;

`libfabric:ofi_rxm:cq:rxm_cq_write_error_trunc():135<warn> Message truncated: recv buf length: 64 message length: 16384`

If I run it the application single threaded or add explicit mutexes around the app's OFI calls it runs reliably.

**Comment by dmitrygladkov** [comment]
@AddyLaddy Thanks for reporting this.

What the `fi_info::fi_domain_attr::threading` do you set in multi-threading case?
If you don't set any value to this field, it should be thread-safe. Could you run the application with the `FI_OFI_RXM_SAR_LIMIT=0` environment variable, please?

**Comment by AddyLaddy** [comment]
Thanks Dmitry. We don't set any value for `fi_info::fi_domain_attr::threading`.
I tried with `FI_OFI_RXM_SAR_LIMIT=0` and no longer see the error.

I didn't see any mutex protection in the RXM segmentation code when I was digging yesterday. Does it need it?

**Comment by AddyLaddy** [comment]
In my experiments where I added mutex locks to the plugin that uses libfabric, I found that it would work more reliably if I made a critical region of the code segments that were calling `fi_cq_readfrom()` and `fi_trecv()`. My assumption is that these are being called independently by different threads.

**Comment by dmitrygladkov** [comment]
Addy, yes, receive SAR code (reassembling) need to be redesigned in order to have fine-grained mutex protection instead of naive approach that acquires EP and CQ locks and then reassemble message. Unfortunately, I don't have a working multi-threaded sample/test that can be used for debugging purposes. If you could help with that, it would be great.

@shefty @a-ilango what do you think about disabling SAR in 1.7 for applications that requires `fi_info::fi_domain_attr::threading = FI_THREAD_SAFE`? SAR is not safe enough for multi-threaded scenarios.
I tried to fix this problem by adding CQ and EP locks around SAR code on the receiver side. It leads to double locking of the same "spinlock" (the fastlock `acuqire` function reports it in single-threaded scenarios).

**Comment by shefty** [comment]
Disabling SAR for thread safe is reasonable.  Let's not rush a fix for this.  We can apply an update to a 1.7.1 release if it's available by then.

**Comment by a-ilango** [comment]
> what do you think about disabling SAR in 1.7 for applications that requires fi_info::fi_domain_attr::threading = FI_THREAD_SAFE?

Sounds good. 👍

**Comment by shefty** [comment]
PR #4680 _may_ help address this issue.  That PR fixes the locking around the progress engine which could lead to the problem being reported.

**Comment by shefty** [comment]
Please re-test with the tip of master or v1.7.0rc2 (out shortly).  The locking inside the rxm provider was re-worked.

**Comment by AddyLaddy** [comment]
I've re-run my reproducer against the tip of master and I can now no longer generate the issue. Thanks for fixing this!

**Comment by dmitrygladkov** [comment]
@shefty @AddyLaddy Thank you!
