### ISSUE TITLE
register memory for direct fabric access is time consuming

### ISSUE THREAD

**Issue by tanghaodong25** [ofiwg/libfabric#4738]
It took more than 20 seconds to register 256 GB memory for direct fabric access with fi_mr_reg. the CPU's overhead became excessively high (close to 100%) when calling fi_mr_reg. The provider we're using is verbs. Do you think this is normal? Is there any other way to accelerate the memory registration?

**Comment by dmitrygladkov** [comment]
There are no standard ways to accelerate `fi_mr_reg`, because OFI Verbs provider depends on the `ibv_reg_mr` implementation provided by IB Verbs provider (mlx5, hfi1 or etc). But if you use Mellanox OFED, you may use experimental ODP feature for MR (https://ofiwg.github.io/libfabric/master/man/fi_verbs.7.html)

If you does the memory registration for multiple the same memory blocks (or this memory block is inside of some previously registered memory block ), `FI_VERBS_MR_CACHE_ENABLE=1` may give you better performance than default behavior (but this functionality relies on free/realloc GLIBC hooks)

**Comment by shefty** [comment]
This sounds normal.  The use of huge pages should help.  ODP can defer the cost of registration until the MR is accessed the first time, but the delay will still be there.

**Comment by dmitrygladkov** [comment]
> ODP can defer the cost of registration until the MR is accessed the first time, but the delay will still be there.

Yes, I meant this

**Comment by tanghaodong25** [comment]
@dmitrygladkov @shefty Thanks for your prompt reply. We've tried ODP, the latency didn't improve. Actually, we register memory directly from NVDIMM, do you think the asynchronous memory registration would help?
