### ISSUE TITLE
Notification of forced memory deregistration (e.g. munmap)

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#484]
Notification of forced memory deregistration (e.g. munmap)

This is from MPI requirements list.

**Comment by shefty** [comment]
This has to be handled by the kernel, not the library.  This isn't something user space can properly enforce.

**Comment by jsquyres** [comment]
Agreed.  But it would be nice to have a simple userspace API for the userland side of it.

**Comment by shefty** [comment]
The app can call close on the MR.  Or is there something more that's desired?

**Comment by jsquyres** [comment]
I'm not sure what you mean.

The issue is when registered memory was released from the process -- MPI needs to know when this happens because it may have happened outside of the MPI API.

Remember Roland's mmunotify system?

**Comment by shefty** [comment]
Got you.  I didn't understand the issue.

**Comment by shefty** [comment]
This feature seems more related to MPI's implementation over libibverbs, than it is an application level request of libfabric.  Since libfabric does not require that applications register data buffers for local only access, I believe this request is more appropriate as an implementation requirement for whatever tries to cache memory registration than something to expose up through the API.

IOW, if a provider caches registration requests, then the provider needs to interface to some mmunotify API.  If middleware does the caching, then it needs to interface with mmunotify.  But libfabric should not be that interface.  If anyone disagrees, please re-open this issue.  :)

**Comment by goodell** [comment]
I would still like to see this sort of notification exposed through libfabric EQs.  I can imagine a combination of kernel+libfabric support that is aware enough of registered regions that it both simplifies the app's/middleware's registration cache implementation and reduces the overall amount of work that needs to be done by the whole stack, e.g. by collapsing two interval tree lookups (kernel+middleware) down to one (kernel only).

Jeff and I have an unfinished proposal sitting in a notes file somewhere that we need to dust off and officially propose at some point.  But we can leave this issue closed until we actually get enough cycles and priority pressure to finish it.
