### ISSUE TITLE
prov/verbs: Handle case where no verb devices are present

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#512]
From #229 

"On a host that has has no devices that use the kernel drivers/infiniband stack, I get this:

librdmacm: Warning: couldn't read ABI version.
librdmacm: Warning: assuming: 4
librdmacm: Fatal: unable to get RDMA device list
fi_getinfo No such device

**Comment by shefty** [comment]
If no verbs devices are present on the system, the verbs provider should detect this and silently fail with ENODATA on getinfo calls.  The verbs provider may need to call ibverbs directly, see if any devices are present, and fail gracefully if nothing is available.

**Comment by pmmccorm** [comment]
I am not able to reproduce this. rdma_getaddrinfo will return ENODEV in errno, which the verbs provider will return as ENODATA and thing will behave as expected.

**Comment by goodell** [comment]
As of ofiwg/libfabric@4524f98 and ofiwg/fabtests@09e4b51, I can no longer reproduce this issue on the machine in question.  The most likely explanation is that all the recent fixes in the verbs provider caused us to call librdmacm differently, since rolling back to (arbitrarily selected) commit cfc070a from a few days ago causes the problem to resurface.
