### ISSUE TITLE
prov/psm2: psm2_finalize

### ISSUE THREAD

**Issue by tanghaodong25** [ofiwg/libfabric#5164]
Hi,

We would like to use libfabric psm2 prov in our application but hit the eager message issue. One of our use cases is to 
reinitialize psm2 in **one process**, which means call fi_fabric -> fi_close(&fabric->fid) -> fi_fabric.

The error message is:
Received eager message(s) ptype=0x1 opcode=oxcc from an unknown process.

After reading the code, we find psmx2_fini() will only be called when exit() is called, while in our use case, we don't exit current libfabric process, and reinitialize psm2 in **the same process**. Do you think the eager message issue in our application is related to this? If so, how can we explicitly call psm2_finalize()?

```c++
static void psmx2_fini(void)
{
	FI_INFO(&psmx2_prov, FI_LOG_CORE, "\n");

	if (! --psmx2_init_count && psmx2_lib_initialized) {
		/* This function is called from a library destructor, which is called
		 * automatically when exit() is called. The call to psm2_finalize()
		 * might cause deadlock if the applicaiton is terminated with Ctrl-C
		 * -- the application could be inside a PSM2 call, holding a lock that
		 * psm2_finalize() tries to acquire. This can be avoided by only
		 * calling psm2_finalize() when PSM2 is guaranteed to be unused.
		 */
		if (psmx2_active_fabric) {
			FI_INFO(&psmx2_prov, FI_LOG_CORE,
				"psmx2_active_fabric != NULL, skip psm2_finalize\n");
		} else {
			psm2_finalize();
			psmx2_lib_initialized = 0;
		}
	}
}
```

Thank you!

**Comment by j-xiong** [comment]
psm2_init / psm2_finalize are not supposed to be called more than once. The library is initialized when fi_getinfo is called the first time. There is no re-initialization in fi_fabric. The error message you saw is more likely caused by reusing endpoint id w/o cleaning up old connection status. Currently there are two possible way to work around this: one is to set FI_PSM2_DISCONNECT=1. This will let the connected peer to call psm2_ep_disconnect when local endpoint is closed. This method works best when only one side needs to set this variable, e.g., client-server style applications. The other way is to explicitly disconnect by calling fi_av_remove, this requires more work at the application side.

**Comment by tanghaodong25** [comment]
Great! thanks for your info, we'll try both of the suggestions in our application and give the feedback.
