### ISSUE TITLE
prov/shm: Failing fi_rdm unit tests

### ISSUE THREAD

**Issue by rajachan** [ofiwg/libfabric#5182]
When running fabtests against the `shm` provider, I noticed it was failing the fi_rdm unit test:

```
- name:   fi_rdm g00n13s -p "shm"
  result: Fail
  time:   121
  server_cmd: /scratch/libfabric/fabtests/install/bin/fi_rdm g00n13s -p "shm"
  server_stdout: |
    Killed by signal 15.
```

With debug logs:
```
libfabric:42331:core:core:fi_fabric_():1084<info> Opened fabric: shm
libfabric:42331:shm:av:util_av_init():455<info> AV size 1
libfabric:42331:shm:av:smr_map_to_region():161<warn> shm_open error
libfabric:42331:shm:av:smr_map_to_region():161<warn> shm_open error
libfabric:42331:shm:av:smr_map_to_region():161<warn> shm_open error
```
The shm_open() call is failing with `ENOENT`. All other fabtests are passing just fine.

**Comment by aingerson** [comment]
The shm provider fails the negative tests because it allows for any destination address as an acceptable address which gets converted into a shared memory region name. When the provider tries to "connect" to a peer with a bad address and fails, it will just wait until the peer initializes its shared memory region. With negative tests, this doesn't work since it won't detect the bad address in the first place.
When testing the shm provider, we skip the negative tests by using the -N flag with the runfabtests.sh script

**Comment by aingerson** [comment]
We could also add a timeout of some sort to stop trying to connect to a peer after X seconds/tries

**Comment by rajachan** [comment]
Got it, that makes sense. You might want to add this test to the shm exclude list then.

**Comment by aingerson** [comment]
That's a good idea. I'll do that right now. Thanks!

**Comment by aingerson** [comment]
Just remembered why I didn't add it to the exclude file - the negative tests are just unit tests that input bogus destination addresses so there's not a great way to omit them in the exclude files since they look for arguments in each test.
