### ISSUE TITLE
[PSM2] Unhandled exception [PSM2_MQ_SENDREQS_MAX & PSM2_MQ_RECVREQS_MAX]

### ISSUE THREAD

**Issue by fsalem** [ofiwg/libfabric#5243]
While sending RDMA messages as fast as possible between client and server, I get one of these two exceptions (which are because of the same reason):
- Exhausted 1048576 MQ isend request descriptors, which usually indicates a user program error or insufficient request descriptors (PSM2_MQ_SENDREQS_MAX=1048576)
libfabric:135750:psm2:core:psmx2_fabric_close():48<info> refcnt=3
terminate called without an active exception

- Exhausted 1048576 MQ irecv request descriptors, which usually indicates a user program error or insufficient request descriptors (PSM2_MQ_RECVREQS_MAX=1048576)
libfabric:135750:psm2:core:psmx2_fabric_close():48<info> refcnt=3
terminate called without an active exception

The implementation is based on sending as many RDMA messages as possible from a client to a server. The client collects the completion events (FI_COMPLETION) for time to time, which limits the injection rate. But unlike the GNI Provider, it seems that the completion events are generated when the message left the source message and not delivered to the destination. 

- Is there any way in Libfabric to check the current isend or irecv counter in order to limit the injection rate?
- Does PSM2 provider handle this limitation internally?
- Are RDMA messages handled as normal messages? Why aren't RDMA messages written directly to the destination memory?

**Comment by j-xiong** [comment]
RMA in the psm2 provider is emulated in one of two ways: for small size (up to a few kilobytes), it is done via active message. for large size, it is done using send/recv. The exception you observed should belong to the latter case.

For the large size case, completion at the initiator side is generated when the corresponding send completes. In order to ensure the data being delivered before generating this completion, the FI_DELIVERY_COMPLETE flag is needed.

There is no guarantee that completion is ordered. It can be helpful to ensure progress is made by inserting fi_cq_read or fi_cntr_read between the fi_write() calls. Also, what is the server doing all the time, does it make progress calls or just sit idle?

**Comment by fsalem** [comment]
Hi,

Thanks so much for your response. The server just sits idle and the client keeps writing data in its memory. Regarding the FI_DELIVERY_COMPLETE flag and according the manpage (https://ofiwg.github.io/libfabric/v1.8.0/man/fi_cq.3.html), this flag applies only to reliable endpoints, which is not the case with RDM. Please correct me if I am mistaken.

Thanks in advance


— 
Best regards,
Farouk Salem


Zuse Institute Berlin (ZIB)
Takustraße 7
14195 Berlin
Germany

Phone:  	+49 30 841 85 - 204
Fax:		+49 30 841 85 - 311
Mobile:  	+49 15 255 454 962
Page:	http://www.zib.de/members/salem

**Comment by j-xiong** [comment]
RDM is reliable endpoint and the FI_DELIVERY_COMPLETE flag applies. 

If the server just sits idle, does it ask for auto progress? This can be done by setting hints->domain_attr->data_progress to FI_PROGRESS_AUTO. Progress must be made in some way to get the large size RMA protocol working.

**Comment by j-xiong** [comment]
Seems to be a user error. No update for over one year. Close now.
