### ISSUE TITLE
prov/verbs: XRC regression with commit d38c8869

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#5427]
With commit d38c8869, XRC tests hang immediately. This was noticed on Oct 8th, when master was built on our CI system. 

@shefty FYI. Do you notice anything particularly strange? 
@swelch  FYI. We'll need to get this fixed quickly. 

```
2019-11-11T00:55:57.298Z] # (in test file contrib/cray/bats/mpi.bats, line 208)
[2019-11-11T00:55:57.298Z] #   `[ "$status" -eq 0 ]' failed with status 124
[2019-11-11T00:55:57.298Z] # # OSU MPI Latency Test v5.4.1
[2019-11-11T00:55:57.298Z] # # Size          Latency (us)
[2019-11-11T00:55:57.298Z] # srun: error: cn48: task 0: Exited with exit code 124
[2019-11-11T00:55:57.298Z] # srun: error: cn49: task 1: Exited with exit code 124
[2019-11-11T00:57:03.385Z] Sending interrupt signal to process
[2019-11-11T00:57:23.386Z] After 20s process did not stop
```

**Comment by shefty** [comment]
I don't see anything in the PR that could cause this.  The xrc related changes look straightforward, which suggests that there's likely a simple fix that I'm not immediately seeing.  :)

**Comment by swelch** [comment]
@jswaro - I will take  a look.

**Comment by swelch** [comment]
> I don't see anything in the PR that could cause this. The xrc related changes look straightforward, which suggests that there's likely a simple fix that I'm not immediately seeing. :)

@shefty - I don't see anything obvious looking at the source, I will debug and see what is going on.

**Comment by swelch** [comment]
@shefty, @jswaro - The change replacing the "hfi1"/"qib" strncmp checks with the NIC vendor ID looks to have inadvertently inverted the logic for setting the functions. Either need to remove the "!" or just swap the contents of the if/else blocks. Do you want me to prepare a patch?

**Comment by shefty** [comment]
That vendor id is for Mellanox, so the intent was the revert the logic.  Please prepare a patch, but I'm still missing something regarding the problem I think

**Comment by swelch** [comment]
> That vendor id is for Mellanox, so the intent was the revert the logic. Please prepare a patch, but I'm still missing something regarding the problem I think

Maybe best to hold off on this PR for now then. It might be better that we revert that portion of the commit. I'll dig a little deeper and see if a different change is needed.

**Comment by shefty** [comment]
I expected that using fi_ibv_post_send_track_credits / fi_ibv_poll_cq_track_credits should work in all cases.  The direct calls to ibv_post_send / ibv_poll_cq are just optimizations that skip the credit increments.  I'm still not seeing wrong with the patch, so I would look more at a change that wasn't made somewhere.  Does reverting the commit allow xrx to work?

**Comment by swelch** [comment]
@shefty - Ok there are several problems here.

1. XRC does not seem to like the tracked versions.
2. I believe that Mellanox PCI Vendor ID is 0x15b3 not the 0x02c9 in the check.
3. The verbs provider is not correctly setting the vendor_id string consistently to how other providers are doing it.

Let me create a patch that addresses 2 and 3, then 1 is not an issue since XRC relies on Mellanox hardware.

**Comment by shefty** [comment]
Do we know why xrc doesn't work with the tracked versions?  I looked through the code and nothing stood out to me.  I thought maybe xrc was taking a path that didn't call the domain send/poll handlers, but I didn't see that anywhere.

**Comment by swelch** [comment]
> Do we know why xrc doesn't work with the tracked versions? I looked through the code and nothing stood out to me. I thought maybe xrc was taking a path that didn't call the domain send/poll handlers, but I didn't see that anywhere.

I don't see anything obvious either, it appears to run out of CQ credits but it looks like every post/poll call should go through the tracked versions. It will require some debug to fully understand.

**Comment by shefty** [comment]
I wonder if xrc is setting IBV_WC_RECV flag correctly.  That might explain an immediate hang.

**Comment by swelch** [comment]
> I wonder if xrc is setting IBV_WC_RECV flag correctly. That might explain an immediate hang.

@shefty - The credits check was invalid. It does not work for XRC because the underlying XRC Send QP context does not point to a message EP, so fi_ibv_post_send_track_credits() is dereferencing an invalid address/offset. The context of an XRC Send QP points to the domain that owns the initiator QP so that the QP can be shared among message EP. The message EP that creates the physical XRC Send QP can be closed, but the QP will live on if it has been shared/referenced with another message EP.

I'm pretty sure I could do something here based on QP type to make it work if you believe we should, but would end up adding some additional overhead for all cases to the already slower path and isn't really needed. We could instead add an assert() and/or check when the tracking functions are set that make sure XRC is not specified for the domain.

**Comment by shefty** [comment]
I don't think it's worth fixing at this time.  It would be worth adding an assert() that xrc takes the correct path, or simply expanding the if statement that checks the vendor id to also check if xrc is in use.
