### ISSUE TITLE
fi_pep_bind missing in fi_endpoint(3)

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#548]
There are entries for fi_ep_bind and fi_scalable_ep_bind, but no entry for fi_pep_bind. Is this intentional?

**Comment by goodell** [comment]
Nope.  It looks like an oversight on my part when I fixed the entire absence of `fi_pep_bind` in #522.  I would normally take care of it, but I'm traveling this week and trying to juggle lots of things.  If you have a minute to update the man pages, please go ahead.  Otherwise I'll fix it by Friday.

**Comment by bturrubiates** [comment]
Sure I can do that. I'm new to libfabric but from my understand the description for fi_pep_bind should be identical to fi_ep_bind right? From the tests I've been looking at I know it supports being bound to an event queue, but does it support all of the fabric resources that the active endpoint bind does (event queue, completion queue, counter, address vector, and memory region)?

**Comment by shefty** [comment]
Fi_pep_bind is nearly identical to fi_ep_bind -- takes struct fid_pep rather than struct fid_ep.  A passive endpoint may only be bound to an event queue.

**Comment by bturrubiates** [comment]
Thank you @shefty, PR submitted.
