### ISSUE TITLE
benchmark tools of libfabric

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [ofiwg/libfabric#5522]
Today I run `fi_pingpong` with `usnic` provider, and below is result:   
```
bytes   #sent   #ack     total       time     MB/sec    usec/xfer   Mxfers/sec
64      1m      =1m      122m        5.44s     23.52       2.72       0.37
256     1m      =1m      488m        5.89s     86.92       2.95       0.34
1k      1m      =1m      1.9g        7.48s    273.65       3.74       0.27
```
And I find I can not see transport speed of data which size is larger than 1k , and I want to see transport speed of data which size is more that 1k , so I add a `-S 2000` parameter into command line such as:   
```
fi_pingpong -p usnic -I 1000000 -S 2000 10.0.0.2
```
But I received an error as below:   
```
[error] util/pingpong.c:528 : ctrl/read: no data or remote connection closed
```
It seems that I can't send data size of which is over 1k with usnic provider in `fi_pingpong`.  
So is there any other tools that enable me to see transport speed of data size of which is large that 1MB、100 MB and so on.?

**Comment by Keepmoving-ZXY** [comment]
And I also very confused why libfabric is designed to limit size of message the send interface (such as `fi_send`) can process,  can you explain it to me?

**Comment by jsquyres** [comment]
The usnic provider only provides `FI_EP_DGRAM` -- i.e., unreliable datagrams.  Specifically, is uses UDP as its transport, and sets its max message size to the MTU of the Ethernet network which it is using.  In short: usnic is basically OS-bypass UDP.

Hence, if you have an MTU of 1500, your max message size is going to be somewhere around 1480 -- it will return an error if you try to send a message larger than that.  If your MTU is 9000, your max message size is somewhere around 8980 or so.

Hence, it's neither the libfabric core nor fi_pingpong which is limiting your individual messages to MTU size -- it's the usnic provider itself.

-----

Note, too, that we just merged a fix for `fi_pingpong` that affected the usnic provider on the git master HEAD as well as on the v1.9 and v1.8 branches, and new tarballs have not been formally released yet.  Meaning: if you have a v1.8.x or v1.9.x tarball, `fi_pingpong` will fail with the usnic provider.  You have a few options:

1. Use an older series for usnic (e.g., v1.7)
2. Wait for the next releases for v1.8.x / v1.9.x
3. Use a git clone / checkout of the relevant release branch
4. Manually apply a patch to your libfabric tarball (3bf9513f284a89ae834dc58680634a9f817bc49c).  For example:
```shell
$ wget https://github.com/ofiwg/libfabric/commit/3bf9513f284a89ae834dc58680634a9f817bc49c.diff -O fi-pingpong-fix.diff
$ wget https://github.com/ofiwg/libfabric/releases/download/v1.9.0/libfabric-1.9.0.tar.bz2
$ tar xf libfabric-1.9.0.tar.bz2
$ cd libfabric-1.9.0
$ patch -p1 < ../fi-pingpong-fix.diff
```

That being said, don't forget that `fi_pingpong` isn't really a benchmark.  It gives a good indication of performance, but it's not perfect / not a proper benchmark (e.g., it doesn't do warmup sends).  I see you pumped up the number of iterations -- that's good -- but don't forget to use processor affinity to bind `fi_pingpong` to a process NUMA-near the Cisco VIC.  For example (on my network with a 9K MTU):

```
$ hwloc-bind socket:1.core:4 ~/bogus/bin/fi_pingpong -p usnic -I 10000 192.168.2.1
bytes   #sent   #ack     total       time     MB/sec    usec/xfer   Mxfers/sec
64      10k     =10k     1.2m        0.04s     30.64       2.09       0.48
256     10k     =10k     4.8m        0.04s    123.16       2.08       0.48
1k      10k     =10k     19m         0.05s    431.05       2.38       0.42
4k      10k     =10k     78m         0.08s   1059.27       3.87       0.26
```

Also, I note that there seems to be something odd with the `fi_pingpong` `-S` option -- at least at master HEAD.  When I use it, `fi_pingpong` hangs/fails.  I'm afraid I don't have time to look at this at the moment -- it's both the Christmas holidays here in the US and also the annual Cisco shutdown.  I may not be able to look at the `-S` issue until early next year, which is why I'm trying to pack in tons of info for you here on my reply today, since it may be the last for a while.

-----

Two other options for getting performance numbers:

1. If you installed the Cisco drivers ISO from cisco.com, it also came with `/opt/cisco/usnic/bin/usd_pingpong`, which is quite similar in spirit to `fi_pingpong`, but is written to the (internal) API that the Libfabric `usnic` provider is written to.  So it'll be slightly different performance (but not a lot - for the performance-critical operations, the Libfabric `usnic` provider is actually a very thin wrapper around this internal API).  I mention this because the `-s` size operator _does_ work for `usd_pingpong` -- you might want to try playing with that.  That being said, I do recall that `fi_pingpong` and `usd_pingpong` have slightly different ping pong algorithms; i.e., it's expected that they return different measurements.  I confess that I don't remember off the top of my head what the difference is in the algorithms - sorry!  (I had a quick look at the code and nothing is jumping out at me immediately)

```
$ hwloc-bind socket:1.core:4 /opt/cisco/usnic/bin/usd_pingpong -s 8192 -h 192.168.2.1
open usnic_0 OK, IP=192.168.2.2
QP create OK, addr -h 192.168.2.2 -p 3333
sending params...
payload_size=8192, pkt_size=8234
posted 63 RX buffers, size=8256 (8192)
100000 pkts, 5.793 us / HRT
```

2. You can use any MPI ping pong application (e.g., the OSU MPI benchmarks) with the usNIC BTL (i.e., the usnic plugin in Open MPI).  It will return slightly higher latency because the MPI layer adds a little bit of overhead.  But MPI messaging: is reliable (i.e., does retransmission if necessary) and allows arbitrary-sized messages (not limited to MTU).  So you can explore more with that space.

**Comment by Keepmoving-ZXY** [comment]
ok, thank you for so much info, Merry  Christmas!

**Comment by shefty** [comment]
Assuming the original issue was resolved here.
