### ISSUE TITLE
Does openmpi's reduce operation support usnic btl?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [ofiwg/libfabric#5624]
OpenMPI suport reduce operation such as `allreduce` and so  on, and these days I am working on cisco usnic technology, and I have known that OpenMPI has usnic btl, so can OpenMPI use usnic btl to transfer bytes during reduce operation?

**Comment by jsquyres** [comment]
Yes.

**Comment by Keepmoving-ZXY** [comment]
This is my script:
```
mpirun -np 2 --host 10.0.28.2:2 \
  -map-by node -mca btl tcp,vader,self \
   -mca pml ^ucx \
  -mca btl_tcp_if_include rdma2 \
  -x HOROVOD_MPI_THREADS_DISABLE=1 \
  python ./tf_cnn_benchmarks.py --num_gpus=1 --batch_size=32 --model=vgg16 --variable_update=horovod --device=gpu
```
and during run, OpenMPI's `allreduce` operation is needed. When running, this script will case a segment fault, error message is:  
```
INFO:tensorflow:Running local_init_op.
I0210 23:53:25.700993 139875376367424 session_manager.py:491] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0210 23:53:25.717878 139875376367424 session_manager.py:493] Done running local_init_op.
INFO:tensorflow:Running local_init_op.
I0210 23:53:26.063787 139940961154880 session_manager.py:491] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0210 23:53:26.085994 139940961154880 session_manager.py:493] Done running local_init_op.
[gpu7:189975][bcol_basesmuma_component.c:408:knem_mem_reg] BCOL-BASESMUMA FAILED to prepare memory for KNEM: buf 0x7f2da1210700, len 1179648, errno 14
[gpu7:189975][:97:hmca_rcache_ucs_mem_reg_cb]  mem_reg failed in rcache bcol_uma_knem
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node gpu7 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
```
It seems that OpenMPI choose `knem` to run intra-node communication, do you know how to change my script to let OpenMPI use usnic to run intra-node communication?

**Comment by shefty** [comment]
usnic does not support intra-node communication

**Comment by Keepmoving-ZXY** [comment]
ok, I will try run OpenMPI in two servers.

**Comment by Keepmoving-ZXY** [comment]
This is my two server run scripts:
```
/usr/mpi/gcc/openmpi-4.0.2a1/bin/mpirun -np 2 --host 172.16.0.164:1:,172.16.0.165:1 \
	-x HOROVOD_MPI_THREADS_DISABLE=1 \
	-bind-to none -map-by slot \
	-mca btl tcp \
	-x UCX_NET_DEVICES=eth0 \
	-x UCX_TLS=tcp \
	python /home/zxy/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --num_gpus=1 --batch_size=256 --model=vgg16 --variable_update=horovod --device=gpu 
```
This is just a test that whether tcp btl is used or not,  but I find that OpenMPI is using ucx to communicate, do you know how to let OpenMPI use tcp btl?

**Comment by jsquyres** [comment]
We might want to move this question -- or at least future Open MPI questions -- to an Open MPI area.  Libfabric is one of the family of transports that Open MPI can use, but Open MPI is technically a different project with a different set of developers (although some of the developers overlap, like me).

A few points in no particular order:

1. @shefty is correct that usNIC does not support communication between peers on the same node.
2. When using usNIC, the `vader` BTL is typically used for shared memory communication (which may include KNEM support).  Yes, I know `vader` is a terrible name -- it does not immediately convey that `vader` == "shared memory".  Sorry about that.  ☹️ 
3. It's interesting that KNEM fails for you -- perhaps it has something to do with tensorflow's runtime...? 
 Or perhaps the GPU memory is not KNEM-able?  If this is an actual problem, it should be brought up on the Open MPI issue tracker.  Regardless, you can still use `vader` and exclude `knem` support.  Try:  `mpirun --mca btl_vader_single_copy_mechanism none ...`
4. As to why it's using UCX, Open MPI has multiple different "engines" that it can use for MPI communication (called PMLs).  Check out https://github.com/open-mpi/ompi/blob/d79fe7fe10251ba789d473339a0d0cbf4b347b9f/README#L652-L731 for details on this.  The short version is that Open MPI is likely choosing the UCX PML instead of the OB1 PML (usNIC is only supported in the OB1 PML).  You can do this to force the selection of the OB1 PML: `mpirun --mca pml ob1 ...`
5. You can specify multiple `--mca` clauses; e.g., `mpirun --mca btl_vader_single_copy_mechanism none --mca pml ob1 --mca btl tcp,vader,self ...`
6. When selecting BTLs (which are the underlying modules for the OB1 PML), you *must* also list the `self` BTL, which provides process-loopback communications.  The TCP BTL can do server-loopback communications (i.e., other processes on the same server), but not peer-loopback (i.e., communicating with the same process).

**Comment by Keepmoving-ZXY** [comment]
ok, thank you for explain, I will have a try  and if any problem I will ask at OpenMPI's github repo.

**Comment by Keepmoving-ZXY** [comment]
It seems that add `--mca pml ob1` can't disable ucx, and I have post this question to OpenMPI's github, see https://github.com/open-mpi/ompi/issues/7388
