### ISSUE TITLE
FI_INJECT support for device memory

### ISSUE THREAD

**Issue by iziemba** [ofiwg/libfabric#5861]
The following issue is to discuss how providers should support FI_INJECT with device memory. Currently, there are two different approaches to issuing an FI_INJECT operation: the inject interface  (e.g. fi_inject()) or a message interface with the FI_INJECT flag (e.g. fi_sendmsg(..., ..., FI_INJECT)). The issue with the inject interface and device memory is that there is no way to provide a provider the necessary information, such as an MR desc, for the provider to determine if the buffer is host or device memory. Seems like either the provider needs to rediscover the buffer type, or the inject interface cannot be supported. The message interface with the FI_INJECT flag does not have this issue since the message descriptor contains an MR desc field.

The following is one approach to the issue which can be addressed through documentation. If a provider supports FI_HMEM and requires FI_MR_HMEM, the inject interfaces cannot be used with device memory. All inject operations have to go through the message interface with the FI_INJECT flag set and a non-null MR desc. If a provider supports FI_HMEM and does not require FI_MR_HMEM, the inject interface and message interface with the FI_INJECT flag can be used with device memory. Note that both interfaces will come at the cost of the provider having to perform a query to determine buffer type.

Internally, the use of a bounce buffer would be left up to the provider.

There was talk about having a separate inject size for device memory. One concern here is that the provider would have to discover this size based on platform.

**Comment by shefty** [comment]
There was significant discussion on this topic in various forums (ofiwg, mail list, etc.).  If I'm remembering correctly, 
the ultimate decision was to leave the API as defined.

References:
https://github.com/ofiwg/libfabric/pull/6185
https://www.mail-archive.com/ofiwg@lists.openfabrics.org/msg01027.html

To summarize some of the factors:

- A provider can disable inject if it absolutely requires a desc to distinguish between host versus device memory.
- It seems unlikely that device memory will be used with inject operations in practice, particularly if transfers to/from devices will be large.  This makes the discussion mostly academic.  A provider could document that inject is only usable with host memory, even if the more general API allows both.
- Forcing registration for device buffers may be more costly than other options, such as copying the buffer.
- Inject calls usually involve using memcpy to copy the user's buffer into bounce buffers or a command queue.  memcpy could work with device memory if the kernel drivers and buffers have been mmapped with hmm support.
- A hooking provider could be used to intercept inject calls, identify the location of the buffer, and pass that data through to a lower-level provider.  For host memory, inject could map to the underlying inject call.  For device memory, the hooking provider could redirect the transfer to a non-inject call, with FI_INJECT flag set, and discard the completion.  Or it could copy the data into a host bounce buffer, which would be passed through to inject. Since inject sizes tend to be small, the host buffer used for this could be allocated on the stack.

Unless there is a real application need for using inject, I propose closing this issue.  When a need arises, a hooking provider as mentioned above could be implemented.

**Comment by iziemba** [comment]
I am ok with closing this ticket for now. I expect I will need to revisit this in the future.

**Comment by wzamazon** [comment]
> It seems unlikely that device memory will be used with inject operations in practice, 

Indeed it is unlikely that application use device memory with inject. However, fabtests will use inject as long as message size < max_inject_size.

See:

https://github.com/ofiwg/libfabric/blob/d8e6100a68b2526ef350f6f83550981f1a9c43e4/fabtests/benchmarks/benchmark_shared.c#L87

Is it OK to change fabtests such at inject is not used for device memory? (because application is unlikely to use inject with device memory)

**Comment by wzamazon** [comment]
We can do that (I think we will have to do that for now to avoid segfault).

However, that would mean that if an application want to use device memory, it will not be able to use inject on host memory. What if an application want to use both?

**Comment by aingerson** [comment]
Then it sounds like we need to take the second approach that Sean outlined in his earlier comment - "A provider could document that inject is only usable with host memory, even if the more general API allows both."
So in that case, yes, we should probably remove it from fabtests like you suggested :) 
I'm fine with that.

**Comment by shefty** [comment]
AFAICT, there is no issue to resolve here.  The inject calls are left as-is, and fabtests disables inject for hmem.
