### ISSUE TITLE
How to reliably determine a network interface associated with a domain

### ISSUE THREAD

**Issue by jbrosenz** [ofiwg/libfabric#5958]
I originally posted this issue [https://github.com/mercury-hpc/mercury/issues/349](https://github.com/mercury-hpc/mercury/issues/349) to the Mercury project.  They suggested I log the issue with the libfabric project.  

Here is an edited version of the original question.

In DAOS, when configuring a Mercury connection using the verbs provider, the API currently requires the specification of a network device and domain.  How does one reliably determine the specific network device associated with a fi_info record reported by libfabric? I need to know how to do this at least for verbs providers, but a general solution is desirable as well that would work with all providers.

I need to be able to tell an administrator tuples of [network device | domain] when specifying the verbs provider and do not have a solid way to do this. The initial approach was to use the domain associated with the libfabric fi_info scan to find related siblings in the hwloc system device tree. The domain and the related devices show up as siblings in the hwloc system device tree.  The sibling of the domain "mlx4_0" might be found to be "ib0". If there were **no other siblings**, we could **infer** that "ib0" is the network device name if "ib0" shows up on the list of network devices according to system command "ip a".  (the associated domain "mlx4_0" will not show up in the 'ip a' scan)

This approach is sufficient if there are precisely two siblings in the device tree. The complicating factor is that some fabric adapters support **more than one network device or port**. The device tree will show three or more siblings, such as "ib0, ib1, mlx4_0", or "ib0, ib1, enp2s0, mlx4_0" with a device for each port of the fabric adapter.  Given there will be one or more records from the fi_info scan associated with the domain "mlx4_0", how does one accurately determine that the related network device names for the verbs provider are "ib0" and "ib1" and not "enp2s0"?

Given that Mercury requires the domain and network device name when specifying the verbs provider, I am looking for a way to reliably obtain this information.

If the libfabric fi_info record had a string identifier for the specific network interface associated with a given fi_info record, that would solve my particular problem.  Bonus points for telling me the NUMA node that the network interface has affinity to.

If fi_info could be counted on to provide a network interface name with each record, that would remove all ambiguities for those fabric adapters that have more than one port (as is the case with the Cray/HPE system)

**Comment by krehm** [comment]
Here is some background on the Cray/HPE system Joel mentions...

In our test cluster each node has 2 sockets and 2 two-port FDR infiniband cards. We currently only cable one interface/port per card, so one interface is Linkup/Active with a configured IPoIB address, and the other is Down/Polling.  Theoretically in an H/A configuration one could have both interfaces in each card configured Linkup/Active with IPoIB addresses, but that is not the case here.

The domain names for the two cards are mlx4_0 and mlx4_1. Default interface names ib0 and ib1 are on mlx4_0, and interface names ib2 and ib3 are on mlx4_1.

Because different nodes in our cluster might connect to the switch using a different port in each card, we use udev rules to rename the active ports to names mlx40 and mlx41 so that the interface names are identical on every node even though the card ports might be different. The interface names mlx40 and mlx41 will appear on every node; the 2 unused ports could be any of the names ib0 through ib4, they could be different on each node.

Ideally, Joel's code would be able to determine which interface in each card/domain is the active port with an IPoIB address configured, and select that as the interface name to use with that card's domain name when configuring Mercury.  But fi_info output does not provide interface names, only domain names, so this becomes a difficult problem.

DAOS also needs to assign interface/domain pairs to PEs based upon the NUMA affinity of each PE that will be using infiniband.  By including NUMA affinity in the fi_info output, this would be easy to determine.

**Comment by jbrosenz** [comment]
Ping to the libfabric team ...

**Comment by shefty** [comment]
fi_info provides NIC attributes as part of its output.  See

https://ofiwg.github.io/libfabric/master/man/fi_nic.3.html

for details on data that is available.  NUMA information is accessible using the pci attributes.

**Comment by krehm** [comment]
In our config, each host contains a two-port IB card.  Interfaces ib0 and mlx40 are on card (domain) mlx4_0, and interfaces mlx41 and ib3 are on domain mlx4_1.   Interfaces mlx40 and mlx41 have cables and are configured for IPoIB, ib0 and ib3 are not.   

The output from "fi_info -p 'verbs;ofi_rxm' -v" does not identify the interface names mlx40 and mlx41.  The fi_domain_attr sections of the output identify the domains mlx4_0 and mlx4_1, but there is no mention which interface to use for each domain.

If I remove the -p option, the sockets provider mentions the mlx40 and mlx41 interface names, but the verbs provider does not.


3: ib0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 65520 qdisc mq state DOWN group default qlen 256
    link/infiniband a0:00:02:20:fe:80:00:00:00:00:00:00:e4:1d:2d:03:00:7b:61:21 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
4: mlx40: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    link/infiniband a0:00:03:00:fe:80:00:00:00:00:00:00:e4:1d:2d:03:00:7b:61:22 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
    inet 10.0.0.38/16 brd 10.0.255.255 scope global noprefixroute mlx40
       valid_lft forever preferred_lft forever
5: mlx41: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2044 qdisc mq state UP group default qlen 256
    link/infiniband a0:00:02:20:fe:80:00:00:00:00:00:00:e4:1d:2d:03:00:12:5e:e1 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
    inet 10.0.1.38/16 brd 10.0.255.255 scope global noprefixroute mlx41
       valid_lft forever preferred_lft forever
6: ib3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 65520 qdisc mq state DOWN group default qlen 256
    link/infiniband a0:00:03:00:fe:80:00:00:00:00:00:00:e4:1d:2d:03:00:12:5e:e2 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff

**Comment by krehm** [comment]
Here's a clip from the "fi_info -p 'verbs;ofi_rxm' -v" output, the nic_fid field is always NULL.  In the "name" field, that is the domain, not the interface.

    fi_domain_attr:
        domain: 0x0
        name: mlx4_0
        threading: FI_THREAD_SAFE
        control_progress: FI_PROGRESS_AUTO
        data_progress: FI_PROGRESS_MANUAL
        resource_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: [ FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY ]
        mr_key_size: 4
        cq_data_size: 4
        cq_cnt: 65536
        ep_cnt: 32768
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
        max_ep_tx_ctx: 1
        max_ep_rx_ctx: 1
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 0
        cntr_cnt: 0
        mr_iov_limit: 1
    caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM ]
    mode: [  ]
        auth_key_size: 0
        max_err_data: 0
        mr_cnt: 0
    fi_fabric_attr:
        name: IB-0xfe80000000000000
        prov_name: verbs;ofi_rxm
        prov_version: 1.0
        api_version: 1.7
    nic_fid: (nil)

**Comment by jbrosenz** [comment]
This is still an open issue.  How do we get this resolved?

**Comment by shefty** [comment]
The verbs provider will report nic attributes in newer versions of libfabric.  E.g.
```
fi_info:
    caps: [ FI_MSG, FI_RMA, FI_TAGGED, FI_COLLECTIVE, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_LOCAL_COMM, FI_REMOTE_COMM ]
    mode: [ FI_BUFFERED_RECV ]
    addr_format: FI_SOCKADDR_IN6
    src_addrlen: 28
    dest_addrlen: 0
    src_addr: fi_sockaddr_in6://[fe80::202:c903:35:3882]:0
...
    fid_nic:
        fi_device_attr:
            name: mlx4_0
            device_id: 0x1003
            device_version: 0
            vendor_id: 0x02c9
            driver: (null)
            firmware: 2.10.000
        fi_bus_attr:
            fi_bus_type: FI_BUS_UNKNOWN
        fi_link_attr:
            address: (null)
            mtu: 4096
            speed: 56000000000
            state: FI_LINK_UP
            network_type: InfiniBand
```
The domain is associated with that RDMA NIC.  More generally, there are no guarantees that a domain *will* be associated directly with a NIC.  A domain is not necessarily tied directly to a hardware construct.  For some providers a domain may span multiple NICs (e.g. multi-rail) or not have one at all (shared memory).

Traffic through the verbs provider does not go through netdev interfaces.  For convenience a mapping is made so that IP addresses may be used for communication setup, but IP addressing is not required.  There is not a 1:1 mapping between a verbs domain and a netdev name.  With the verbs provider, domains are associated with an RDMA NIC.

You can use the environment variable FI_VERBS_DEVICE_NAME to restrict fi_getinfo output to a specific RDMA device.   FI_VERBS_IFACE can also be used to filter output to addresses associated with a specific netdev name.

If a returned fi_info includes an IP address, it could probably be used in conjunction with getifaddrs()/getaddrinfo() to associate it with a netdev interface.  But that should be a property of the address being selected for use and it not a relationship between the domain.

**Comment by shefty** [comment]
I believe this has been resolved with newer versions reporting the NIC attributes.
