### ISSUE TITLE
prov/shm: Incorrect use of spinlock in smr_create

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#6050]
smr_create has the following code:
```
	pthread_mutex_unlock(&ep_list_lock);

	*smr = mapped_addr;
	fastlock_init(&(*smr)->lock);
	fastlock_acquire(&(*smr)->lock);

	(*smr)->map = map;
```
The acquiring of a spinlock immediately after it's been initialized can't provide any protection.  If some other thread can acquire the spinlock, it can do so before it's been initialized.  Removing the spinlock is an option, but if there's an assumption that it's providing some sort of serialization, then that serialization needs to be reworked.

**Comment by aingerson** [comment]
@shefty This can be removed I think as long as we move the smr->pid initialization to the end of the the smr_create. This was added to prevent a peer from mapping to the region without resources being initialized. But a check was added to make sure the pid was initialized instead so that can act as a safeguard against that -https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_shm.c#L300

So we can remove the lock and rely on the pid as marking initialization as long as we can assume the shm will initialize to 0 when created. Is that a correct assumption?

**Comment by shefty** [comment]
I'm not following the problem yet.  Can a provider be fully initialized prior to exposing any sort of addressing that a peer can use to locate it?

**Comment by aingerson** [comment]
The problem is that the name of the shm region is the ep name which can be changed by the application via setname so we create the region when enabling the EP. If another assumption is that no peers will try to send to peer until it has been enabled then this is a non-problem. This is guarding against the case where a peer tries to send to another peer before it has been enabled.

**Comment by aingerson** [comment]
(before it has returned from enabling, that is)

**Comment by shefty** [comment]
Returning back to this problem.  These are the 2 lines in question:
```
	fastlock_init(&(*smr)->lock);
	fastlock_acquire(&(*smr)->lock);
```

What other thread is trying to acquire smr->lock?

**Comment by aingerson** [comment]
The protection here is not against a thread but another peer.
So back to my question - is it a correct assumption that no peers will try to send to a peer before it has been enabled? If so, this can be removed. If not, then we could move to the PID setting as a marker of full initialization.

**Comment by shefty** [comment]
Let's agree that the current use of locking doesn't work, and some other synchronization method is being employed (or is needed).  :)

A peer can start walking through the shared region after ftruncate has been called to set the region size.  On this note, it may be best if O_TRUNC were passed to shm_open. ftruncate initializes the memory to 0, so if you're using the pid to determine when the region has been initialized, I would just set that at the end, after everything else has been initialized.

**Comment by aingerson** [comment]
Agreed :)

I'm into the just setting the PID at the end. Based on the documentation of O_TRUNC though, it looks like that only truncates to 0 if the region already exists. It doesn't say anything about setting to 0 or what it does if the region doesn't exist and was just created:
```
       O_TRUNC
              If the file already exists and is a regular file and the
              access mode allows writing (i.e., is O_RDWR or O_WRONLY) it
              will be truncated to length 0.  If the file is a FIFO or ter‐
              minal device file, the O_TRUNC flag is ignored.  Otherwise,
              the effect of O_TRUNC is unspecified.
```

**Comment by shefty** [comment]
Using O_TRUNC with shm_open was to ensure that if there was an existing file by that name, that we killed it upon opening it.  Yes, this should be unlikely to occur, since we're expecting to create a new file.  Though if the file exists, then a peer could already have opened it and read data from the old file...

The ftruncate call will set the new file to 0.

**Comment by aingerson** [comment]
Hmm yeah I haven't thought about that case... don't know how we want to handle that...
