### ISSUE TITLE
prov/tcp: fi_cq_sread() returns EAGAIN immediately, ignoring timeout

### ISSUE THREAD

**Issue by rclaus2** [ofiwg/libfabric#6068]
The code I developed usually uses libfabric with the verbs provider on RHEL 7 Linux to exchange messages between nodes.  In some instances where it must run, Infiniband hardware is not installed, so it falls back to using Ethernet.  Most of the data is passed around using RDMA writes, with the other side polling on fi_cq_read() for a CQ entry containing immediate data.  I used this same idea at start up to exchange a few  configuration parameters using only the CQ immediate word (no RDMA, no MR), but now with fi_cq_sread() and a timeout value.  
It has been working fine until recently, when we moved from version 1.7.1 to 1.10.1.  At that point, the start-up phase fails with Ethernet, although not with IB.  Only one or two CQ entries are received from fi_cq_sread(), with subsequent calls receiving EAGAIN well before the timeout period has expired.
The provider selected by fi_getinfo() for use with Ethernet was 'sockets' in the earlier releases, but comes up 'tcp' with 1.10.1.  When I set hints->fabric_attr->prov_name to 'sockets', everything works again as before.  However, since the 'sockets' provider is deprecated, I want to move to using 'tcp'.
The attached modified fabtests/functional/cq_data.c shows the issue.  I've also attached client and server log files for each of the verbs, sockets and tcp provider instances.  
In preparing the modified cq_data.c, I noticed that ft_wait_for_comp() in fabtests/common/shared.c calls fi_cq_sread() with a timeout value in a while loop that retries the call on EAGAIN.  Following this example allows my code to work again, so perhaps there's no issue here other than to note that 'tcp' behaves differently from 'sockets'.  Is that the appropriate conclusion or should this loop be considered redundant?  I think there is no way to distinguish EAGAIN from meaning timed out vs another reason, so I'd need to add the timeout machinery to this loop to avoid automatically retrying when EAGAIN really does mean timed out.  Is that the right thing to do?

Thanks to all the developers for producing and maintaining libfabric.  While I've had my moments of frustration with it (as with everything), it has certainly made my life easier than if I had had to roll my own.

[cq_data.c.txt](https://github.com/ofiwg/libfabric/files/4906053/cq_data.c.txt)
[verbs_server.txt](https://github.com/ofiwg/libfabric/files/4906054/verbs_server.txt)
[verbs_client.txt](https://github.com/ofiwg/libfabric/files/4906055/verbs_client.txt)
[sockets_server.txt](https://github.com/ofiwg/libfabric/files/4906056/sockets_server.txt)
[tcp_server.txt](https://github.com/ofiwg/libfabric/files/4906057/tcp_server.txt)
[sockets_client.txt](https://github.com/ofiwg/libfabric/files/4906058/sockets_client.txt)
[tcp_client.txt](https://github.com/ofiwg/libfabric/files/4906059/tcp_client.txt)

**Comment by shefty** [comment]
months later...

Have you tried using a later version of libfabric, and if so, do you still see this problem?  You should not need to mimic the fabtests code, which is structured to handle different completion calls.  The sread call itself should block for the timeout, and itself loops.  There were fixes to the timeout logic, but I think those should have been in the v1.10.1 release.

Note that it is possible for a cq wait call to return, followed by the application finding the cq empty.  This can occur because the completion may be consumed by the provider internally.  For example, the completion may be for a receive carrying credits or flow control data, and the completion will not be read until the application calls cq read.

If you're using connected (msg) endpoints, this shouldn't be the case with the tcp provider.  But it's worth mentioning that the app should be prepared for it to occur.
