### ISSUE TITLE
Segmentation fault with Libfabric >=1.9.1 and verbs;ofi_rxm

### ISSUE THREAD

**Issue by mkre** [ofiwg/libfabric#6200]
Hi,

We are seeing a segfault with Open MPI 4.0.3 and Libfabric >=1.9.1 (tried 1.9.1, 1.10.0, 1.10.1, 1.11.0) when running on a Mellanox ConnectX-6 system (MLNX_OFED 4.6) with the `verbs;ofi_rxm` providers. Libfabric 1.9.0 is working fine. The only thing we are changing is the Libfabric version available at run time (i.e., we are not recompiling anything). The gdb stacktrace points to a function in our application where we are doing some simple non-blocking communication, and valgrind reports an invalid write in this function. The fact that it only happens with specific Libfabric versions might give some evidence that it is an issue with Libfabric, rather than our application.

I will dig a bit deeper to find the root cause of this, but while doing this, I wanted to ask this question: Are you aware of anything that has changed between 1.9.0 and 1.9.1 which might cause this issue?

Please let me know if you need further information.

Thanks,
Moritz

**Comment by shefty** [comment]
I will look at the changes between 1.9.0 and 1.9.1 and report back if anything looks suspicious.

**Comment by shefty** [comment]
There are a couple of changes between 1.9.0 and 1.9.1 that I would look at first.  There were fixes to multi-recv handling and the memory registration caching.  Both had a relatively wide impact.  You can try disabling the MR cache to see if the problem is related.  The multi-recv fixes were centered on unexpected message processing, but the changes ripple into other areas.  Another thing to try is running with rxm;tcp.  That may help determine if the problems are likely in rxm, versus verbs.

**Comment by mkre** [comment]
Setting `FI_VERBS_MR_CACHE_ENABLE=0` leads to the same segfault. Setting `FI_PROVIDER=tcp,ofi_rxm` does not lead to a segfault. So the problem seems to be in the `verbs` provider. Anything else I could try out?

**Comment by mkre** [comment]
Hi @shefty,

I looked a bit deeper into the available environment variables, and it turns out that setting `FI_MR_CACHE_MONITOR=disabled` avoids the segmentation fault. Seems like I just set the wrong variable in my previous experiment.

**Comment by shefty** [comment]
It's been confirmed that the MR cache has issues and must be disabled.  The upcoming 1.11.1 and 1.12.0 releases will hopefully fix the issue.
