### ISSUE TITLE
sockets provider: stack corruption on private data exchange

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#632]
In `sock_msg_ep_listener_thread` and `sock_pep_listener_thread`, the user private data is copied onto the event structure on the stack.  However, the event structure does not include space for the private data, so copying the private data corrupts the stack.

This should be fixed by using calloc or alloca (or just allocating a big enough buffer on the stack) to allocate sufficient space for the user private data.

**Comment by shefty** [comment]
The use of alloca would seem to be the best choice given the current structure of the code.  Looking at the functions referenced by this issue, the conn_response buffer is also leaked on each iteration of the while loop.  To fix that, I would look at changing the definition of struct sock_conn_response to allocate SOCK_EP_MAX_CM_DATA_SZ bytes as part of the structure.  That should clean up the code.

**Comment by shefty** [comment]
I tried to fix this for rc2, but the changes are more significant than I want to push in immediately before a release.  These are the issues that I see in sock_msg_ep_listener_thread:

1. The cm_entry structure is overrun as Patrick mentions.  That structure should be dynamically allocated, or a new structure should be defined (e.g. sock_eq_cm_entry) that includes space for up to SOCK_EP_MAX_CM_DATA_SZ bytes of user data.
2. The conn_response is allocated within the while loop and not freed.  The allocation is only needed once, outside of the loop, which would also handle the memory leak.
3. user_data_sz can be calculated directly outside of the switch statement, rather than set to 0, then overwritten.  This is just a slight inefficiency and code cleanup.
4. The SOCK_CONN_REJECT case statement references cm_entry incorrectly when copying the user data.  It should reference cm_err_entry instead.
5. Note that the reporting of user data is difference between a normal event and an error event.  In the case of an error event, data is accessible through the err_data pointer.  In the case of a normal event, the data is included directly as part of the event structure (i.e. data[]).
6. The socket provider EQ support for error entries appears to be wrong.  For example, the call to sock_eq_report_event(... FI_ECONNREFUSED..) reports 'fi_connrefused' as the event type.  The event type and error status values are separate, and may overlap.  The status values FI_ENOENT and FI_EIO have the same values as event types FI_CONNECTED and FI_AV_COMPLETE, for instance.  And data associated with the different types of events needs to be handled correctly.  This likely requires some modifications to the EQ code.
