### ISSUE TITLE
Detect clwb, clflushopt, clflush errors

### ISSUE THREAD

**Issue by zzjianhui** [ofiwg/libfabric#6391]
In function `ofi_pmem_init`, libfabric judges whether CLWB, CLFLUSHOPT, CLFLUSH are available. But OFI_CLWB_REG is set to 2, OFI_CLWB_BIT is set to 1<<24. According to the Intel manual, the location is Reserved. The other two tests are also wrong. 

```c
void ofi_pmem_init(void)
{
	if (ofi_cpu_supports(0x7, OFI_CLWB_REG, OFI_CLWB_BIT)) {
		ofi_pmem_commit = pmem_commit_clwb;
	} else if (ofi_cpu_supports(0x7, OFI_CLFLUSHOPT_REG, OFI_CLFLUSHOPT_BIT)) {
		ofi_pmem_commit = pmem_commit_clflushopt;
	} else if (ofi_cpu_supports(0x1, OFI_CLFLUSH_REG, OFI_CLFLUSH_BIT)) {
		ofi_pmem_commit = pmem_commit_clflush;
	}

	if (ofi_pmem_commit)
		OFI_RMA_PMEM = FI_RMA_PMEM;
}
```

**Comment by shefty** [comment]
For reference, I believe the original code was derived from here:

https://github.com/shefty/nvml/blob/master/src/libpmem/cpu.c

which was a clone of the original pmdk.  The most up to date version of that code should be this:

https://github.com/pmem/pmdk/blob/master/src/libpmem2/x86_64/cpu.c

Based on the original source, OFI_CLWB_REG is incorrect (should have been 1 instead of 2).  But based on the latest source, I believe these are the values that we want:

```
OFI_CLWB_REG = 1     /* change */
OFI_CLWB_BIT = (1 << 24)

OFI_CLFLUSHOPT_REG = 1
OFI_CLFLUSHOPT_BIT = (1 << 23)  /* change */

OFI_CLFLUSH_REG = 3 
OFI_CLFLUSH_BIT = (1 << 19)  /* change */
```
I think ofi_pmem_init() is okay, only the defines are incorrect.

**Comment by shefty** [comment]
Please see PR #6400 for updates.
