### ISSUE TITLE
daemon logs / syslog

### ISSUE THREAD

**Issue by aakefbs** [ofiwg/libfabric#6525]
Right now fi_log() only allows to print to stderr, but that will actually suppress all logs if libfabric is part of a daemon that prefers to log via syslog. 

Any objections against a libfabric fi_log_init() function, that allows to set a log function pointer? If that pointer is set logs would be printed via that function, otherwise as before to stderr.

Thanks,
Bernd

**Comment by shefty** [comment]
I have no objection, and I think the ability to customize the logging would be welcome.  There was a prior request for something like this, though the proposal was too restrictive.

We may want the ability to replace fi_log() and fi_log_enabled() with custom calls.

An external app won't have access to the private data stored with each fi_provider, but I don't think that will matter for a custom fi_log_enabled() call.

**Comment by sydidelot** [comment]
@aakefbs @shefty Have you had a chance to work on this feature?
If not, I will probably work on a patch next week (I need that feature very soon).

**Comment by shefty** [comment]
I have not.  This is low on my priorities.  I haven't given this much more thought, but would look at using the import fid option to override the logging calls.  Shouldn't be that much work.  (Yeah, sure.  It'll be easy they say.)

**Comment by sydidelot** [comment]
@shefty I recently looked at the import fid option. I think I can do it, but I would need some guidance.
If I understand the code correctly, `fi_import_fid()` binds 2 FID objects together. 
We can create a new FID class for the log subsystem (FI_CLASS_LOG?) but to what FID class should it bind to? I am a bit confused, sorry.

**Comment by aakefbs** [comment]
Sorry I didn't any minute for logging yet. I had created an IME jira task for it - it assigned away from me and so far this did not have priority for anyone here.

Anyway so complicated and not just an optional function pointer in log.c and then fi_log() would do

if (external_log_func)
  external_log_func(level, buf);
else
  fprintf(stderr, "%s", buf);
  
Not sure about red, but for ime that would be sufficient.

**Comment by shefty** [comment]
WARNING: I haven't thought through this completely.  :)

Start by looking at fi_open() in src/fabric.c and the mr_cache mechanism.  The mr_cache piece is at the end of prov/util/src/util_mr_cache.c.  This is what I think is needed:

1. Make up a new name for our fid object, maybe just "logging" (not sure about name).
2. Add a new call, ofi_open_log(), similar to ofi_open_mr_cache().
3. Have fi_open("logging", ...) call ofi_open_log().
4. ofi_open_log() will return the fid that we'll import against.

Unlike the mr_cache, it may make more sense if fi_open("logging") returned a reference to a single global object which can: only be opened once, and only uses the last import.  Conceptually, something like this might work:

```
static int ofi_log_enabled(...)
{
    current contents of fi_log_enabled
}

static int ofi_log_ready(...)
{
    current contents of fi_log_ready
}

static void ofi_log(...)
{
    current contents of fi_log
}

static struct fi_log_ops log_ops = {
    .size = sizeof(struct fi_log_ops),
    .enabled = ofi_log_enabled,
    ....
};

static struct fid_logging log_fid = {
    .fid = ...
    .log_ops = log_ops,
};

int DEFAULT_SYMVER_PRE(fi_log_enabled)(...)
{
    return log_fid.log_ops.enabled(...)
}

int ofi_log_open(...)
{
    return log_fid
}

int ofi_import_logging(...)
{
    change log_fid.log_ops
}

static int ofi_log_close(...)
{
    reset log_fid.log_ops
}
```

There's a log of details missing, synchronization is needed, etc.  But I think something close to this would work.

**Comment by shefty** [comment]
@aakefbs - Do you need the level, or would just having the buf be sufficient, so you can redirect the output to wherever?  And if the latter, would replacing stderr with a logfd also work?  Are you needing to modify the logging or just redirect it?

**Comment by aakefbs** [comment]
We want to write the buffer with syslog - file handle would not work, afaik. Good would be to add an IME daemon or mount point prefix. So it would be good get the log buf and then to handle logging of it on our own.

**Comment by aakefbs** [comment]
The level is not strictly needed, though. It just might  be useful.

**Comment by shefty** [comment]
If you only intercept at the fi_log() call, then a filter has already been applied via fi_log_ready() or fi_log_enabled().  So the most general solution would be to intercept all those calls.  Setting a function pointer to non-null would fix that function's API signature.  That shouldn't be a big deal, but any change requires exporting another pointer.  We'd also have to hope that two users don't both try changing the pointer, because they wouldn't have any way to know which one ended up winning.  With an API call, we could fail one of them.

**Comment by aakefbs** [comment]
I guess I wouldn't have an issue with fi_log_ready() or fi_log_enabled() not being intercepted. Regarding two users changing the pointer - that is just a `return compare_and_swap(variable, NULL, value)` from the function that sets the ptr? I see the issues, though of the function-ptr API would need changes.

**Comment by shefty** [comment]
Okay, I'm leaning towards going with the minimal impact here.  I like the idea of exporting a simple function to replace the fprintf (log_out, log_print, log_redirect ?), with the simpler signature of log_whatever(const char *buf).  buf should be treated as an opaque string (app shouldn't try to parse as the format may change).  And log_whatever should be set using some atomic.

Anything more than this should probably be more robust, such at all the parameters passed to fi_log would also be passed to some future intercepting call, with versioning handled by the library, etc.

**Comment by aakefbs** [comment]
Let's see if @sydidelot agrees with the simple approach as I'm not sure what are the red needs.

**Comment by sydidelot** [comment]
RED allows for dynamically changing the log levels: I would like to have the ability to override `fi_log_enabled()` so that the application can select if the log message must be printed or not, based on the level. 
I'm fine with `log_whatever(const char *buf)` where the buffer should be treated as an opaque string.

I have a couple of comments/questions regarding the above discussion:
- If I understand the discussion correctly, we want to export function pointers that the end-user can override (with a CAS). We do _not_ want to define API calls, right?  
If so, do we want these new symbols to be exported in a header file, or do we expect the library to import them using `extern`? Furthermore, do we want to version these new symbols in the ABI with `symver`?
- Exporting `fi_log_enabled()` would require to expose the definition of log levels (`enum fi_log_level`) to a header file, which could then be included into the application.

**Comment by shefty** [comment]
Whatever we do here will need to be documented and maintained as part of the stable ABI.  Note that the definitions in include/rdma/provider/fi_log.h are exported by libfabric.  So enum fi_log_level, fi_log(), etc. definitions are already available to an application today.  We just don't anticipate an application doing anything with them.

If you need to intercept fi_log_enabled(), we should go ahead and allow intercepting fi_log_ready().  We were talking about exporting function pointers for this, but there's no real benefit to exporting function pointers versus new API calls that do the same thing.  Only with an API call we can ensure proper serialization rather than relying on the app.  And this brings me back to using my proposal above: fi_open(), fi_import_fid()...

To simplify things for the app, we can define:
```
static inline int fi_import(uint32_t version, const char *name, void *attr, size_t attr_len,
   uint64_t flags, struct fid *fid, void *context)
{
    struct fid *open_fid;
    int ret;

    ret = fi_open(version, name, attr, attr_len, flags, &open_fid, context);
    fi_import_fid(open_fid, fid, flags);
    fi_close(open_fid);
}

static inline int fi_import_log(uint32_t version, uint64_t flags, struct fid_log *log_fid)
{
    return fi_import(version, "logging", NULL, 0, flags, &log_fid->fid, log_fid);
}
```

The fid_log would contain the function pointers set by the app.  The app just calls fi_import_log to add those to libfabric, and fi_close(log_fid) later to remove them.

**Comment by sydidelot** [comment]
@shefty thanks for the comprehensive explanation of the interface! 
I managed to cook a patch, which is available here: https://github.com/ofiwg/libfabric/pull/7653
