### ISSUE TITLE
Define device allocation type fields in fi_mr_attr

### ISSUE THREAD

**Issue by aingerson** [ofiwg/libfabric#6526]
To extend for use with FI_MR_HMEM, fi_mr_attr was extended to include the interface used to allocate and manage the memory (ie FI_HMEM_CUDA, FI_HMEM_ZE) as well as interface-specific fields.
Each of these interface types is defined to include memory allocated in a variety of different ways. For example, for CUDA:
"Uses Nvidia CUDA interfaces such as cuMemAlloc, cuMemAllocHost, cuMemAllocManaged, cuMemFree, cudaMalloc, cudaFree."
However for both CUDA and L0 (maybe others), IPC is not supported for all types of allocations. See [here for CUDA](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#interprocess-communication) and [here for ZE](https://spec.oneapi.com/level-zero/latest/core/api.html#zememgetipchandle).

fi_mr_attr needs to include what type of memory/allocation the buffer is as well so that the provider can know what protocols, like IPC, can or cannot be used.

Possible solution - add allocation types to fi_hmem_iface

**Comment by shefty** [comment]
If the application knows this, it makes sense to pass that data through.  But does middleware know what call was used for the allocation?  Can it get this through the buffer attributes?

**Comment by aingerson** [comment]
Both CUDA and L0 have calls to find this out so it's possible for the middleware to do this discovery if they don't have the information already to pass through. The same call that the hooking provider will need to do to register the memory will have the type of memory as well to use in the registration.

**Comment by shefty** [comment]
Does this data come 'for free' as part of querying if a buffer is a GPU or host buffer?  Or is it an extra call?

**Comment by aingerson** [comment]
Fo free!

**Comment by shefty** [comment]
An 'easy' solution is to extend enum fi_hmem_iface with device allocation details.  For example:
```
enum fi_hmem_iface {
    FI_HMEM_SYSTEM = 0,
    FI_HMEM_CUDA,
    FI_HMEM_ROCR,
    FI_HMEM_ZE,
    FI_HMEM_CUDA_ALLOC,
    FI_HMEM_CUDA_ALLOCHOST,
```
This may add a bunch of enum values.  However, I'm not sure if additional details would be necessary or not, based on which call was used and how it was invoked.

As an alternative, rather than indicate which call was used, we could pass in the necessary information more directly.  Using a flag, rather than extending the enum seems to make more sense here:
```
#define FI_MR_HMEM_IPC_BUFFER (1ULL << 59)
#define FI_MR_HMEM_NONIPC_BUFFER (1ULL << 58)
```
These flags would be passed into fi_mr_regattr.  I don't like have 2 flags, but I think we need both in order to indicate that the IPC'ish is unknown to the caller.

**Comment by iziemba** [comment]
In addition to whether a buffer supports IPC, I think we may need to distinguish between managed (cudaMallocManaged) and non-managed (cudaMalloc). With MOFED, RDMA to CUDA managed buffers cannot be supported due to the following:

_CUDA Unified Memory is not explicitly supported in combination with GPUDirect RDMA. While the page table returned by nvidia_p2p_get_pages() is valid for managed memory buffers and provides a mapping of GPU memory at any given moment in time, the GPU device copy of that memory may be incoherent with the writable copy of the page which is not on the GPU. Using the page table in this circumstance may result in accessing stale data, or data loss, because of a DMA write access to device memory that is subsequently overwritten by the Unified Memory run-time. cuPointerGetAttribute() may be used to determine if an address is being managed by the Unified Memory runtime._

https://docs.nvidia.com/cuda/gpudirect-rdma/index.html

**Comment by shefty** [comment]
@iziemba comment suggests that the enum extension suggested above would work for both the IPC and GPUDirect RDMA cases.  Or we need to define more flags.  Enum is looking like a better approach, and might be easier for the user.

**Comment by aingerson** [comment]
As we add interfaces and types of memory, there are going to be a lot of combinations and I think it might make it hard to code for specific protocols. For example in shm to figure out if I can do IPC then I have to do 
`if (mem_type == FI_HMEM_CUDA_DEVICE || mem_type == FI_HMEM_ZE_DEVICE...)` 
and maybe more depending on the more interfaces we add. I don't love having two fields and adding a flag but I think it does simplify it a bit since CUDA's "managed" memory and ZE's "shared" memory are both just their own way of saying unified memory. And each interface (as far as I know) has its own version of host, device, and unified memory with similar restrictions. CUDA and L0 both can only do IPC with their specifically device allocations because of migration of memory so they can't support their unified version (managed or shared).
So, implementation wise for the providers, it might be easier to add 3 flags
```
FI_HMEM_HOST
FI_HMEM_DEVICE
FI_HMEM_UNIFIED
```
that can apply the same to all interfaces.
I don't love the flags not only because of the extra field but also because it renames/makes connections between the interfaces' APIs that I don't think necessarily can be true.
Just something to consider/think about.

**Comment by shefty** [comment]
Why would anyone use a device API to allocate host memory?  I don't understand why those calls exist at all.

Looking at the CUDA documentation, there's a ridiculous number of allocation calls.  Sigh...

What is 'managed' memory actually mean?  That the allocation uses a shared virtual address space?

And are we getting into an area where a restriction today may not be a restriction tomorrow?
