### ISSUE TITLE
does read-after-read ordering matter?

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#653]
There's currently a flag to define read-after-read ordering for both messages and RMA.

Does this matter?

i.e. is there ever going to be a provider that can implement reads that are out of order?

A shared memory provider that implements RMA  ... you *could* potentially see out of order reads depending on the architecture.

Similarly, there could be a fabric provider could do better if read-after-read ordering was relaxed by having more reads outstanding. Applications could use read-after-read ordering to poll on remote memory? I'm making up the following example...

```
val1 = read remote byte X
val2 = read remote byte X+1
while (val2 != MAGIC) {}
// use val1
```

If we decide to keep read-after-read as an ordering flag, then we need a max_order_rar_size in struct fi_ep_attr.

While we are at it, can we rename 'max_order_X_size' to 'max_rma_X_size', where X=rar, raw, waw, war? This might make it clearer.

**Comment by shefty** [comment]
Note that unlike the other flags, the example given is specifying ordering at the initiator, rather than the target.  Adding initiator ordering to the discussion has repercussions on other ordering flags, such as WAR.  Does WAR mean that a write to the target memory comes after the read, or does it now mean that the write is not initiated until the remote memory has been read and the local buffers updated?

I think this could get messy quickly.  If possible, I'd like to associate local memory updates with completion ordering.  And I don't believe that's the case now.

**Comment by sayantansur** [comment]
OK. I checked the MPI requirements. They are requiring order at the target, not at the initiator.

So, the example given is not a valid MPI program. I will double check with MPI folks and get back on this.

**Comment by sayantansur** [comment]
At least @jeffhammond is in agreement that MPI accumulate ordering is at target only. If we are defining ordering only for target side, then I think we are fine dropping RAR.

**Comment by jeffhammond** [comment]
@jeffhammond does not know if the MPI RMA WG meant to say anything about origin-side ordering of round-trip RMA operations, e.g. fetch_and_op.  I am in agreement that target-side RAR is not a data hazard.

**Comment by shefty** [comment]
I plan on keeping the existing flag defined for possible future use, even if it will not apply to the current attributes, which are target based.
