### ISSUE TITLE
Ordering data placement between different messages to non-overlapping memory locations

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#654]
Currently we define data ordering as follows:

> Data ordering refers to the access of target memory by subsequent operations.  When back to back RMA read or write operations access the same registered memory location, data ordering indicates whether  the  second  operation  reads  or
       writes  the  target  memory  after the first operation has completed.  Because RMA ordering applies between two operations, and not within a single data transfer, ordering is defined per byte-addressable memory location.  I.e.  ordering
       specifies whether location X is accessed by the second operation after the first operation.  Nothing is implied about the completion of the first operation before the second operation is initiated. 

That means if there were two different messages that wrote two different memory locations, then there is no ordering between them.

If an application required ordering between the messages, they would have to use some kind of synchronization scheme. This could have additional costs. If the fabric exposed placement ordering up to the application, then the synchronization could be avoided. This could make sense where the writes are very small and maybe to the same page and the message ordering is FI_ORDER_WAW? i.e. the operations are inherently ordered. 

Certain (probably non-standard) SHMEM apps rely on memory polling. This could also be useful in implementing collectives and funky synchronization schemes.

**Comment by shefty** [comment]
I will submit a patch that defines FI_ORDER_DATA.  When set, the ordering of data is guaranteed if message ordering is also guaranteed.  This combined with WAW ordering would provide for data placement.  Though, this guarantee would be for any write, regardless of write location, rather than being restricted to writing to the same page.

If this is too gross of a requirement, a different ordering flag could be defined, or this flag could be restricted based on the max_order_xxx_size fields.  E.g. ORDER_DATA could be defined such that it only applies if the messages are ordered and the transfers are smaller than max_order_waw_size.
