### ISSUE TITLE
What is the meaning of "usec/xfer" and "Mxfers/sec" ?

### ISSUE THREAD

**Issue by zarzen** [ofiwg/libfabric#6796]
Hi there,
I am using `fi_rdm_tagged_bw` to benchmark the network bandwidth. I would like to know two other reported scores, "usec/xfer" and "Mxfers/sec". I checked the document of fabtests, but didn't find explanation for them. 
Could you detail the meaning of these two fields?

**Comment by shefty** [comment]
Average micrseconds per transfer and millions of transfers per second.  All benchmarks report these value, but often only one makes sense for a given test.  In this test, millions of transfers per second is the useful metric.  microseconds per transfer is more useful for latency tests, rather than the back to back transfers done by a bandwidth test.
