### ISSUE TITLE
No easy way to unblock a thread in cq sread

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#697]
It's a pain for applications to use cq sread, since the thread can remained blocked forever.  The only current solution is for apps to get the underlying wait object and use it directly, often with another wait object (such polling on an fd and a socketpair fd used simply for signaling).

This is the real feature requested from issue #677

**Comment by patrickmacarthur** [comment]
I should point out that the workaround that I'm using for now is to set the timeout to something like 100 milliseconds, and then every time that `fi_cq_sread` returns with a timeout, checking if the connection is still alive before calling `fi_cq_sread` again.  This is also not ideal since it requires waking up the thread occasionally for essentially no reason, but at least avoids having to get the underlying wait object and go through the extra overhead of poll, socketpairs, etc.

**Comment by shefty** [comment]
CQ write call replaced with CQ signal
