### ISSUE TITLE
Reference counting objects?

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#705]
It would be nice if the framework could reference count objects. This would help with applications that close resources while objects are still bound to them.

e.g. a cq is closed when an endpoint is bound to it.

**Comment by shefty** [comment]
This would require that the framework intercept all open/close calls and could lead to duplicate reference tracking.  For instance, the kernel must track all user space allocated resources.  For providers that drop into the kernel to allocate resources, user space reference counting may be unnecessary.

Maybe there could be some sort of opt-in model where a provider could direct calls to the framework?  This idea was also discussed as part of debug logging, so that even fast path operations could have logging available in release builds.

**Comment by sayantansur** [comment]
Yes, that sounds like a good idea.

I'll work with @shantonu and @jithinjosepkl to see if the sockets provider can do this.

**Comment by jithinjosepkl** [comment]
Sounds like a good idea. Sockets currently track object counts for domain. For example, if user closes domain without domain objects such as cq, ep, it will complain.

**Comment by shefty** [comment]
This is one idea for supporting this:

Define a new internal structure:
struct fid_core {
   void *context;   /* use by the framework */
   struct fid fid;
}

Add a call to the framework, such as fi_hook(fid_core, ...).

When called, fi_hook() will allocate context space for the provider.  The provider will save the provider function pointers set in the fid to its context, then replace them with its own.  (The framework may need to cast the fid to an appropriate structure based on the fid type.)  fi_hook() would take other parameters indicating the type of 'hooking' that's needed, which would allow the framework to selectively replace calls.

**Comment by shefty** [comment]
The utility provider/library will provide this functionality when used by the underlying providers. There is also work ongoing that will provide the hook functionality described above (a proxy provider).

**Comment by shefty** [comment]
This functionality is not incorporated into the utility framework.
