### ISSUE TITLE
prov/sockets: fails running fi_eq_test

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#708]
Testing EQs on fabric IP
Running eq_open_close...PASS!
Running eq_write_read_self...FAIL
  fi_eq_write ret=0, Success
Running eq_write_overflow...FAIL
  fi_eq_write ret=0, Success
Running eq_wait_fd_poll...FAIL
  fi_eq_write ret=0, Success
Running eq_wait_fd_sread...FAIL
  fi_eq_write ret=0, Success
Summary: 4 tests failed

**Comment by shantonu** [comment]
Need some clarifications: @jithinjosepkl @luomiao @shefty 
- eq_write_read_self checks for -EAGAIN return value from fi_eq_read when the eq is empty. But the manpage says it returns the number of bytes read. Isn't returning 0 instead of error more reasonable for fi_eq_read?
-  eq_write_overflow also checks for -EAGAIN return value from fi_eq_write when eq is full. The man page doesn't say anything about the overflow scenario. But it says size attribute is the "minimmum size of eq" when in fi_eq_open. What should fi_eq_write return in case of overflow?

**Comment by shefty** [comment]
eq_write should return -FI_EAGAIN in case of overflow.

We can consider changing the return value for read.  Both -EAGAIN and 0 are reasonable.  EAGAIN is often used with nonblocking operations (including the standard 'read' call) to indicate that the operation would have blocked.  Returning 0 makes a little more sense to me, given that we have separate blocking and nonblocking read calls.

**Comment by shantonu** [comment]
Since manpage doesn't enforce the eq size to be the size of fi_eq_attr.size. So a provider can choose to buffer the writes when number of eq entries fi_eq_attr.size. In that case we need to modify the eq overflow test.

**Comment by shantonu** [comment]
Pushed a Fabtests fix addressing the test failures https://github.com/ofiwg/fabtests/pull/173
