### ISSUE TITLE
fabtests: fi_rdm_atomic segfault

### ISSUE THREAD

**Issue by ghost** [ofiwg/libfabric#7138]
We have seen that ever since the introduction of https://github.com/ofiwg/libfabric/pull/6929 that the fi_rdm_atomic test segfaults, at least under certain conditions with certain providers. This is breaking our CI.

This has so far only been observed with the EFA provider but only built without debug and running in a multi node test. The exact command that fails is: `fi_rdm_atomic -o all -I 1000 -U -p "efa" -E`

We are still RCA'ing but wanted others to be aware of this in the meantime.

**Comment by richwelchaws** [comment]
I now have an RCA for this issue.

This happens in non-debug builds with the EFA provider because we were accessing 128 bit ints where they were not 16 byte aligned, and when optimizing the compiler uses instructions that require 16 byte alignment. Hence the segfault.

This requirement could be changed by using a `memcpy` instead in `void ofi_cswap_## op ##_##`, but that could introduce performance impacts.

In the meantime we may disable support for 128 bit atomic ints in EFA until we can guarantee proper alignment.

**Comment by shefty** [comment]
Both the EFA and shm providers have disabled support for 128-bit atomics because they cannot guarantee that data buffers are aligned.  This issue should be resolved with the latest main, and backport to v1.14.x branch
