### ISSUE TITLE
build error on RHEL 7.0

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#720]
error installing OFED-3.18-20150304-0429 on RHEL 7
error: Failed build dependencies:

        libnl3-devel is needed by libfabric-1.0.0rc2-1.x86_64

However, the libnl3-devel package is not distributed with RHEL 7.0 release:
http://isotope.jf.intel.com/rhel70-x86_64/SDVD1/Packages/

**Comment by shefty** [comment]
@goodell @jsquyres - The usnic provider uses this.  I think this is coming from the libfabric.spec.in BuildRequires.  Is there a way to make this optional?

**Comment by pmmccorm** [comment]
It is in the RHEL7 repos when hooked up to RHN:

```
yum info libnl3-devel

Name        : libnl3-devel
Arch        : x86_64
Version     : 3.2.21
Release     : 6.el7
Size        : 195 k
Repo        : installed
From repo   : rhel-7-server-optional-rpms
Summary     : Libraries and headers for using libnl3
URL         : http://www.infradead.org/~tgr/libnl/
License     : LGPLv2
Description : This package contains various headers for using libnl3
```

**Comment by jsquyres** [comment]
Arrgh.  libnl.

libnl comes in 2 flavors: version 1 and version 3.  usnic needs one of them -- either one, it doesn't matter.  And you can have both installed simultaneously; they don't conflict with each other.  

We defaulted usnic to requiring the later one because most other packages seem to build against libnl3 (because it's newer/better).  It seems like libnl v1 is provided by RH for legacy stuff (because the API changed between v1 and v3).

I don't think RPM has mojo for requiring A *or* B, does it?

**Comment by shefty** [comment]
Doesn't the build auto-detect if the library is there or not?  If so, it's not really a requirement for the package, is it?

**Comment by pmmccorm** [comment]
No, anytime a spec seems to require a || b, what it actually wants is to depend on a something provided by both a and b, where b can obsolete a (or be parallel installible).

Maybe just change the Buildrequires to libnl-devel, which will work without the optional-channel libnl3-devel.

Yes the build auto-detects the library, but if we specify it explicitly we get a nice message from RPM when we try to build it that says "requires ... to build" vs just failing to compile. More user friendly.

**Comment by jsquyres** [comment]
Oh, that's a good idea -- I don't have a RHEL7 handy to check: do both libnl1-devel and libnl3-devel provide a neutral libnl-devel?  If so, that's perfect.

**Comment by shefty** [comment]
The build *will* compile.  If I install the source on my system, it automatically checks for what's needed for the usnic, verbs, and psm providers.  Whatever isn't there just doesn't get built.  Why can't the package do the same?  That's more user friendly than requiring the installation of libraries for hardware that the user likely doesn't have.

**Comment by jsquyres** [comment]
By that logic, we shouldn't have any BuildRequires, because the sockets provider will likely always be able to be built.

I guess the real question is: who are you targeting with the spec file -- users, or distributors?  I don't feel bad about requiring distributors to have either libnl1-devel or libnl3-devel.

**Comment by pmmccorm** [comment]
It looks like lbnl* doesn't do the right things:

```
]$ rpm -q --provides libnl-devel
libnl-devel = 1.1.4-3.el7
libnl-devel(x86-64) = 1.1.4-3.el7
pkgconfig(libnl-1) = 1.1.4
$ rpm -q --provides libnl3-devel
libnl3-devel = 3.2.21-6.el7
libnl3-devel(x86-64) = 3.2.21-6.el7
pkgconfig(libnl-3.0) = 3.2.21
pkgconfig(libnl-cli-3.0) = 3.2.21
pkgconfig(libnl-genl-3.0) = 3.2.21
pkgconfig(libnl-nf-3.0) = 3.2.21
pkgconfig(libnl-route-3.0) = 3.2.21
```
We can make the RPM like the tarball build-- compiling support for whatever it can. The RPM though is what is going into OFED-3.18 (and distros), so we probably want to have a constant set of providers so that all customers have the same libfabric. We had this discussion I thought (or maybe just the beginning of it) when pushing changes to the spec file.

Or we can package all the providers separately-- each will only require their dependencies, can be installed individually, and be dl-loaded, ie libfabric, libfabric-psm, libfabric-usnic, libfabric-verbs, etc. But this was shot down early.

**Comment by jsquyres** [comment]
Yep; this is a bummer.

Sidenote: I see that libnl-route-3 is separate. Does libfabric+usnic build properly on RHEL7 with just libnl3-devel?  Or does it need libnl3-route-devel, too?  (or whatever the relevant package is called).

This does raise an interesting question, though -- if we're forcing these BuildRequires, why aren't we also forcing the corresponding Requires, too?

**Comment by shefty** [comment]
IMO - the goals is to have the distros include the libfabric package directly.  RH does not touch OFED.  No one sane ever should.  The vendors ship their own software anyway.  SuSE used to pull in OFED directly.  I don't know if that's still the case or not.

Anyway, I would say that the spec files are targeting the distros.  I don't believe OFIWG is planning on publishing RPMs.  Did we already discuss this in a OFIWG meeting?

**Comment by jsquyres** [comment]
@dledford What should we do here?

**Comment by dledford** [comment]
On Fri, 2015-03-06 at 04:43 -0800, Jeff Squyres wrote:
> @dledford What should we do here?

Interestingly enough, I'm going to have to modify my email rules to
account for this ;-)  Tagging me on a github thread did not cause this
email to go to my inbox instead of my libfabric mail folder, so I only
say this as I was perusing libfabric mail today.

OK, so I'll clear a few things up:

You are welcome to include a spec file, but understand it will never be
used "as is" by any vendor that I know of.  We all keep our own spec
files and ship them separate from the tarball and use our own copies to
actually do the builds of the programs.

Now, I can't speak for other vendors on this next part, only Red Hat,
but here are the reasons/justifications for the way things are:

Understand that for any distro, software build determinism and
repeatability are important.  From build to build we can't have random
things changing without us knowing about it.  While the
automake/autoconf stuff is nice for end users, it's actually quite the
pain for our repeatability requirement.  It means we can't actually have
shared build environments for different packages, or else installing
libnl3-devel in order to build iproute2 would cause the build of
libibverbs and now libfabric to change silently on us.  For that reason,
all official builds are done in a clean buildroot built just for that
one build and then thrown away.  There are a base set of packages that
are installed in that clean build environment (glibc, gcc, bash, make,
stuff like that, about 90 rpms in total).  If a package is not in that
base set, and you need it to build, then it *must* be included in the
BuildRequires: lines of the spec file.  Only if it is included there
will it ever get used in the official build.

With that in mind, my suggestion for any spec file template you have in
the package is to follow this rule of thumb: make it build everything,
but make it easy for the user to turn some things off.  For that to
work, I would add a BuildRequires on all the non-standard packages you
need, and then I would add some macros at the top of the spec file that
allow a user to change the macro to either enable or disable specific
providers.

And I'm guessing you don't have the updated RoCE code for libibverbs or
else the verbs provider would need libnl or libnl3 too :-/  That's
probably something to consider looking at for the 1.0 release as it
means that your current RoCE support is the old wire format and is
incompatible with the current generation stuff (I know, Roland hasn't
taken it yet, but we can't wait forever on him, this wire protocol
shipped in rhel6.6, rhel7.0, and only rhel6.5 and earlier will be wire
compatible with what you have now if you have the old wire protocol, and
I know OFED also has moved on to the latest wire protocol, but I don't
know for certain where SuSE stands on this issue).

-- 
Doug Ledford <dledford@redhat.com>
              GPG KeyID: 0E572FDD

**Comment by shefty** [comment]
Thanks for the input.

FYI - libfabric no longer builds or contains libibverbs or librdmacm directly.  It just requires that they be there.  But this does make me wonder what OFED has.

**Comment by pmmccorm** [comment]
Thanks Doug this is very useful information.

So it looks like our sole consumer of the spec file is >= OFED-3.18, or people downloading the tarball from openfabrics.org and building RPMs (rpmbuild -ta ...).

But we probably want the libfabric installed by an OFED distro to have the same set of providers as  one installed by RHEL/SuSe (for debugging sanity sake).

**Comment by jsquyres** [comment]
@dledford Which libnl does the new RoCE stuff use -- libnl3?

@shefty @pmmccorm libnl1 and libnl3, while they can co-exist peacefully on a single system, they *cannot* be combined in a single process (Bad Things will happen).  So usnic and verbs (and whoever else) must all agree on what they use: libnl1 or libnl3.

**Comment by pmmccorm** [comment]
It looks like:

Distro libibverbs from RHEL7 and SLES12 both depend on libnl3.

In RHEL7 libnl3-devel is in the "optional" repo (available only via RHN?), but plain old libnl3 is available on the install CD.

On SLES12 both lib and devel packages look available from the install CD(s).

OFED-3.18 libibverbs does not require any libnl.

So I think the best solution is to make libfabric.spec buildrequire libnl1-devel for OFED-3.18, so that it works fine without adding extra repos on both RHEL/SLES. If OFED libibverbs ever starts requiring libnl we match them.

The distros should require libnl3-devel, the same as their libibverbs requires.

**Comment by goodell** [comment]
> So I think the best solution is to make libfabric.spec buildrequire libnl1-devel for OFED-3.18, so that it works fine without adding extra repos on both RHEL/SLES. If OFED libibverbs ever starts requiring libnl we match them.
>
> The distros should require libnl3-devel, the same as their libibverbs requires.

Agreed.

I do want to reemphasize how important it is for each distribution/packager to get this right.  If libnl and libnl-3 are linked into the same process, bizarre crashes, assertion failures, and corruption can all happen.

**Comment by shefty** [comment]
Are we sure it's not safer to require libnl3 then?  If someone repackages OFED with the later version of verbs or installs the later version of verbs manually, things will be broken.

**Comment by goodell** [comment]
> Are we sure it's not safer to require libnl3 then?

It's probably safer, but I thought that the new libnl3-devel requirement was a major problem on RHEL 7...

The best fix would be if libnl v1/v3 weren't such a mess in general, but that's not something that we have control over.

**Comment by jsquyres** [comment]
Perhaps the specfile should be generated via configure, and can therefore put whatever configure finds (libnl1 vs. libnl3) in the specfile.

**Comment by pmmccorm** [comment]
There are three issues we are talking about here:

1) Fix the build failure where libfabric requires libnl-3-devel on RHEL7, but ilibnl3-devel is only available from the "optional" repo (RHN subscribers only).

2) Depend on the libnl that matches the one from verbs (if verbs depends on libnl, otherwise choose libnl that satisfies 1).

3) Provide guidance to distro packagers to follow step 2 on their own (since at least for RHEL, they write their own specs).

Choosing libnl1 solves 1 and 2 for RHEL7/SLES12 with (and only with) OFED-3.18.

For 3 I think we just file a bug w/ respective distros if they get it wrong (or just work with them directly).

To solve this with configure we could:
make BuildRequires: @LIBNL@
or remove it completely

Then have configure determine which version libibverbs links against and SUBST that value.

This would have to be ported to install.pl for OFED-3.18 (yuck! install.pl has already halfway implemented a package manager). Also this would be very fragile since it would have to rely on compiled library names linked to by other libraries etc.

**Comment by dledford** [comment]
On Fri, 2015-03-06 at 11:03 -0800, Jeff Squyres wrote:
> @dledford Which libnl does the new RoCE stuff use -- libnl3?
> 
> @shefty @pmmccorm libnl1 and libnl3, while they can co-exist
> peacefully on a single system, they cannot be combined in a single
> process (Bad Things will happen). So usnic and verbs (and whoever
> else) must all agree on what they use: libnl1 or libnl3.

In rhel6, libibverbs uses libnl, in rhel7 it uses libnl3.  However, the
libnl3 support in rhel7 is broken and I'm tempted to recompile it
against libnl for 7.2.

-- 
Doug Ledford <dledford@redhat.com>
              GPG KeyID: 0E572FDD

**Comment by jsquyres** [comment]
I think we're overthinking this.

As Doug said, this spec file is basically for consumers -- not distros.  

Since configure already figures out what is on the system, it seems reasonable to have a `@LIBNL@` (let's hope there's no @LIBNL github user!) in the Makefile.am that gets the result from configure.  Then the user will be able to build the RPM on their machine -- they just have to run configure first.

**Comment by jsquyres** [comment]
Hah. There is a @libnl github user.  Sorry for the noise!

**Comment by shefty** [comment]
To best of my knowledge, I think this has been addressed by the usnic configure.  Closing this.  If this issue still needs to be resolved, we can re-open.

**Comment by pmmccorm** [comment]
I think we should try depending on libnl1 in our spec by default for OFED-3.18, so that we can compile on RHEL7 systems w/o RHN subscription. See my comment above.

**Comment by jsquyres** [comment]
The usnic configury will first look for libnl3, and if it finds it, it will use it.  If it didn't find libnl3, it'll look for libnl and if it finds it, it will use it.

You're suggesting that we change the spec file to require libnl-devel instead of libnl3-devel, right?

The spec file is already generated via configure; it would probably be sufficient to have @LIBNL_DEVEL@ in the libfabric.spec.in that gets filled in with whatever configure found.  That way, it'll require whatever was already found on the user's system.

Kosher?

**Comment by pmmccorm** [comment]
We give Vlad/OFED a .src.rpm, which will get "rpmbuild--rebuild .."-ed, so I don't think @LIBNL_DEVEL@ will work..

**Comment by jsquyres** [comment]
Why not?

**Comment by jsquyres** [comment]
Never mind, I'm a moron -- the spec file is already generated, duh.

**Comment by jsquyres** [comment]
What libnl is RoCE (in OFED) using?  We need to match it.

**Comment by pmmccorm** [comment]
Read my comment from above.

**Comment by jsquyres** [comment]
@pmmccorm I'm not sure which comment above you're referring to -- none of them specify which libnl RoCE/OFED is using...?  Your comment above talks about using configure to figure out which libnl libibverbs uses, but doesn't that have the same problem: "rpmbuild --rebuild ..." is using a specfile that is already built, so AC_SUBST'ing `@LIBNL@` won't fix it?

**Comment by pmmccorm** [comment]
```
There are three issues we are talking about here:

1) Fix the build failure where libfabric requires libnl-3-devel on RHEL7, but ilibnl3-devel is only available from the "optional" repo (RHN subscribers only).

2) Depend on the libnl that matches the one from verbs (if verbs depends on libnl, otherwise choose libnl that satisfies 1).

3) Provide guidance to distro packagers to follow step 2 on their own (since at least for RHEL, they write their own specs).

Choosing libnl1 solves 1 and 2 for RHEL7/SLES12 with (and only with) OFED-3.18.
```

**Comment by jsquyres** [comment]
@pmmccorm Cool; it was my (apparently flawed) understanding that libibverbs in OFED was linking to libnl.  If that's not the case, then this is all moot -- it sounds fine to link against libnl1 for OFED.

**Comment by shefty** [comment]
Please, at least re-open the issue if we're going to continue to have discussions on it.

What change is needed for this?  Just an update of libnl3-devel to libnl-devel in libfabric.spec.in?

**Comment by pmmccorm** [comment]
@shefty : yes that is all
