### ISSUE TITLE
prov/netdir: fi_getinfo does not return FI_CONTEXT (bug)

### ISSUE THREAD

**Issue by dshinaberry** [ofiwg/libfabric#7212]
Regarding the netdir provider and the fi_getinfo function. If I understand the api correctly, when providing hints for mode of “FI_CONTEXT|FI_CONTEXT2”, if the corresponding bits are cleared in the returned fi_info struct, then there is no requirement for providing a fi_context/fi_context2 struct ahead of any context used by the application.

What I am seeing when invoking fi_sendv / fi_recvv is that it is, in fact, using context for internal purposes. The context the application provides is overwritten during the function execution and differs after the call returns.

If I provide an fi_context2 struct ahead of the application context, then things appear to behave as expected.

So, I’m assuming that I’ve stumbled upon a bug here.

**Comment by j-xiong** [comment]
A quick reading of the code reveals what happened: the provider checks if the context is NULL, if not they it goes ahead to use the first word to store information for fi_cancel().  This behavior can be considered "not requiring context" to some extent because it works if NULL context is used. However, it will break when application does supply a context that is not intended to be written to (either in the scenario described in the bug report or the when context be simply a number). So this is a bug.

**Comment by shefty** [comment]
Correct, the provider needs to set FI_CONTEXT as a mode bit.

**Comment by shefty** [comment]
Added fix to the provider to set the mode bit.  See #7240

**Comment by shefty** [comment]
Fixed by #7240
