### ISSUE TITLE
Clarifications on FI_MR_PROV_KEY/requested_key

### ISSUE THREAD

**Issue by rwespetal** [ofiwg/libfabric#7233]
We're running into a problem with the sockets provider memory registration path and FI_MR_PROV_KEY. I think some additional clarification may be needed in the man page, and I think there might be a bug in the hints/getinfo path as well.

For context, we have a customer application that uses Libfabric, and they want to switch between the EFA and sockets providers to test their library on instances without an EFA device, and they want the same behavior as the EFA provider using sockets, where the provider assigns a key. The app passes 0 for the key (since it should be optional), but due to the bug below the sockets provider uses 0 as the requested key, and fails subsequent registrations that pass 0 for the key as [this path to use a provider key](https://github.com/ofiwg/libfabric/blob/main/prov/util/src/util_mr_map.c#L71-L72) is not taken.

On the man page, should it state that when an application passes FI_MR_PROV_KEY in the `mr_mode` hints, the provider must generate a key and ignore `requested_key` in the MR registration attributes? The fi_mr page is clear about the behavior when the provider sets this flag, but I think it could be clearer about when `requested_key` is optional and when it is not from the application's perspective:

> requested_key:    Optional requested remote key associated with registered buffers.

> Because MR keys must be provided by a remote process, an application can use the requested_key parameter to indicate that a specific key value be returned. Support for user requested keys is provider specific and is determined by the mr_mode domain attribute.

On the attribute bug, FI_MR_PROV_KEY is getting dropped in [fi_alter_domain_attr](https://github.com/ofiwg/libfabric/blob/main/prov/util/src/util_attr.c#L1136-L1140) as `attr->mr_mode` is 0, not sure if that's correct or not. My concern here is that if we change this/fix this bug we're going to impact applications. For example, fabtests does set FI_MR_PROV_KEY in the hints but some paths don't check for it and assume the requested key will be used.

For a reproducer I'm just running `fi_rdm_pingpong` with the sockets provider using the main branch.

**Comment by shefty** [comment]
The mr_mode flags act the same as the main mode flags.  The provider clears those flags that it does not require.  The app is expected to check the flags an react accordingly.  If the flag has been cleared, then the app controls the MR key values.
```
By setting an mr_mode bit, the application has agreed to adjust its behavior as indicated. Importantly, applications that choose to support an mr_mode must be prepared to handle the case where the mr_mode is not required. A provider will clear an mr_mode bit if it is not needed.
```
FI_MR_PROV_KEY is no different from other mr_mode flags.  It is not an application requirement to fi_getinfo.  The app is saying that it can handle the case when it is set, but also when it is cleared (which is the ideal default, since key exchanges are not needed).

The fi_mr_attr requested_key definition includes this text:
```
Support for user requested keys is provider specific and is determined by the mr_mode domain attribute.
```
The optional part here only refers to whether the mr_mode has that key set.  If FI_MR_PROV_KEY is not set, then the key is not optional.  The input value will be used, and there are no reserved or special values.  0 is as valid as any other integer.

I *think* there's an undocumented feature that we use for testing, which is that FI_MR_PROV_KEY can be set in the mr_mode flags when opening a domain.  I.e. FI_MR_PROV_KEY can be OR'ed back into the mr_mode from the fi_getinfo output.  That will force some providers to generate keys (always) when registering memory.  This should work for providers that use software based registration code (mr_map), and rxm and tcp should support this.  We could document this behavior, assuming that it is the behavior.

**Comment by rwespetal** [comment]
Thank you for the response, that clears up the confusion I had on the behavior here.
> I think there's an undocumented feature that we use for testing, which is that FI_MR_PROV_KEY can be set in the mr_mode flags when opening a domain. I.e. FI_MR_PROV_KEY can be OR'ed back into the mr_mode from the fi_getinfo output.

**Comment by rwespetal** [comment]
The customer was able to make the change to get this working again, they will pass a unique key when using the sockets provider. I did confirm the undocumented option you mentioned also works. Thanks again for the help here, Sean!
