### ISSUE TITLE
DAOS: verbs;ofi_rxm - failure to allocate qpairs on client beyond some scale

### ISSUE THREAD

**Issue by frostedcmos** [ofiwg/libfabric#7368]
Testing on Frontera DAOS validation reported rdma_create_qp() failing with failure to allocate memory.

Setup:
Servers 256
Targets per Server 16
Total targets 4096
Clients 16
PPN 32
Total client processes 512

Provider: verbs;ofi_rxm
OFI: v1.14.0rc3

Client app: mdtest ran on all clients against servers.

some of clients with this setup fail with following errors:

libfabric:22102:1638393161:verbs:ep_ctrl:vrb_ep_enable():884<warn> rdma_create_qp: Cannot allocate memory (12)
libfabric:22102:1638393161:ofi_rxm:ep_ctrl:rxm_open_conn():140<warn> fi_enableCannot allocate memory (-12)

Corresponding DAOS ticket: https://daosio.atlassian.net/browse/DAOS-9175

**Comment by j-xiong** [comment]
Could be just running out of resource. Does setting FI_VERBS_TX_SIZE and FI_VERBS_RX_SIZE to a smaller value help? The default value is 384.

**Comment by chien-intel** [comment]
This issue is traced to Mellanox ConnectX-6 controller returning error on Create QP command: 
[1899678.679848] mlx5_core 0000:5e:00.0: mlx5_cmd_check:824:(pid 46096): CREATE_QP(0x500) op_mod(0x0) failed, **status limits exceeded(0x8),** syndrome (0x19c6d6)

At the time of error, "rdma resource" is showing:

0: mlx5_0: pd 99 cq 95 qp 130763 cm_id 130810 mr 848 ctx 98

Which is no where near the 262144 max_qp limit.
Closing this issue as it is not related to libfabric.
