### ISSUE TITLE
fi_av_insert: attaching user data to returned fi_addr_t

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#7428]
This may be both a question and a feature request. Currently a call to `fi_av_insert()` returns us a `fi_addr_t *fi_addr`. Using that returned `fi_addr_t` we define in our code our own struct on top it as follows, e.g. :
```C
struct my_addr {
  ...
  fi_addr_t fi_addr;
  ...
};
```
For providers that support the `FI_SOURCE` cap flag, a call to `fi_cq_readfrom` is able to provide us source address information in the form of `fi_addr_t *src_addr`. While this is already great in its own, we don't have any other way currently to retrieve the top struct `my_addr` (defined as above) other than using a hash table to look it up using the corresponding `fi_addr`. Instead of using a hash table, I'm wondering if there would be a way to attach it at the time of `fi_av_insert()` so that we could directly retrieve it later on using either some sort of `container_of()` call or similar. Would that make sense? Or is there any other way to achieve the same behavior currently? I could not really see anything in the current API that would allow for that. (Note that this mostly concerns unexpected recv cases where we don't know in advance the source address of the peer that is going to send us a msg)

**Comment by shefty** [comment]
This is asking for some sort of address context.  There are 2 ways the fi_addr_t can be formed.

FI_AV_TABLE:
If you force your AV to use FI_AV_TABLE, the returned fi_addr_t will be an index.  This also gives you the control over which index is assigned to which address.  You would only need to store the address context in an array.

Note that in provider implementations for FI_AV_TABLE, it shouldn't be difficult to instead return an address context instead.  It's more of a question if it's needed, as the provider would basically just implement an address context array for this purpose.

FI_AV_MAP:
With FI_AV_MAP, the returned fi_addr_t may be directly formed from the network address itself.  No lookup or translation is needed.  For example, the fi_addr_t could be an {tcp port, ipv4}, {lid, qpn}, {mac, cmd queue}, or other such tuple.  In this case, returning an address context would require some sort of hash table lookup, like you mentioned.

Rather than trying to change the behavior of FI_AV_MAP, a better option would be for the app to request FI_AV_TABLE.  This basically tells the provider to perform the lookup, if needed.  FWIW, FI_AV_TABLE isn't necessarily less efficient than FI_AV_MAP.  For example, the fi_addr_t mapping can be determined during communication setup, so that lookups aren't needed later.

**Comment by soumagne** [comment]
Interesting, right exactly that's asking for an address context. The problem with having an array in our case is that we never have a fixed number of peers from start to end (as peers come and go) so having an array indexed from 0 to N would then add complexity in the sense that we'd have to potentially resize the array etc (all while being thread safe). Not saying that it would not be doable but I'd rather keep a hash table than having to deal with array resizing I think...

**Comment by shefty** [comment]
libfabric makes use of an abstraction called an index map that might work in your case.  See:

https://github.com/ofiwg/libfabric/blob/main/include/ofi_indexer.h
https://github.com/ofiwg/libfabric/blob/main/src/indexer.c

The index map acts as a dynamically growing/shrinking array.  The implementation uses a double array underneath that allocates chunks of entries as needed.  Allocated entries are not moved or freed.  The original intent of the index map was to associate a pointer with an integer file descriptor.

**Comment by soumagne** [comment]
Ok that might work then. I will look into it. Thanks for the pointers!

**Comment by shefty** [comment]
This feature ends up being needed to optimize the peer provider implementation.  As a result, since it's needed for that, it was added as an exposed feature of the API.  See f8225b592b640bce3d6ac7f90409cc0bd13c0a0c in PR #7670.  This is an optional capability that isn't currently supported by any providers, but will be by the shm provider soon.  It could be added for others, such as rxm.

**Comment by soumagne** [comment]
Thanks @shefty, it's definitely great to see that being added. When requesting `FI_AV_USER_ID` through `fi_getinfo()`, would providers that do not support it simply clear off that bit (similar to MR mode bits) or would fi_getinfo() fail because the provider does not support the minimal set of requirements that are passed? I'm asking because I've seen so far the latter I believe when asking for things like `FI_DIRECTED_RECV` etc and a provider was not supporting it.

**Comment by shefty** [comment]
For capability bits, the provider is expected to fail the fi_getinfo call if it cannot support the requested capabilities.  The mode bits (including mr_mode) are different in that the provider removes those that are not needed.

Which provider was not failing for FI_DIRECTED_RECV?  That is a bug in the provider.

**Comment by soumagne** [comment]
OK. No it was failing for FI_DIRECTED_RECV.

**Comment by shefty** [comment]
API feature now defined.  Just needs more providers to implement...
