### ISSUE TITLE
Shm provider's usage of mutex lock in smr region cause performance degradtion (especially on centos7/centos8)

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#7429]
Commit 98782f7dd02237cedfc0a5fb0ef1e85ed9955adb made the shm provider to use a mutex lock (replacing a spin lock).

Though the intention was to improve performance, we have seen the change caused performance degradation in multiple HPC workload on several OS, in general, legacy OS (like centos7 and rhel7) are more impacted than modern OS. 

For example, on CentOS 7, we have seen the performance of OpenFOAM (which is a widely used computational fluid dynamics program), drop by 25% on a typical use case (The motorbike test case).

Given this observation, I wonder if we should reconsider this change. Or, at least make shm lock type a configurable option?

**Comment by wzamazon** [comment]
@aingerson and @shefty We would really appreciate your input on this issue.

**Comment by shefty** [comment]
Given how apps might spin on the shm provider, I would have expected that a spin lock would be more likely to lead to starvation.  I'm not as surprised about problems with legacy OS's, as their implementation of mutex may be less optimal.  I think we need to analyze the impact for different platforms, versus assuming that the same solution will work for all.

Also, it's not as simple as reverting the lock in the commit you referenced.  There are nested locks here, some of which are still mutex.

**Comment by wzamazon** [comment]
> Also, it's not as simple as reverting the lock in the commit you referenced.

I understand that reverting will not work. Do you think making shm lock type a configurable option is possible? This way user on legacy OS can choose old behavior. 

> There are nested locks here, some of which are still mutex.

Would mix type of locks be a problem? e.g. shm usage spin lock, but other parts still use mutex lock.

> I think we need to analyze the impact for different platforms, versus assuming that the same solution will work for all.

I see. What kind of analysis do we need to do? I checked that pthread on centos7 version 2.17, and is part of glibc, so it is not easy to  just upgrade pthread.

**Comment by wzamazon** [comment]
>Since a mutex can block, we can't hold a spin lock then try to acquire a mutex. 

I see. Thanks for the explanation.

> I was suggesting that we need to look at the performance on, say, Centos 7 vs Centos 8. Do they both see degradation, and if so, how much?

For this workload, e.g. openfoam motorbike test case, centos7 and centos8 show similar level of degradtion, e.g. ~25%.

Amazon linux 2 and ubuntu 18.04 also observed degradation, but the degradtion is less severe (~3%).

The following table should the numbers:

|  OS  |   Before shm lock change | After shm lock change |
|-|-|-|
| CentOS 7 | ~190 second   | 240 second |
| CentOS 8 | ~190 second   | 253 second |
| Amazon Linux2 |  ~185 second | ~192 second |
| Ubuntu 18.04 | ~185 second | ~192 second |

Please let me know if there are other test I can try

**Comment by wzamazon** [comment]
We discussed this issue during the ofiwg meeting. The main concern is still the nested locks. To address the issue, the actions are:

1. utility code need to be able to choose between different types of locks
2. shm provider need to switch back to spinlock. 

I have a patch that does 2 (make shm provider to use spinlock), and I verified it brings back performance. I will open PR, and ask for feed back.

**Comment by shefty** [comment]
I've traced through most of the locking in the shm provider.  What each lock protects isn't intuitive.  Items stored in the ep->region appear to be protected by either the region or tx cq lock.  E.g. the cmd_queue is region lock, resp_queue is tx cq lock.  AFAICT, the rx cq lock only protects the receive queue.  In most cases the provider acquires the region lock of the peer, and not its own.  The region lock is acquired before acquiring other locks.

In addition to the cq locks, the provider also uses the domain lock, av lock, and cq ep_list_lock.  

The cq and domain locks are nested.  Between these, the cq lock should be the easiest to convert to a spinlock.  The util cq already has lock callbacks.  The smr provider just doesn't use it.  The util cq could be updated to support either a mutex or spinlock, with the lock callback set appropriately.  The best path here would be to update ofi_cq_init(), so that the locking type can be specified.  (Alternatively, smr could change the lock after init returns, but that's less maintainable).  The util_domain could be updated similarly by adjusting ofi_domain_init().

**Comment by shefty** [comment]
See #7439 and #7433 - combined I think these will fix the regression (at least once 7439 works)

**Comment by shefty** [comment]
Fixes were merged into main.
