### ISSUE TITLE
man: man pages are not being updated in branches

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#7616]
See #7615 for start of discussion.  The gh-man.yaml only updates main, so man pages in stable branches are not being updated.  github documentation indicates that cron jobs only operate on main/default branch.

**Comment by shefty** [comment]
@j-xiong - nroff-elves is a cron job, but I don't think that's active anymore.  We're using gh-man.yaml as the github action, which I don't believe is.

**Comment by j-xiong** [comment]
gh-man.yaml is for updating the man pages on the web site. nroff-elves.yaml is used to convert .md files to the actual man pages. Both are active.

**Comment by j-xiong** [comment]
You can check the history under the "Actions" tab. The nroff-elves action is not properly named (it uses the default name "GitHub Action Schedule").

**Comment by shefty** [comment]
Can we just change the nroff to an on push action?

**Comment by j-xiong** [comment]
I think we can. @jsquyres, is there any specific reason this should be started as a cron job instead of a push action?

**Comment by shefty** [comment]
This may just be an artifact from when it ran as a cron job on the ofa server.

**Comment by j-xiong** [comment]
I am working on  a patch for this.

**Comment by j-xiong** [comment]
PR #7619, #7621, #7623 make the change for `main`, `v1,15,x` and `v1.14.x` branches, respectively. The first two were merged so that test run can be performed. Older branches are unlikely see man page updates so we can probably leave them alone.

With the changes in place, the action was able to create correct PR for the triggering branch. However, for table branches review approval is required before a PR can be merged. As the result, the PR failed to merge and then was closed.

**Comment by shefty** [comment]
I removed the review requirement from the stable branches.  I think we're okay not having that.

**Comment by j-xiong** [comment]
Great. Added PR #7624 for `v1.13.x`. That's where the actions were initially introduced.

**Comment by j-xiong** [comment]
v1.15.x man pages have been successfully updated with a manually triggered run of the action.

**Comment by j-xiong** [comment]
All these PRs have been merged.

Next time any change to `man/*.md` would trigger the action.
