### ISSUE TITLE
prov/tcp: zerocopy being disabled under load

### ISSUE THREAD

**Issue by DougSO** [ofiwg/libfabric#7887]
**Describe the bug**
While running an aggressive RDMA test using TCP provider, I started seeing these pair of warnings from libfabric:

tcp  ep_data   warn ofi_bsock_async_done:1270 Error reading MSG_ERRQUEUE (Resource temporarily unavailable)
tcp  ep_data   warn ofi_bsock_async_done:1296 disabling zerocopy

Looking at the code, it seems we are trying to read the MSG_ERRQUEUE via a readmsg() call and are getting EAGAIN back.  I'm not sure if this should be expected under heavy load or not.  Triggers us to disable zerocopy.

Now, I'm not sure if it is related, but shortly after that, I see this assert from the TCP provider:

red: prov/tcp/src/tcpx_progress.c:674: tcpx_recv_hdr: Assertion `ep->cur_rx.hdr.base_hdr.id == ep->rx_id++' failed.

In another case where I saw those warnings, it was followed by this assert:

red: prov/tcp/src/tcpx_progress.c:415: tcpx_handle_ack: Assertion `!slist_empty(&ep->need_ack_queue)' failed.

I'm starting to get the feeling that dynamically disabling zerocopy might open us up to asserts.

**To Reproduce**
My setup is the following:
- libfabric version 1.14
- 30 ARM-based node cluster
- Each node has two endpoints to every other node
- Dedicated polling threads are used.  Each polling thread "owns" a set of endpoints and only it accesses them.  I've reproduced this for both COMPLETION mode and THREAD_SAFE mode.
- An RDMA test is performed which loads up all endpoints with 32 1M RDMA transfers each direction
- Zerocopy seems to be on by default now (I've see the patches that introduced this)
- The NICs are Mellanox CX5 in RoCE mode.  We are using them with the TCP provider to test it.
- This issue only happens when pushing RDMA to the limit.  Does not happen with aggressive messaging.

**Expected behavior**
Zerocopy does not get disabled.  Also, we don't assert!!

**Output**
Output above.

**Environment:**
Ubuntu Linux 20.04.4 LTS

**Additional context**

**Comment by aakefbs** [comment]
@DougSO Just back from vacation and checking mails...

See here regarding the assert
https://github.com/ofiwg/libfabric/issues/7844#issuecomment-1161982132

and here regarding the log messages
https://github.com/ofiwg/libfabric/pull/7871#pullrequestreview-1029161364

**Comment by shefty** [comment]
As @aakefbs mentioned, the assert is for libfabric debugging.  Don't mix release and debug versions of libfabric.

Zerocopy is disabled by default and must be enabled through an environment variable.  Disabling zerocopy on an error is expected.

Are you seeing that any zerocopy transfers complete?

**Comment by sydidelot** [comment]
@shefty FYI, this issue is still impacting us with libfabric 1.18.1.

As pointed out by @DougSO (cc @bsbernd), we see the following lines in the logs before the assertion failure triggers:
```
tcp  ep_data   warn ofi_bsock_async_done:1444 Error reading MSG_ERRQUEUE (Resource temporarily unavailable)
```

The scenario I suspect is that zero-copy gets disabled in the middle of a TCP transfer (short send) and the transfer is restarted from the beginning (without zero-copy support), causing a corruption of the TCP stream.

IMHO, the main issue is that zero-copy shouldn't be disabled if `recvmsg(..., MSG_ERRQUEUE)` returns EAGAIN. Instead, the function should return `bsock->done_index` to let the caller retry later. 

My other concern is that `ofi_bsock_async_done()` may disable zero-copy for some other reasons:
```
    assert(!(msg.msg_flags & MSG_CTRUNC));                                  
    cmsg = CMSG_FIRSTHDR(&msg);                                             
    if ((cmsg->cmsg_level != SOL_IP && cmsg->cmsg_type != IP_RECVERR) &&    
        (cmsg->cmsg_level != SOL_IPV6 && cmsg->cmsg_type != IPV6_RECVERR)) {
        FI_WARN(prov, FI_LOG_EP_DATA,                                       
            "Unexpected cmsg level (!IP) or type (!RECVERR)\n");            
        goto disable;                                                       
    }                                                                       
                                                                            
    serr = (void *) CMSG_DATA(cmsg);                                        
    if ((serr->ee_origin != SO_EE_ORIGIN_ZEROCOPY) || serr->ee_errno) {     
        FI_WARN(prov, FI_LOG_EP_DATA,                                       
            "Unexpected sock err origin or errno\n");                       
        goto disable;                                                       
    }                                                                       
                                                                            
    bsock->done_index = serr->ee_data;                                      
    if (serr->ee_code & SO_EE_CODE_ZEROCOPY_COPIED) {                       
        FI_WARN(prov, FI_LOG_EP_DATA,                                       
            "Zerocopy data was copied\n");                                  
disable:                                                                    
        if (bsock->zerocopy_size != SIZE_MAX) {                             
            FI_WARN(prov, FI_LOG_EP_DATA, "disabling zerocopy\n");          
            bsock->zerocopy_size = SIZE_MAX;                                
        }                                                                   
    }                                                                       
    return bsock->done_index;                                               
}                                                                           
```

If one of these code paths disables zero-copy after the TCP transfer was started, the TCP stream will again be corrupted.
Wouldn't be safer to shutdown the endpoint completely when one of this error occurs?

**Comment by shefty** [comment]
Starting with ofi_bsock_async_done(), the first 2 checks seem fatal.  I agree that we should disable the socket completely in those cases.  The last check is the one that's actually supposed to disable future zero-copy attempts.  That's based on:

https://www.kernel.org/doc/html/v4.15/networking/msg_zerocopy.html

```For this reason, the kernel signals if data was completed with a copy, by setting flag SO_EE_CODE_ZEROCOPY_COPIED in field ee_code on return. A process may use this signal to stop passing flag MSG_ZEROCOPY on subsequent requests on the same socket.```

We can debate whether to disable future zero copies in that case or continue to try.  I don't know what the downside is to trying.  It may be that we need more intelligence here and only disable zero copy if the first attempt fails, or we fail X tries in a row.

As for MSG_ERRQUEUE, is that coming after epoll indicates that an error should be readable?

**Comment by sydidelot** [comment]
@shefty Thank you for your answer. It's unclear if `recvmsg(..., MSG_ERRQUEUE);` fails because the endpoint got disconnected and xnet_run_ep() was called with `perr=true` after epoll_wait(), or if it's the consequence of an error related to zerocopy. 
I think we add some code to early exit from `xnet_progress_async()` if zero copy is disabled (we are not supposed to read `MSG_ERRQUEUE` in this case). This log message is a bit confusing when zero copy is disabled.

Anyway, I implemented the suggestions from your previous comment (disabling the socket for the first 3 checks in `ofi_bsock_async_done()`) and I no longer hit the issue! I will push a PR for review soon.
