### ISSUE TITLE
prov/psm3: 1.15.1 is broken: ./configure: ${PSM3_HAL_INST:1}: Bad substitution

### ISSUE THREAD

**Issue by yurivict** [ofiwg/libfabric#7901]
configure uses bash syntax instead of Bourne shell syntax.

**Comment by shefty** [comment]
@acgoldma - Can you look into this?

**Comment by acgoldma** [comment]
Will look into, looks like this was fixed in the ofi build previously. https://github.com/ofiwg/libfabric/blob/773140bf3322ff3e462b0c2646baeb6f05e16755/prov/psm3/configure.m4#L39

But not fixed in the provider only build:
https://github.com/ofiwg/libfabric/blob/773140bf3322ff3e462b0c2646baeb6f05e16755/prov/psm3/configure.ac#L77

There might be other cases, I will check, but if you know them, let me know.

**Comment by acgoldma** [comment]
https://github.com/ofiwg/libfabric/pull/7906
Not sure why this was missed in previous push, but here is the final fix (hopefully 😄).
