### ISSUE TITLE
FI_WARN doesn't log by default

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#820]
FI_WARN is supposed to signal an error or a warning meaning it always gets printed. This is reflected in the provider code where it is frequently used to signal errors. Unless I'm mistaken the new logging framework has a minor mistake. The FI_LOG_TAG macro shifts by the level so when given 0 (FI_LOG_WARN) it ends up with 1 << 0 which is 1. The value in log_mask by default does not have the relevant bit set though. This is because fi_read_value returns -1 when there is nothing so the 1 << 0 doesn't get applied by default. I'm not sure how this should be fixed (it seems that fi_read_value is only used for the log level so it can simply return 0 instead of -1 in this case, that might not be the solution we're going for though). 

@shefty

**Comment by shefty** [comment]
Actually, I intentionally wanted the ability to disable all logging output, which is why FI_WARN was assigned its own bit.  This is based on feedback on other OFA software.  If a provider really wants to force a message to be displayed, I would use fprintf(stderr, ...) rather than hooking into the logging framework.

**Comment by bturrubiates** [comment]
Oh alright. That is a bit different than before. This means that some other updates are in order. Sockets uses FI_WARN for SOCK_LOG_ERROR at the moment. The providers should probably redefine their error macros to not use FI_WARN.

**Comment by shefty** [comment]
A provider could also use fi_log() directly, rather than one of the macros, in order to force output, but keep the log format consistent.  We could wrap this using FI_ERR() or something similar if there's a case where the library really must output a message with no way to turn it off.  I just know that some users don't like that option, as it can cause issues with parsing tools used by higher-level apps.
