### ISSUE TITLE
Describe what happens with posted operations when an EP is disabled

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#826]
If an EP enters into an error state, the man pages describe that all posted operations are discarded.  Should the posted operations complete in error to the CQ?

**Comment by Pgrun** [comment]
Are they completed in error, or marked as flushed (or something similar)?  If they are marked as completed in error, doesn't the consumer assume that the operation failed, as opposed to simply being the victim of some other error?

**Comment by goodell** [comment]
This would probably cost the usnic provider some data path performance and/or introduce some fragility in the software.  Unlike IB, our hardware doesn't flush operations in any fashion when the queues move into an error state.  Instead the queues are disabled and an interrupt is raised.  So we would be forced to use host software to emulate this flushing behavior, reading WQ/RQ descriptors that have been posted and signaling completions somehow.  If the completion queue is shared between two endpoints and only one of the endpoints moves into an error state, we would need to interleave software error completions with regular hardware completions for the still-functional EPs.

If this is actually important to applications I can try to prototype what this would look like over our hardware.  But I suspect it won't be pretty.

**Comment by sayantansur** [comment]
I think any of the HPC middleware on RDM EPs might have to know which operations failed when RM is disabled.

In the RDM model, an origin can address multiple targets with the same EP. An originator EP might overflow resources at a particular target, but not at other targets. It needs to know which ops specifically failed, and for which target. These ops can be retried if the app is resilient enough.

If we make the entire EP go to error state, then that basically ends up crashing the application. Not good!

I think the requirement could be fairly simple to implement - all that is required is the op_context. Although I don't know your hardware details much. I'm still happy to chat about this offline, might be simpler than typing emails :)

**Comment by goodell** [comment]
@sayantansur There's a difference between what happens when a local EP enters an error state and when a remote EP enters an error state.  I was referring to difficulties around dealing with the local EP failing.  I suspect it should be easier in some ways to deal with a remote EP failing.  I also was thinking primarily about our hardware-based DGRAM implementation.

This requirement is easier for our RDM and MSG implementations to meet *right now*, since they are currently software-based over top of datagrams.  Whether a hardware-assisted approach would be able to efficiently implement this is an open question for us.

But I'd be happy to chat offline about this to make sure we're really understanding each other.


> I think any of the HPC middleware on RDM EPs might have to know which operations failed when RM is disabled.

Did you mean "EP" or "RDM" instead of "RM" above?

**Comment by sayantansur** [comment]
@goodell I did mean RM as in "FI_RM_DISABLED". I'll schedule a quick call with you.

**Comment by goodell** [comment]
Sayantan and I chatted a bit earlier today.  We are both generally in agreement on the issues.  This ticket is a little vague right now, since the minimum desired behaviors (from the application's perspective) are a bit different depending on whether we are talking about:

- endpoint type: DGRAM vs. RDM vs. MSG
- what sort of behavior caused the endpoint to become disabled
- simple messages vs. tagged messages vs. RMA operations
- whether a TX or RX context of the EP was the thing that actually needed to be disabled

The requirements for RDM endpoints that Sayantan raised on the phone are good ones and can probably be handled by usNIC (definitely in a software implementation, probably also in a hypothetical hardware-assisted implementation).  These requirements are not, however, clearly captured on this ticket yet.

One specific example that I want to *avoid* requiring is:
- the application posts several DGRAM recvs to a context/endpoint
- the application chooses to manually disable the context/endpoint by calling some libfabric function
- the provider (and provider hardware) must then return error completions for every previously posted DGRAM recv on the context/endpoint

We have existing silicon out there that cannot support the immediately preceding example in an efficient, clean manner and I don't see that restriction changing any time soon.

**Comment by sayantansur** [comment]
Also adding that we didn't immediately see an application use case for the behavior Dave said was difficult to support. An app should be able to track all state associated with receives (via context), or memory regions that are exposed via FI_REMOTE_WRITE | FI_REMOTE_READ.

**Comment by jsquyres** [comment]
Do you want to re-target this for v1.0.1?

**Comment by shefty** [comment]
I'd like to target this for the next possible release that we can get this defined.

**Comment by shefty** [comment]
I want to limit this discussion to the local EP going into some sort of error state.

Based on current providers, it seems that the answer is that some providers will return the outstanding operations to the CQ, and some providers may not...

We can define a new secondary capability bit, FI_FLUSH, that will allow an application to request that all operations be flushed on an EP error.  If we go this route, there would not be a need to add this immediately.  We can wait until there's an application need.  For now, I can document that any pending operations will be lost.

**Comment by goodell** [comment]
Works for me.
