### ISSUE TITLE
prov/usnic: Fails fi_getinfo with ENODEV when there's no device on the system

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#828]
This causes fi_getinfo to abort with an unexpected failure.  I'm not sure when this change ended up going into the provider.

**Comment by goodell** [comment]
I'll look into this today.  This isn't a case that we typically test, sorry for the breakage.

**Comment by goodell** [comment]
Simply not having a device is not sufficient to cause the problem in my testing.  I had to `rmmod ib_uverbs` too in order to trigger the logic on `prov/usnic/src/usnic_direct/usd_ib_sysfs.c:87`.  This is the only path that I see right now in the code that could cause this behavior.

I'll transform that `ENODEV` into an `ENODATA` in the caller(s) of `usd_ib_get_devlist()` so that callers of `fi_getinfo()` won't ever see the `ENODEV`.
