### ISSUE TITLE
New fabtest proposal: Many to One load test

### ISSUE THREAD

**Issue by wckzhang** [ofiwg/libfabric#8465]
Hello, I would like to add a load test to fabtests which tests many senders trying to overwhelm a receiver and ensure correctness. This is substantially different from existing fabtests which function in a more 1:1 client/receiver fashion and thus requires completely different startup and synchronization logic. I would like feedback whether this is something we want in fabtests or if it's not an appropriate place for this test to exist.

**Comment by shefty** [comment]
See rdm_stress as a possibility

**Comment by wckzhang** [comment]
Can you confirm if I understand fi_rdm_stress properly:

It spawns a server and (num_connections - default 16) * client number processes then it parses through a json config file which tells the client what operations to perform and repeats this x iterations in a row.

If I'm correct, the server isn't configurable only the client operations and if you want to perform many ops in a row you have to individually put the op as a new json line?

So to get the behavior I want, it'd be best to add an operation iteration count option?

**Comment by shefty** [comment]
Yes, there's a single server, which can be multi-threaded.  The client will fork itself, so that there can be multiple active clients at the same time.  The clients are allowed to misbehave, such as sending a request to the server then exiting.  The entire client process repeats for some number of iterations.  For example, 1000 times, start a client that forks itself 16 times -- each client executes the commands in the config file.

For an example config file, see fabtests/test_configs/rdm_stress/stress.json.

The server only responds to the client operations.  The client tells the server what to do; it's RPC based.

As the test is, you can have up to 128 clients sending away to the server, requesting different types of responses back.  If you wanted each client to send 1000 requests, you would need 1000 entries in the json file.  Alternatively, the file format could be updated with an iteration count, as you suggest.  But, since you can repeat how many times you have the 128 clients process the config file, the test may already give you the behavior that you want.

The test was created based on stress testing used for DAOS, specifically to help debug issues with clients acting insane and the ability of the server to detect and recover from that.

**Comment by shefty** [comment]
I believe #8479 addresses this feature, but is also responsible for #8493.
