### ISSUE TITLE
prov/tcp: Need improved multi-threaded support driving progress with EQ

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#8505]
From @sydidelot 

One thing I noticed is a lock when the CQ is polled (libfabric is configured with FI_THREAD_COMPLETION and both control_progress and data_progress as set to data_progress).
This lock is initialized in xnet_init_locks():

```
/* Because we may need to start the progress thread to support blocking CQ      
 * or EQ calls, we always need to enable an active lock, independent from       
 * the threading model requested by the app.                                    
 */                                                                             
static int xnet_init_locks(struct xnet_progress *progress, struct fi_info *info)
{                                                                               
    enum ofi_lock_type base_type, rdm_type;                                     
    int ret;                                                                    
                                                                                
    if (info && info->ep_attr && info->ep_attr->type == FI_EP_RDM) {            
        base_type = OFI_LOCK_NONE;                                              
        rdm_type = OFI_LOCK_MUTEX;                                              
        progress->active_lock = &progress->rdm_lock;                            
    } else {                                                                    
        base_type = OFI_LOCK_MUTEX;                                             
        rdm_type = OFI_LOCK_NONE;                                               
        progress->active_lock = &progress->lock;                                
    }                                                                           
                                                                                
    ret = ofi_genlock_init(&progress->lock, base_type);                         
```
The comment above the function states that the lock is needed if we start the progress thread. However, progress thread is not started if attr->wait_obj == FI_WAIT_FD and epoll is supported. I think we could disable the locking in this case.

---
I believe the above comment is stale, resulting from earlier changes in the code before improved wait support was added.  We need to revisit that section of the code and see if locks are needed at all.

**Comment by sydidelot** [comment]
Thanks for the issue!

**Comment by sydidelot** [comment]
@shefty I ran some more tests with the new TCP provider and I clearly see a performance regression compared to the former TCP provider because of this lock. First of all, let me give you some details on how we use libfabric at DDN: our application creates multiple threads, and all of them run on separate cores. Each thread runs with its own libfabric domain with the following domain's attributes:
```
control_progress = FI_PROGRESS_MANUAL;
data_progress = FI_PROGRESS_MANUAL;
threading = FI_THREAD_COMPLETION:
```

In addition, each thread has its own collection of endpoints and CQs that are associated with the domain it owns. As a consequence,  domains, EPs and CQs are always accessed by the same thread.

In addition, each thread runs its own collection of PEPs and EQs that belong to the same fabric object (shared between all the domains in the application). In its main routine, the thread polls all the EQs and CQs it owns and processes incoming events.

What I expect with the above design is that all the threads run independently (and possibly lockless). This is not what I observe with the new TCP provider. 

With the new TCP provider, polling an EQ results in progressing all the domains that belong to the same fabric + the fabric itelsef.  This is what the function `xnet_progress_all()` does. Now, if we have multiple threads polling some EQs from the same fabric, that would result in a high contention against the fabric's lock `fabric->util_fabric.lock` and the domain's lock `progress->active_lock`.
To my understanding, the intention behind the new TCP provider is to have one single progress object per domain, which, as a result, allows a given domain to be progressed without locks if the application can guarantee that al accesses to that domain are serialized.
The action of polling the EQ defeats that design because an EQ is associated with a fabric and not a domain. One possible workaround would be to create one fabric per thread, but I'm not sure it's a good approach and I would like to suggest something different. 

What about having one progress structure per EQ? With one progress structure per EQ, the application could poll each individual EQ with no locks since it wouldn't require to access the domain's progress structure. That would be beneficial for multi-threaded applications that do manual progression. If a progress thread is required, we could have a progress structure at the fabric level and add each EQ's FD (retrieved from the EQ's progress structure) to it. The progress thread would basically wait for activity from the EQs.

The major change with the above proposal is in the code for connection management: when a new EP needs to be connected, we need to add the EP socket to the  EQ's progress structure and move it back to the domain's progress structure when the connection establishment is complete. 

Does this change look reasonable to you? I don't know all the different use cases you have for libfabric, but that is certainly a big issue for multi-threaded applications. If you agree with that change, I can work on a patch and push it in a PR. I don't think it's too much code unless I'm missing something.

**Comment by shefty** [comment]
I need to understand the proposal better, but I think it works.  In the libfabric v2 discussions, I'm proposing that we align on FI_THREAD_DOMAIN as the common multi-threaded model.  And, as you point out, the eq breaks that.  In the use cases I've been targeting, polling the EQ is rare, since the apps use rdm ep's.  That's why the connection code now executes when reading the CQ.  It allows for faster connection setup in the rdm case.

What you're describing sounds similar to the structure of the older code, where the fd would migrate between different poll sets (the EQ and CQ).  That can work, but I'd like to distinguish between PEPs/EPs that are exposed to the app, versus ones that are internal to an RDM EP.  In the RDM case, the CM setup is handled internally without writing a EQ entry, and the PEP is conceptually restricted to a domain.

**Comment by shefty** [comment]
After thinking on this more...

For background, the reason for fabric->progress iterating over all domains was to handle apps (fabtest) that block on the EQ until an EP is connected.  I originally didn't have that in the code.

We can move fabric->progress to eq->progress, like you suggest.  A passive EP already selects different progress engines based on whether it was created by the app or for an rdm ep.  This should allow checking for new connections without lock contention.

Dealing with a connecting EP state is more of a challenge.  An EP is protected by  domain->progress, and that's enforced throughout the code.  Trying to jump the EP between different progress engines likely requires significant changes.  I can think of a couple options.

One is to attach the socket for a connecting ep to both eq->progress and domain->progress.  Once connected, the fd can be removed from eq->progress.  When an event occurs on that socket, we'd still need to acquire the domain->progress to update the EP state.  There could be lock contention, but it's significantly more limited than the current situation -- only when actively connecting and only for the connecting ep processing.  I think this option would align with your use case and not actually result in contention.

Another option is similar to above, but simpler to implement.  The eq->progress only needs to run domain->progress if there's a connecting ep on it.  If we kept a simple count with the domain on the number of active connections, we can skip calling progress when it's zero.  This might work okay as long as connections don't occur frequently.

**Comment by shefty** [comment]
Another thought: The EQ only needs to progress domains that have an EP that will write events to that EQ.  In your case, there should be a 1:1 association between an EQ and domain.  Generically, that's 1:n.  We'd still need eq->progress, but adding this level of tracking may be fairly easy with minimal other changes.

**Comment by shefty** [comment]
Here's a proposed set of changes that I think will work for your case:

1. Remove fabric->progress
2. Add eq->progress
3. Add a domain fid_list (see ofi_util.h) to the eq.
4. When an ep is bound to an eq, add the ep->domain to the eq->domain_list.  Note fid_list_insert() handles duplicates.
5. Change xnet_start_all / xnet_progress_all to iterate over eq->domain_list.
6. Update xnet_eq_monitor_all to iterate over eq->domain_list.
7. xnet_eq_monitor_all goes away.
8. When an ep is bound to an eq, monitor the domain->progress with the eq (i.e. call xnet_eq_add_progress).  We need to handle duplicates.  We could update fid_list_insert() to return EALREADY to help trap for this.  This requires updating existing callers of fid_list_insert().  Steps 4 & 8 are part of the same function.
9. xnet_pep_listen() should reference the bound eq->progress instead of fabric->progress

I could still be missing some changes, but overall, the changes seem fairly straightforward.  In most places that we access fabric->progress or fabric->domain_list, we're getting there from an eq.

**Comment by sydidelot** [comment]
Thank you very much for your help and your very detailed explanations.

The set of changes you suggested seems good to me. Ideally, we should also modify `xnet_ep_close()` and remove any domain from the EQ list that is no longer referenced by any EP. That's not an easy change though, because it would require keeping track of the number of EPs per EQ and per domain. 
This is not needed for my particular use case because I have a 1:1 relationship between EQ and domain.
However, when closing a domain, I think we need to iterate over all the EQs of the fabric and remove the closing domain. We can probably reuse the existing list `xnet_fabric::wait_eq_list` and make it more generic.

**Comment by sydidelot** [comment]
@shefty I have pushed the PR #8570 for review, which implements the set of changes you suggested.

**Comment by shefty** [comment]
Thanks- I'll look at the changes.  I actually started making the changes Friday myself.  I think the only step I had left to complete was 8.  Hopefully we ended up near the same point.  :)

**Comment by sydidelot** [comment]
@shefty With your PR that moves the progress from the fabric to the EQ, the contention on `progress->active_lock` is now gone.
However, we can push the optimization further and convert the lock into noop operations if the domain's threading level is compatible. I looked at the code, but the change is not that trivial. The main problem is that when a EQ is created, we don't know yet what threading model will be used. This piece of information is known when the domain is bound to the EQ, which happens after the initialization of the progress locks.

I'm not sure what's the best solution here. I started considering adding a new environment variable that would select whether or not the locks should be enabled in the TCP provider, but it looks like a hack because the domain already defines the threading level.
Suggestions are very welcome. Thank you!

**Comment by shefty** [comment]
Which lock are you wanting to remove?  progress->lock / rdm_lock?

I don't believe this comment with xnet_init_locks() still applies:
```
/* Because we may need to start the progress thread to support blocking CQ
 * or EQ calls, we always need to enable an active lock, independent from
 * the threading model requested by the app.
 */
```
We only start the progress thread for the EQ/CQ if the following conditions are met:
```
		if (eq->util_eq.wait->wait_obj != FI_WAIT_FD || !ofi_have_epoll) {
			ret = xnet_start_progress(&eq->progress);
```
I'm struggling to think of a case where the wait object would NOT be an fd, and ofi_have_epoll is a system level setting.

If the user requests FI_THREAD_DOMAIN and ofi_have_epoll is true, is that enough to set the lock to NONE?  Does iouring change these checks at all?

**Comment by shefty** [comment]
Fixes for this were merged upstream.
