### ISSUE TITLE
Expected CQ behavior for multi recv

### ISSUE THREAD

**Issue by shijin-aws** [ofiwg/libfabric#8681]
In multi_recv.c test, the code will not check the `buf` and `len` fields in the CQE if the `comp.flags & FI_MULTI_RECV`, and I find shm provider will write an additional CQE with flag as pure `FI_MULTI_RECV`, `comp.buf` as NULL, `comp.len` as 0, when the posted buf is used up:

https://github.com/ofiwg/libfabric/blob/main/prov/shm/src/smr_ep.c#L1525-L1539

So if I run `fi_multi_recv` as `fi_multi_recv -e rdm -S 1024 -p shm -I 65 -s 127.0.0.1`, I find shm actually calls 66 `ofi_peer_cq_write`, with the previous 65 cqe matching the 65 `fi_send`, and the last dummy one.

Reading the CQ man page it says

```
buf
    The buf field is only valid for completed receive operations, and only applies when the receive buffer was posted with the FI_MULTI_RECV flag. In this case, buf points to the starting location where the receive data was placed.
``` 

So I am a bit confused, according to multi_recv.c, application can ignore the comp.buf when the comp.flags has `FI_MULTI_RECV`  but not `FI_RECV`, so it is ok provider to write additional a dummy cqe with pure `FI_MULTI_RECV` when the posted buf is all consumed? And the statement `... only applies when the receive buffer was posted with the FI_MULTI_RECV flag` is restricted to CQE with flags  having`FI_RECV` bit set?

**Comment by aingerson** [comment]
Not sure I understand the exact question, but I'll try to understand the expected behavior.
The FI_MULTI_RECV flag just means the multi receive buffer has been consumed. It can be coupled with FI_RECV which would indicate that the last slot in the buffer has been consumed but can also just be used alone to indicate the buffer itself has been used up. If the flag is just FI_RECV, then it means a message was received. If the buf field is set, it means it was part of multi receive buffer.
Shm (and other providers) post the extra dummy entry with just the FI_MULTI_RECV because it makes the implementation simpler.

**Comment by shijin-aws** [comment]
>The FI_MULTI_RECV flag just means the multi receive buffer has been consumed. It can be coupled with FI_RECV which would indicate that the last slot in the buffer has been consumed but can also just be used alone to indicate the buffer itself has been used up. If the flag is just FI_RECV, then it means a message was received. If the buf field is set, it means it was part of multi receive buffer.
Shm (and other providers) post the extra dummy entry with just the FI_MULTI_RECV because it makes the implementation simpler.

@aingerson Thanks! This exactly answers my question. I was confused because the current efa code goes with

>  It can be coupled with FI_RECV which would indicate that the last slot in the buffer has been consumed

but shm goes with `but can also just be used alone to indicate the buffer itself has been used up` .

Your answer helps me understand both implementation are legitimate.
