### ISSUE TITLE
prov/psm3: `--disable-shared` causes "No HALs registered" error

### ISSUE THREAD

**Issue by raffenet** [ofiwg/libfabric#8979]
**Describe the bug**
Error message from psm3 provider during initialization.

**To Reproduce**
```
./autogen.sh
./configure --prefix=$PWD/i --disable-shared
make -j; make install
FI_PROVIDER=psm3 i/bin/fi_info
```
```
compute-386-08% FI_PROVIDER=psm3 i/bin/fi_info
compute-386-08:pid2800529.fi_info: No HALs registered
fi_getinfo: -61 (No data available)
```

**Expected behavior**
No error message. If psm3 cannot work with `--disable-shared`, then configure should disable the provider.

**Environment:**
Linux (Ubuntu 22.04)

**Comment by acgoldma** [comment]
I have been able to reproduce. Oddly, looks like the constructors that are included in other files are working, but the ones in the hals are not.

**Comment by acgoldma** [comment]
Comment from #8972:

looks like the `__psmi_hal_verbs_constructor` is grepable in `libfabric.a`, but not in `fi_info`.

It looks like constructors are not always included when linking a static lib to an executable. 

I was able to fix this for fi_info by adding this:
```diff
 util_fi_info_SOURCES = \
        util/info.c
 util_fi_info_LDADD = $(linkback)
+util_fi_info_LDFLAGS = -Wl,--whole-archive,src/.libs/libfabric.a,--no-whole-archive

 util_fi_strerror_SOURCES = \
        util/strerror.c
```
This will link the whole archive instead of just the sections `fi_info` calls.

Not sure why some constructors worked and others did not. 
Specifically all `psm3` constructors, excpet the ones to register the HALs, worked fine.

Structurally, `__psmi_gethostname_lock_constructor()` works the same way as the hals, but seems to work fine.

As a work around for now, using the above patch should work.
