### ISSUE TITLE
libfabric-2.0: Completion changes (CQs and cntr)

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#9017]
- No completion ordering guaranteed
- Restrict a standard endpoint to a single CQ.  Separate CQ for sends and receives no longer supported.
- Scalable endpoints still support separate CQs.  Technically, an app can create a scalable endpoint with 1 Tx and 1 Rx context and achieve the same behavior they have today.  From the viewpoint of the provider, it can optimize for a different threading model under the proposed FI_THREAD changes.
- Open question: A standard endpoint can have up to 4 counters attached.  Can that be limited to 1, possible for RMA only?

**Comment by shefty** [comment]
- Proposal: Restrict FI_SELECTIVE_COMPLETION to transmit operations only.  Use on receive side seems questionable.  Generates a conflict with the use of FI_REMOTE_CQ_DATA.  If an RMA with CQ data consumes a receive buffer at the target, the CQ data will be lost.  This isn't true if a receive buffer is not consumed.

**Comment by thomasgillis** [comment]
From our usage, I think it could still be useful to have `selective_completion` when using `fi_(t)recv`. Maybe another solution would be that `FI_REMOTE_CQ_DATA` always generates an entry in the cq?

**Comment by shefty** [comment]
Can you describe what the use case is to receive a message without the receiver being notified?

AFAIK, no existing HW can support the combination of only generating a CQ entry when remote CQ data is included as part of the transfer.  So, this would end up as a SW based discard, just below the API.  But that's what current implementations do anyway...  It's at least trapped at a lower layer.

Disallowing mixing selective completion with CQ data is more to simplify the use of the API.  That's talking about the sender of a message being able to override the (loca) behavior requested by the target application, which is non-intuitive and seems wrong.

**Comment by thomasgillis** [comment]
The only usage I can think of would be a 0-byte exchange that could be used for acknowledgment and tracked with a counter, but it might be a very weak one.
If it's not supported in hardware, then there is no need to consider it

**Comment by kdunder** [comment]
Counters are a viable alternative to having a CQ entry for many use cases.  A target of an operation should be able to control what competions are generated.  Just because you want to place CQ Data into my CQ does *not* mean that I should have to let you. Control of counters and CQ entries should be independent.

Separating TX and RX CQs has an important use case associated with resource exhaustion/resource management at the target.  There are reasons for an application and/or provider to want the TX and RX CQ to be merged and reasons to want them separated.  Force merging them has little advantage.
