### ISSUE TITLE
Should fi_info->rx_attr->size limit the length of the unexpected message queue?

### ISSUE THREAD

**Issue by a-szegel** [ofiwg/libfabric#9046]
The following is the [definition of the size field
](https://ofiwg.github.io/libfabric/v1.13.1/man/fi_endpoint.3.html) of `struct fi_tx_attr` and `struct fi_rx_attr` defined in fabric.h.

> size
> 
> The size of the transmit context. The mapping of the size value to resources is provider specific, but it is directly related to the number of command entries allocated for the endpoint. A smaller size value consumes fewer hardware and software resources, while a larger size allows queuing more transmit requests.
> 
> While the size attribute guides the size of underlying endpoint transmit queue, there is not necessarily a one-to-one mapping between a transmit operation and a queue entry. A single transmit operation may consume multiple queue entries; for example, one per scatter-gather entry. Additionally, the size field is intended to guide the allocation of the endpoint's transmit context. Specifically, for connectionless endpoints, there may be lower-level queues use to track communication on a per peer basis. The sizes of any lower-level queues may only be significantly smaller than the endpoint's transmit size, in order to reduce resource utilization.

What is tx_size/rx_size supposed to actually limit? My interpretation is that the tx_size should control the number of tx_entry's, and the rx_size should control the number of rx_entry's. The tx_entries correspond to how many messages the sender is trying to send at one time.  The rx_entries correspond to the number of recv's that a receiver is trying to progress at one time. For the receiver, I think this means injects, large messages (greater than the transport size), and unexpected messages (without posted buffers). 

If the rx_size limits the number of unexpected messages, this would require the user to queue unexpected messages once the receiver has met its threshold.

Does our API impose strict limits which define our behavior (and potentially add extra work to our user), or do we grow indefinitely until we run out of memory?

## Example SHM Implementation
SHM has a cmd context pool defined in `smr_endpoint()`, and this bufpool will expand indefinitely until the system runs out of memory.  Should it do this?  Should this buffer pool ever shrink?  If a receiver doesn't post all its receives right away (blocking MPI recv's), the unexpected message list can grow VERY long.

```
int smr_endpoint(struct fid_domain *domain, struct fi_info *info,
		  struct fid_ep **ep_fid, void *context)
{
...
	ret = ofi_bufpool_create(&ep->cmd_ctx_pool, sizeof(struct smr_cmd_ctx),
				 16, 0, info->rx_attr->size,
				 OFI_BUFPOOL_NO_TRACK);
```

And SHM casts cmd_ctx directly into rx_entries here:
```
static int smr_alloc_cmd_ctx(struct smr_ep *ep,
		struct fi_peer_rx_entry *rx_entry, struct smr_cmd *cmd)
{
	struct smr_cmd_ctx *cmd_ctx;

	cmd_ctx = ofi_buf_alloc(ep->cmd_ctx_pool);
	if (!cmd_ctx) {
		FI_WARN(&smr_prov, FI_LOG_EP_CTRL,
			"Error allocating cmd ctx\n");
		return -FI_ENOMEM;
	}
	memcpy(&cmd_ctx->cmd, cmd, sizeof(*cmd));
	cmd_ctx->ep = ep;

	rx_entry->peer_context = cmd_ctx;

	return FI_SUCCESS;
}
```

The rx_entries get added to the unexpected message queue (which will grow forever).

**Comment by shefty** [comment]
There's no one answer as the values are provider dependent.  It is changes based on the endpoint type.

The MPI spec technically requires infinitely large receive side buffering.  There are MPICH tests which, by default, require an unexpected queue of 100 for a single source.  Assuming that's acceptable, because not only does the MPI spec allow that, but MPI tests verify that it works, if you scale that to even a couple hundred of nodes, the unexpected queue can be huge.

Anyway, let's start with connected endpoints.  The tx size and rx size would be directly related to the number of operations that can be posted to the endpoint before the caller starts getting back EAGAIN.  The sizes could map to HW resource allocations, which might trickle upward as pinned memory pages.  Ideal size values would be deep enough for network transfers to sustain achievable bandwidth for some fixed sized transfer (say MTU sized or 8k).

Because some HW allocates fixed sized entries for the send and receive queues, the tx size and rx size might map directly to the number of entries.  However, other HW uses variables sized entries for the send and receive queues.  In the latter case, the tx size may be the total number of iovecs that the queue can reference.  If each send/receive has a single iovec, the two HW solutions behave similarly.  But if the sends/receives can have anywhere from, say, 1 to 4 iovec entries, then the number of sends/receives that can be posted will be smaller than the iovec.

For unconnected endpoints, the definition of what size means varies even more.  If the HW has true unconnected semantics, the sizes might be the number of entries available on the HW queues.  (Or the size might be the total number of iovecs supported...)  If the HW uses connection-oriented semantics underneath, the size value may not map to HW resources at all.

This discussion is related to what the size value means for the AV.  Is the AV size a limit or an optimization value?  In practice, having a hard limit on the size of the AV doesn't work, because upper level software has no idea what the limit needs to be at start-up time.  So, providers that want to work with real apps need to either set an internal limit that's well-above what the user requested, potentially wasting resources, or grow dynamically.  The Rx size is similar.

shm probably needs a more intelligent algorithm for determining when to copy a message to an unexpected queue.  Since shm uses a single command queue for all ranks, that algorithm needs to feed back to each source, so a fast sender backs off and doesn't overrun the receiver.

**Comment by a-szegel** [comment]
I think the libfabric API needs to take a solid stance on our behavior so we can align our providers to be plug and play (especially for libfabric 2.0).

**Comment by shefty** [comment]
It's literally impossible to implement support for all "legal" MPI apps.  I'll argue to only support sane ones.  Providers must support an unexpected queue.  It should be expected that that queue size will be limited, but it should also be expected that a single source won't fully consume it.  (TCP has separate queues per source).

**Comment by a-szegel** [comment]
Do we have a way for a user to tell us that they require an infinite unexpected message queue?

**Comment by shefty** [comment]
No - MPI technically requires it, but such a thing isn't possible anyway.  MPI doesn't even know what the application is trying to do, so can't convey any limits downward.

The provider basically needs to push back on the sender once its queues are full.

**Comment by wzamazon** [comment]
I think it is fair to say that MPI expect libfabric to be able to handle unexpected message (up to what system memory would allow), which libfabric providers do met.

**Comment by lrbison** [comment]
I'm curious about why `fi_rx_size_left` is deprecated.  This would be the path for MPI or some app to recognize they were about to fill the queue.

**Comment by a-szegel** [comment]
@shefty 

> The provider basically needs to push back on the sender once its queues are full.

This is more or less SM2's behavior.  When the SM2 sender's freestack is empty b/c it is in receivers unexpected message queue's, the sender says that we cannot send any more messages.  It is up to the receiver to posts receives and unblock the transport.  This makes a lot of sense to me for a normal HPC application.  It falls apart when we try to say that we want to support ANY possible application up to system limits.

**Comment by a-szegel** [comment]
I am in favor of extending the API to clearly communicate the providers capability to queue unexpected messages to the upper layer, and let the upper layer deal with it.

**Comment by shefty** [comment]
Use of fi_rx_size_left() is inefficient and doesn't actually guarantee that the next posted operation will receive.  In order to support the call, the provider either needs to maintain counters internally, which get updated with every transfer/completion, or dynamically calculate the value when called.  Both are slower than the app just trying to post the operation and getting back EAGAIN, which the app needs to handle anyway.  So, its presence is problematic from an implementation and usage standpoint. (Plus, given that we can't define what 'rx_size' precisely means, how much is left isn't any more defined.)

**Comment by lrbison** [comment]
I think the question we are debating internally boils down to a single point:

Should providers have an unbounded list of pending sends and receives to avoid deadlock, or should we set some maximum amount of memory dedicated to these pending operations, and if so, can the application clearly realize when that allocation is full.

**Comment by a-szegel** [comment]
https://github.com/ofiwg/libfabric/pull/9048

**Comment by mjkoop** [comment]
As @shefty noted, a valid MPI program could still potentially exceed whatever limit a provider sets. If you do provide a mechanism to tell the sender to 'retry' when it's unexpected and "out of space," you will need to adjust your protocols related to completion, which is likely going to cause you performance challenges.

**Comment by shefty** [comment]
MTL and BTL are OpenMPI implementation details and not generic for all apps or even all MPIs.

Should a provider support tag matching or not?  That's implementation specific.  For efficiency, the best answer is yes, it should.  Then the provider owns the rendezvous protocol and use transport level flow control to back off senders.

It doesn't really matter where the data is buffered.  MPI allows infinitely sized receive side buffering and the receiver to request messages out of order relative to the sender.  It's perfectly valid for an MPI receiver to block waiting on the 1000th message that a sender will send.  But that doesn't mean MPI apps are insane enough to do this.  Providers can limit infinity however they choose.  For HW based tag matching, the limit may be significant.

For reference, in the initial implementation of the net (tcp v2), I had NO unexpected message support.  That worked for a large number of apps.  For the few that it didn't, increasing the unexpected queue depth to 1 message of 64 bytes was sufficient.  It wasn't until I tried running the mpich testsuite that I had to increase it to 64 messages of arbitrary size.  That was enough for all but a single test app.

You'll need to make a trade-off.  Unexpected message aren't 'unexpected'; they're early.  The sender may simply be faster than the receiver.  Or the receiver may be wanting a message out of order relative from the sender.  If the receiver is just slow posting the matching receive, then it's best to use transport flow control to back off the sender and only queue the topmost message.  This approach argues against using a rendezvous protocol.  If the receiver wants a message out of order, then you need to queue messages into an unexpected queue.  This approach argues for a rendezvous protocol.

libfabric doesn't know which situation we're in.  But, neither does MPI.  Trying to push the problem up the stack doesn't really solve anything.

**Comment by a-szegel** [comment]
I think we need to tell the upper layer what we are doing, so that they can adjust their behavior accordingly, or pick a provider that suits their needs.

**Comment by shijin-aws** [comment]
>mpich testsuite 

@shefty Is it something similar to ompi-tests? Do you have a link?

**Comment by shijin-aws** [comment]
>These are tests included with mpich and included along with the mpich source. https://www.mpich.org/downloads/

Thanks, is Intel CI currently running this test for PRs?

**Comment by shefty** [comment]
Only a few of them.  The full set of tests takes a couple of hours, and we don't want per PR CI to take that long.  Otherwise, when there are multiple PRs open, that turns into days.  They are run as part of MPI releases.

**Comment by wenduwan** [comment]
@shijin-aws Should we close this issue?

**Comment by shijin-aws** [comment]
I think so... The fact is MPI requires infinite large unexpected msg queue, and there is no handy way for MPI to provide a limit for the unexpected message size. And we agreed to make shm support infinite unexpected message future Libfabric releases, likely >= 1.20.0

**Comment by shijin-aws** [comment]
I would let @a-szegel close it.
