### ISSUE TITLE
[1.18.1] prov/verbs: Double FI_SHUTDOWN event received (regression from 1.18.0)

### ISSUE THREAD

**Issue by sydidelot** [ofiwg/libfabric#9123]
With 1.18.0 and below, there is an implicit assumption that the verbs provider writes the `FI_SHUTDOWN` event only once when an endpoint shuts down.
With 1.18.1, this assumption is no longer true and the application may receive 2 `FI_SHUTDOWN` events for the same endpoint.
This new behavior was introduced by the following commit: https://github.com/ofiwg/libfabric/commit/2abe57cd893d70a52137758c2c5b3c7fbf0be2c1

With the above commit, the first `FI_SHUTDOWN` event is written by `vrb_shutdown_qp_in_err()` and the second originates from `vrb_eq_cm_process_event()` when the CM event `RDMA_CM_EVENT_DISCONNECTED` is received.

One problem I see in the code is that `vrb_shutdown_qp_in_err()` moves the QP to an error state, but `ep->id` remains valid. As a consequence, the next call to `rdma_disconnect()` is allowed to generate the CM event `RDMA_CM_EVENT_DISCONNECTED`.

**Comment by sydidelot** [comment]
FYI, the order is not always `vrb_shutdown_qp_in_err()` then `RDMA_CM_EVENT_DISCONNECTED`. Sometimes the CM event happens before.

**Comment by chien-intel** [comment]
do you have a specific test case that's demonstrating this behavior?

**Comment by shefty** [comment]
@chien-intel , @sydidelot works with a storage app (DDN).  He's likely seeing the issue there.

The vrb_ep likely needs its own state that we can track, so we can discard rdma_cm events if we're in the wrong state.  I have plans to add an vrb_ep state, but I'm not there yet.  The code currently uses the ibv_qp.state, which can be modified outside of libfabric (via libibverbs).

**Comment by sydidelot** [comment]
@chien-intel @shefty Sorry for the missing context: I'm seeing the issue with the storage app we are developing at DDN, which is closed source unfortunately. The app uses MSG endpoint (no RDM) and the double FI_SHUTDOWN event triggers on normal endpoint shutdown on both client and server sides.
I don't think the pattern is specific to our code and it can probably be reproduced on a synthetic application. FYI, I will be on PTO for the next 3 weeks and I won't be able to progress on this issue. For the time being, I reverted the patch in my local branch.
I agree with @shefty and I seems to me that the verbs provider needs its own state.

**Comment by chien-intel** [comment]
https://github.com/ofiwg/libfabric/commit/2abe57cd893d70a52137758c2c5b3c7fbf0be2c1 solved the problem of a QP transitioned to error state by the HW and the only notification to SW is with error CQE and flushed outstanding work.  QP state held by (any) software is RTS.  Providing another stale software state won't help this issue.
In order for vrb_shutdown_qp_in_err() to send up a FI_SHUTDOWN, there has to be a CQE with status that's not IBV_WC_SUCCESS and QP in error state.  This is part of the reason I asked for a test case to see what's going on.  If I have to guess what's happening, most likely there's flushed CQE and somehow this check is false: 	if (!ep || !ep->ibv_qp || ep->ibv_qp->state == IBV_QPS_UNKNOWN || !ep->eq)
To avoid this, add addition check on wc->status against IBV_WC_WR_FLUSH_ERR in vrb_poll_cq.

**Comment by shefty** [comment]
The problem is that the *endpoint* state, which is what libfabric cares about, can be driven either by reading from the CQ or the EQ.  We don't know which will come first - an RDMA CM event or a CQ error.  In either case, the *endpoint* needs to transition into some 'disconnected' state, and if we're already in the disconnected state, do nothing.

The second shutdown event is coming from the RDMA CM and isn't related to the QP state, but the out-of-band connection management that IB uses.  IB HW manages a QP state.  The RDMA CM manages a connection state.  Those two states are not guaranteed to be completely in sync with each other, which is what is happening here.  And libfabric is actually more concerned with the connection state than the QP state, because the connection state is what is visible to the user.  Only libfabric has no way to access the connection state that's maintained by the RDMA CM.

Similar to how the tcp provider maintains a connection state for the endpoint (even though the kernel maintains its own state for the socket), we need to manage an endpoint state for the verbs provider.  So, regardless of whether we read from the CQ or EQ, we check the endpoint state, and if it's 'connected', we transition to 'disconnected' and generate a shutdown event.  If we're in the wrong state, we skip generating shutdown.

We're going to need a state on the verbs endpoint anyway to integrate RDM endpoint support directly into the provider, as was done for tcp.

**Comment by chien-intel** [comment]
I needed something to notify RXM to close the QP.  FI_SHUTDOWN is actually not the right event but did the job.  If only there's some internal mechanism to accomplish this...

**Comment by shefty** [comment]
The shutdown event is likely fine.  We just need to ensure that it's only reported once.  RxM has state checking and likely handles multiple events being reported.  DDN uses msg endpoints directly.  I can work on adding state to verbs endpoints next week.

**Comment by shefty** [comment]
As an update, I am working on this, just very slowly.  Targeting a fix for v1.19 and v1.18.2

**Comment by shefty** [comment]
@sydidelot - Can you see if PR #9175 fixes this issue?

**Comment by shefty** [comment]
#9175 works with main and v1.19, but cannot be picked into v1.18.x without pulling in the changes to the progress model.  An alternative fix is needed for v1.18.x.

**Comment by shefty** [comment]
PR #9201 is a simple hack to avoid the duplicate shutdown on v1.18.x.

**Comment by shefty** [comment]
Fixes should have been applied to v1.18.x, v1.19.x, and main.  I just don't have any easy way to verify the fix.

**Comment by sydidelot** [comment]
@shefty sorry for the late reply. I was able to verify the fix for `1.18.x` and `main`: no double shutdown events anymore! 
Thanks a lot for fixing the issue !

**Comment by shefty** [comment]
@sydidelot - no problem, thanks for reporting and verifying.  I assume there's a lot of vacation and travel happening during the summer.
