### ISSUE TITLE
prov/psm3: `fi_atomicmsg` does not work with FI_REMOTE_CQ_DATA

### ISSUE THREAD

**Issue by thomasgillis** [ofiwg/libfabric#9134]
**Describe the bug**
is seems that the `psm3` provider does not support the usage of `FI_REMOTE_CQ_DATA` when doing atomics.

I have a code (working with `tcp;ofi_rxd` FWIW) that uses non-zero `msg.data` field together with `flags |= FI_REMOTE_CQ_DATA`.
The cq entry for the data never appears on the target side, even if the the `fi_atomic` call completes.

Looking at the code it seems that this has not been implemented?
If this is the case, returning an error would be helpful to the user.
Also, is there any plan to support it in the future?

Thanks for your help :-)

**Comment by acgoldma** [comment]
Hello, we will look into this, but in the meantime, please provide us with a bit more information. 

See Bug Report Guide: [here](https://github.com/ofiwg/libfabric/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

**Expected behavior**
If needed, a clear and concise description of what you expected to happen.

**Output**
If applicable, add output to help explain your problem. (e.g. backtrace, debug logs)

**Environment:**
OS (if not Linux), provider, endpoint type, etc.

**Additional context**
Add any other context about the problem here.

**Comment by thomasgillis** [comment]
that's a good point, thanks. I wrongly assumed it was supported with the `data` entry in `fi_msg_atomic`
