### ISSUE TITLE
usnic: implement counter support

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#950]
`fi_cntr_open()` and friends currently return `-FI_ENOSYS`, so we end up failing (rather than `Notrun`-ing) fabtests like `fi_rdm_cntr_pingpong`.  Either implement this or see if there's a way we can better advertise this lack of support at `fi_getinfo` time.

**Comment by shefty** [comment]
The FI_RMA_EVENT capability bit can be used to indicate that RMA based counters are not supported.  I.e. a counter cannot be used to count remote issued RMA read/write or atomic operations.  Counters for entirely local events are expected to be supported (subject to provider documentation stating otherwise), as those should be relatively easy to implement.

**Comment by shefty** [comment]
usnic is still supported, but has not been updated in several releases.  Closing very old issues.
