### ISSUE TITLE
verbs: Implement fi_setname

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#976]
Right now `fi_setname()` on a passive endpoint causes a segfault (the jump table entry isn't filled in).  It should ideally be correctly implemented, but at the very least should be filled in with `fi_no_setname()`.

**Comment by shefty** [comment]
@a-ilango - Arun is handling most of the verbs provider enhancements.  Tagging him so that he's aware of this issue, but I'm not sure if or when he'll be able to get to this.  This functionality will be needed to complete the rsocket port over OFI verbs provider.

I think this may be as simple as mapping fi_setname to rdma_bind_addr().
